src/components.d.ts, src/components/color-gen/color-generator/color-generator.tsx, src/components/color-gen/demo/index.html, src/components/docs-menu/docs-menu-map.ts, src/components/docs-preview/docs-preview.scss, src/components/docs-preview/docs-preview.tsx, src/components/docs-root/docs-root.tsx
We had a complicated setup where the color-generator would emit an event and then the preview would listen for it and operate on the iframe. This removes that logic in favor of one generic method to communicate with the preview window.
Now you emit a `previewMessage` event and the event's `detail` key will be forwarded on to the preview iframe.
```ts
@Event() previewMessage: EventEmitter;
updatePreviewSomehow() {
this.previewMessage.emit({ foo: 'bar' });
}
```
And then listen for it in the iframe:
```ts
window.addEventListener('message', console.log);
//=> { data: { foo: 'bar' }}
```
=> refactor(preview): add generic preview messages with "previewMessage" event

src/content/native.md
Injectable was spelled as inejectable
-
-
-
**Fixes**: #
=> Fixed a typo

src/components/img-zoom/img-zoom.tsx, src/markdown.ts
Only when undefined is passed, the default value is used, in this case, the render passes null.
=> fix(img-zoom): title is "null"

src/content/native.md
Fixed the  Ionic Platform import because the import has changed with Ionic v4 from `ionic-angular` to `@ionic/angular`
=> docs(native) Fixed Ionic Platform  import

src/content/components.md
The List section is contains an image in the example using the `img` tag which is a self closing tag in HTML5 and it will crash the browser if you try to load it using `ionic serve` as is.
- Removing the `</img>` tag is enough to correct this.
=> [V4] Remove img closing tag

src/content/theming/advanced.md
Reviewing the docs as part of the doc party. Noticed a missing '#' and felt that 'out' was a "busy word"
=> doc(theming): add missing # and remove busy word

.github/CONTRIBUTING.md
- The old repository URL `https://github.com/driftyco/ionic-docs` is no longer valid.
- Update the repository name to the current location/name of the repository
- Add Markdown link from the name to the repository URL address
=> docs(.github): update repository location

src/components/docs-menu/docs-api-map.ts
In  Docs API Reference 4.0.0-beta.15 the list of components is not displayed, because docs-api-map.ts apiMap still is "4.0.0-beta.0"
Update docs-api-map.ts
=> Update apiMap to 4.0.0-beta.15, in accordance with src/versions.ts

src/content/intro/concepts.md
"for apps the are" changed to "for apps that are"
=> Fixing typo

src/content/faq/glossary.md
=> doc(glossary): fix typos

src/content/layout/css-utilities.md
Order of examples in table "Flex Container Properties" did not match the order of example above.
Specifically, the justify-content-between and justify-content-around were reversed
Inconsistency in the order of the table and examples
- Fix the order of the table
=> Fix order of table of "Flex Container Properties"

src/components.d.ts, src/components/code-color/code-color.css, src/components/code-color/code-color.tsx, src/components/color-gen/css-text/color-gen-css-text.css, src/components/color-gen/css-text/color-gen-css-text.tsx, src/components/layered-colors-select/layered-colors-select.css, src/components/layered-colors-select/layered-colors-select.tsx, src/components/stepped-color-generator/parse-css.ts, src/components/stepped-color-generator/stepped-color-generator.css, src/components/stepped-color-generator/stepped-color-generator.tsx, src/content/theming/advanced.md
Updates the advanced theming documentation to use the latest step variables, from this PR: https://github.com/ionic-team/ionic/pull/16543
- updates the documentation to include the correct variables
- renames the `color-block` component to `layered-colors-select` as this is a better description of what it is
- moves the code color block component out of the layered colors select component into its own `code-color` so it can be reused inline with hex values
- adds stepped color generator
Example of the newly separated component being used:
Adds a stepped color generator:
=> docs(theming): update stepped color documentation to latest

src/components/section-switch/section-switch.scss
The "v4 beta" badge in the header was adding width to the menu and causing the main content area to be slightly compressed. This removes the badge from the layout flow with absolute positioning.
=> fix: remove beta badge from grid flow

src/content/pro/deploy/api.md
await is missing in sync() example for getCurrentVersion() call. Result is actually a promise and not the ISnapshot result which results to an error 2 lines after (versionId doesn't exists for a Promise)
sync() example is not generating an error
- replace `const currentVersion = Pro.deploy.getCurrentVersion();` by `const currentVersion = await Pro.deploy.getCurrentVersion();`
**Fixes**: #
=> deploy.getCurrentVersion() returns a Promise so need an await

src/content/building/ios.md
Fixes an inconsistency about Capacitor between the iOS and Android documentation.
**Fixes**:
- Adding the change from @dwieeb's previous commit (https://github.com/ionic-team/ionic-docs/commit/cbb617c0d02e7326db415373ec605348326b79cc) on the Android docs to the iOS doc
=> docs(ios): livereload with capacitor works

src/content/intro.md
Ionic Pro was rebranded in late November to Ionic Appflow. This makes some minor changes to the documentation to reflect these changes.
**Fixes**:
- Updates "Ionic Pro" references to "Ionic Appflow", including links
- Clarifies section on Appflow capabilities, including paid upgrades
- Minor formatting changes
=> docs(intro): Changing Ionic Pro references to Appflow

src/content/developer-resources/guides/first-app-v4/ios-android-camera.md
constructor example is missing the closing curly brace.
-
-
-
**Fixes**: #
=> fix(first-app-v4): missing curly brace

src/content/developer-resources/guides/first-app-v4/intro.md, src/content/developer-resources/guides/first-app-v4/ios-android-camera.md
Several mentions of a non-existent about page, but it is no longer (assuming this is from v3?) called that, its tab2.
The references are confusing but then the snippet suggesting the code `<ion-tab-button tab="about">` actually breaks the app.
- Fix mentions of about page
**Fixes**: #242
=> fix(first-app-v4): about page refs - fixes #242

src/content/building/migration.md
Better dev docs read.
- Typo from `rouer-outlet` to `router-outlet`
**Fixes**: # Spelling
=> docs : Line 180 - typo fix

scripts/build-pages/index.ts, scripts/build-pages/page-types/api.ts, scripts/build-pages/page-types/cli.ts, scripts/build-pages/page-types/native.ts, scripts/build-pages/page-types/static.ts, src/components/page/templates/api.tsx, src/components/page/templates/cli.tsx, src/components/page/templates/default.tsx, src/components/page/templates/native.tsx
This adds the URL path as a key on each page object during build so it can be used on the client instead of reading the router history.
=> Add path key to page objects

src/pages/theming/advanced.md
https://ionicframework.com/docs/layout/color-generator is not found instead the previousUrl should point to https://ionicframework.com/docs/theming/color-generator/
=> fix(docs): change previousUrl of Color Generator

src/components/menu/templates/components.tsx
picker-column is only used internally and is excluded from the
generated docs data.
=> fix: remove picker-column from components menu

src/components/menu/templates/main.tsx, src/pages/utilities/config.md
This PR adds basic "Config" documentation. It also creates a "Utilities" section for documenting other APIs like this.
=> docs(): add Utilities and Config sections

src/pages/theming/css-variables.md
This PR fixes the issue #391.
That's just my proposal of an explanation about where user can override default ionic variables.
=> docs(theming) Explain where to place variables

scripts/build-pages/markdown-renderer/heading.ts
In some cases, we are rendering headings that contain inline html
instead of just text, this parses headings during build using JSDOM
and uses the parsed textContent as the hash instead
=> feat(build): parse heading for textContent before slugifying

src/pages/installation/android.md
It's not just recommended, it's required. I tried this today and there is a flat out version check in the source code that locks it to JDK8.
Also, added https to the download link as the site runs on that now.
FYI if you don't have much time to research this then here is some help:
I also worked with the cordova-android team to clarify this in their error messages and it's been accepted:
- https://github.com/apache/cordova-android/pull/619
- https://github.com/apache/cordova-android/pull/620
If you look in the files changed the version check is just around those changed lines.
=> docs(installation/android.md): strengthen JDK8 requirement wording

src/components/header/header.tsx, src/components/section-nav/section-nav.tsx
The development can't serve the root without a trailing slash,
so let's add these for now.
=> chore: add trailing slashes to header root links

src/pages/intro/browser-support.md, src/styles/global.css, src/styles/pages/browser-support.css
Cleans up the copy on the browser support page and presents the support lists in a different way.
=> content(browser-support): copy edits and table styles

src/components/nav/nav.tsx
This ensures that links in the nav are set as active whether or not there is a trailing slash in the URL.
```
/docs/api/fab
/docs/api/fab/
```
=> fix(nav): use non-strict matching for stencil-route-link

src/pages/appflow/quickstart/installation.md
* Added some breaks to the command prompt for installing the Appflow SDK to make it easier for copy/paste (cc @mhartington)
=> fix(appflow): Tweak Appflow SDK setup CLI prompt

src/pages/intro/versioning.md
Move the link to the changelog into the paragraph copy, instead of linking it awkwardly after.
=> docs(versioning): link to changelog in copy

src/pages/developer-resources/guides/first-app-v4/creating-photo-gallery-device-storage.md
While going through the *first-app-v4* Ionic tutorial, I ran into an issue with the grid layout. The tutorial was using the older syntax of `col-6` instead of `size="6"`, which doesn't work properly on V4 of Ionic and caused the photos to all display on one line instead of inside a grid.
By using the updated grid syntax located in the current docs at https://ionicframework.com/docs/api/grid/, the layout performs as intended by adding two photos per row in the grid. This PR updates the documentation to reflect the current grid documentation.
=> Update outdated ion-col syntax to match current grid documentation

src/demos/api/anchor/index.html, src/demos/api/avatar/index.html, src/demos/api/chip/index.html, src/demos/api/icon/index.html, src/demos/api/note/index.html, src/demos/api/radio/index.html, src/demos/api/reorder/index.html, src/demos/api/segment/index.html, src/demos/api/thumbnail/index.html, src/demos/api/toggle/index.html
adds the following demos
- anchor
- avatar
- chip
- icon
- note
- radio
- reorder
- segment
- thumbnail
- toggle
taken from API demos in ionic
references #463 
:warning: needs the images for avatar/thumbnail :warning:
=> docs(demos): add demos for api docs

src/demos/api/toolbar/index.html
Adds examples for ion-toolbar (ion-header, ion-buttons, ion-title, etc)
references #463
=> docs(toolbar): add toolbar examples

src/pages/developer-resources/courses.md
Per @adamdbradley, I am requesting to add two Pluralsight courses to the Courses page, along with a description of each. The links are direct links into Pluralsight, with no extra tracking or affiliate-type information.
=> Add two Pluralsight course links

src/components/code/code.css, src/components/tabs/tabs.css
=> fix(usage): remove margin between heading and usage examples

src/components/root/root.css, src/components/root/root.tsx
Rather than try to set the menu state `isCollapsed` based on the viewport size during render, this changes the state name to `isMenuToggled` and the default state is in CSS only.
=> fix(menu): base default menu state on viewport size

src/components/menu/templates/main.tsx, src/pages/faq/tips.md, src/pages/installation/cdn.md, src/pages/layout/css-utilities.md, src/pages/layout/global-stylesheets.md, src/pages/layout/grid.md
- adds a page for global stylesheet information
- adds information on including CSS for angular, stencil, and the bundle to packages/cdn
- renames some headings in ionic packages
- adds blockquote in CSS utilities that links to including them
closes #54
=> docs(layout): add information on global stylesheets

src/pages/publishing/progressive-web-app.md
The example Firebase config shows **sw.js** as the name of the service worker for which a cache policy should be set. However, the default filename used by @angular/pwa is **ngsw-worker.js**. This change reflects the default filename.
=> update firebase config with default @angular/pwa service worker filename

CONTRIBUTING.md
This adds a section to the contributing doc describing how page and menu templates work.
=> docs(contributing): add page and menu template sections

src/components/menu/templates/main.tsx, src/pages/faq/cors.md, src/pages/faq/security.md, src/pages/faq/tips.md
This page adds notes on sanitizing user input as well as resources to how other frameworks do sanitization.
Part of https://github.com/ionic-team/ionic/pull/18083 and should not be merged until that other PR is merged.
=> docs(security): add security docs page

scripts/build-data/index.ts, scripts/build-data/release-notes.ts, src/components.d.ts, src/components/menu/templates/main.tsx, src/components/page/templates/index.ts, src/components/page/templates/release-notes.tsx, src/pages/intro/release-notes.md, src/pages/intro/versioning.md, src/styles/global.css, src/styles/pages/release-notes.css
Adds the following page at the URL: `/docs/intro/release-notes`
=> feat(release-notes): add a page for displaying the last 10 releases

src/pages/lifecycle/angular.md
Fix 'CanActive' to 'CanActivate'
=> docs(lifecycle): fix route guard method misspelling

scripts/build-data/release-notes.ts, src/components/page/templates/release-notes.tsx, src/styles/base.css, src/styles/pages/release-notes.css
This PR updates the release notes page to pull in all recent releases, removes the alpha/beta/rc releases from the data, and updates the design to reflect Ben's changes.
=> fix(release-notes): update release note design

src/pages/intro/concepts.md
Solves #734 
Doesn't solve the issue that on this page that is loaded, the following "next" link doesn't go back to the intro that you left from. But at least the 404 is fixed.
=> Fix broken "next" link for intro/concepts

scripts/build-pages/page-types/static.ts
This allows authors to use `index.md` or `readme.md` files within a pages directory as the content for the root of the directory.
=> allow readme/index.md for pages dir index

src/pages/faq/tips.md
- fix incomplete keyboard shortcut advice
- fix typos
- improve wording
- fixed markup: markdown has line breaks, but missing empty line brakes which ensures they are actually rendered
=> tips.md - proofreading overhaul - fixes #772

src/pages/publishing/play-store.md
Removed doubled "the" in the "Signing an APK" paragraph.
=> Typo correction.

src/demos/api/list/index.html
img tag is a void element. The closing tag causes template parsing errors.
=> Remove closing img tag

src/pages/theming/color-generator.md
This makes no sense in the context of a non-angular or non-scss app. I don't think it should be here at all. If anything we can have a separate section that goes into more detail of where you can put this code or what `:root` means, but it doesn't *have* to go into the variables file either.
=> revert: color generator description change

src/pages/developer-resources/books.md
My new StencilJS book was recently added to the books list (including a preview version I created which was requested by Andrew) - I've just updated the entry to include a link and short description for the book.
=> docs(books): change to include link and description

src/pages/appflow/deploy/tutorials.md
I noticed a spelling mistake of **cordoava** on https://ionicframework.com/docs/appflow/deploy/tutorials/#upgrading-to-the-new-deploy-plugin so have decided to correct it.
=> Amended spelling mistake of 'cordoava' to 'cordova'

src/pages/appflow/deploy/cli.md, src/pages/appflow/package/cli.md
- Improved the readability of the Deploy and Package CLI documentation
- Improved consistency of language between the two docs
- Fixed some typos
=> fix(appflow): Improve Deploy and Package CLI document readability

src/pages/appflow/devapp.md
Added a note when explaining the use of the `ionic serve --devapp` command because when using the default project the following error is triggered: Could not find cordova integration in the default project. and we need to run `ionic cordova prepare` in order to be able to use the devapp
=> docs(devapp): add ionic cordova prepare command

src/pages/utilities/platform.md
I'm not sure if its official but I have inferred that with Ionic4 names are expanded like `ctrl` to `controller`. This shortening of `platform` to `plt` doesn't seem in line with this.
=> docs(platform): expand variable name

scripts/build-pages/page-types/native.ts, scripts/data/native.json, src/components/page/templates/native.tsx
When a plugin has the `"capacitorIncompatible": true`, adds a new Capacitor section where it says "Not compatible"
Closes #972
=> feat(native): add note on Capacitor incompatible plugins

src/pages/enterprise/identity-vault.md, src/pages/enterprise/identity-vault/3.0.X/identity-vault.md, src/pages/enterprise/identity-vault/3.1.X/identity-vault.md, src/pages/enterprise/identity-vault/3.2.X/identity-vault.md, src/pages/enterprise/identity-vault/3.3.X/identity-vault.md
The prior link was referencing a branch from when `master` was the non-IV branch.
=> fix(enterprise): use the correct IV link for the HTTP interceptor

src/pages/layout/structure.md
The example for Split Pane Layout uses a deprecated tag that no longer exists in Ionic 4. By replacing `<ion-page class="ion-page" main>` with `<div class="ion-page" main>`, the example works as expected.
=> Removes reference to deprecated component

src/pages/enterprise/geolocation.md, src/pages/es/enterprise/geolocation.md, src/pages/pt/enterprise/geolocation.md, src/pages/zh/enterprise/geolocation.md
This PR fixes a typo in markdown page for Geolocation.
Page that's been affected is:
https://ionicframework.com/docs/enterprise/geolocation
Path to the source file: src/pages/enterprise/geolocation.md
I have updated the other languages' files related to the abovementioned file
=> (docs) Fix configuration.xml to config.xml of Geolocation section

src/pages/theming/css-variables.md
updated to reflect what the name of the section is on the page - easily inferred but I've opened it because i spotted it and its easier to just offer up the pr to see if you are bothered about this level of specificity.
=> docs(css-variables): section name different

src/pages/appflow/deploy/api.md
GetCurrentVersion should be safe checked before accessing the versionId field.
=> getCurrentVersion can be undefined

src/pages/utilities/platform.md
Added a properties section before methods, and added resume as the first property. We needed resume in our app, so we thought others could benefit from this doc update as well.
=> Add properties section with "resume".

src/components.d.ts, src/components/native-ent-install/native-ent-install.tsx, src/pages/enterprise/filesystem.md, src/pages/enterprise/identity-vault.md, src/pages/enterprise/keyboard.md, src/pages/enterprise/splashscreen.md, src/pages/enterprise/statusbar.md
Mark Capacitor incompatible plugins by pointing to the community version:
- Filesystem
- Statusbar
- Keyboard
- Splashscreen
Also, add IV details for Capacitor.
=> Ionic native: add IV cap details and mark incompatible cap plugins

src/assets/locales/en/messages.json, src/components/menu/templates/main.tsx, src/pages/angular/config.md, src/pages/angular/navigation.md, src/pages/angular/performance.md, src/pages/angular/platform.md
1. Moved Config and Platform (previously under "Utilities" subheader) to under the "Angular" subheader.
2. Clarified that Ionic Config in Angular is not reactive.
3. Provided an example for configuring apps on a per-component level in a reactive manner.
4. Updated wording to not mention Config service as it is deprecated.
5. Removed the animations example while I was in there. This functionality/example is covered in https://github.com/ionic-team/ionic-docs/pull/976.
=> chore(): clarify Angular Config, move Config and Platform to Angular subheader

src/demos/api/searchbar/index.html
=> Typo in placename

src/pages/enterprise/auth-connect/azure-ad-b2c.md
- Fixes links to `cs-demo-ac-iv` on the AuthConnect Azure AD page
=> fix(enterprise): Fixing Enterprise Demo App Links

src/pages/enterprise/auth-connect/auth0.md, src/pages/enterprise/auth-connect/aws-cognito.md, src/pages/enterprise/auth-connect/azure-ad-b2c.md
- Fixes the `plugin-id` parameter on the individual AuthConnect pages to match the overview page
=> fix(enterprise): Fixing plugin ID for AC child pages

src/pages/appflow/quickstart/environment.md
- Fixes missing colon in `angular.json` in Environments walkthrough
=> fix(appflow): Fix missing colon in environment setup

src/pages/angular/your-first-app/3-saving-photos.md
*Fix*
Fixing typo that causes compiliation failure on Saving Photo Tutorial.
Changing blog to blob fixes this.
*Issue*
On this page https://ionicframework.com/docs/angular/your-first-app/3-saving-photos in the convertBlobToBase64 function the variable definition is shown like this `blog: Blob` which makes the compiler fail as it should be `blob: Blob.`
It will result in the following error in terminal when compiling:
`[ng] ERROR in src/app/services/photo.service.ts(87,26): error TS2552: Cannot find name 'blob'. Did you mean 'Blob'?
`
Created this issue for visibility https://github.com/ionic-team/ionic-docs/issues/1179
=> Fix typo in variable

src/pages/appflow/package/native-configs.md, src/pages/appflow/quickstart/native-config.md
- Added notes to the QuickStart and Native Config Package documentation about needing matching Bundle ID credentials for iOS builds
=> docs(appflow): Adding note about iOS creds for native configs

.github/ISSUE_TEMPLATE/bug_report.md
I obviously have too much time on my hands but there were a few formatting discrepancies I noticed while submitting the last bug.
=> docs(bug_report): consistent formatting and casing

src/demos/api/segment/index.html
Sets the call segment's value to call to avoid overlapping values.
Overlapping values highlight multiple segments.
=> docs(ion-segment): set unique values for segments

src/pages/react/your-first-app/3-saving-photos.md
First App React guide was missing a required return type of Promise<Photo>. Without it, TypeScript complains.
=> chore(yfa-react): Add missing return type

src/pages/appflow/package/credentials.md
As discussed in Ionic forum (https://forum.ionicframework.com/t/cant-submit-android-keystore/184737/6) the key needs to be in the JKS format which is not the default at least on JDK11 version of the keytool. If the keystore is not in JKS format you'll get an error message whilst uploading it to Ionic Appflow and the error message doesn't do anything to point you to the right direction.
=> Make sure that the keytool command shown generates JKS over PKCS12

src/pages/react/pwa.md
In the Line 
"Once this package has been added run `ionic build --prod` and the `www` directory will be ready to deploy as a PWA."
In react, the --prod on the ionic build command doesn't seem needed and the directory that is generated to be deployed is "build" instead of "www"
=> Updates a command and a folder in the React PWA document

src/pages/appflow/destinations/cli.md
does not look too bad, but as a note, a third note on the same page might not work.
=> add a note about min ver for push to app store app flow cli

src/components/page/page.css, src/components/page/templates/api.tsx, src/pages/reference/glossary.md
Adds encapsulation type to the API components & glossary entries for scoped & shadow that it links to
closes https://github.com/ionic-team/ionic-docs/issues/591
✅ Design is Ben approved
=> feat(api): add encapsulation type to the api components

src/pages/utilities/animations.md
Add animationCtrl to the constructor of the ModalExample in Angular/Typescript otherwise, the code would not compile since animationCtrl  is used later.
=> Add animationCtrl to the constructor in Angular

src/pages/appflow/cookbook/phonegap-build-migration.md
It was missing a couple of steps such as adding required package.json and ionic.config.json files for builds to work correctly in Appflow.
=> PhoneGap Build migration guide: add more details for non ionic apps

src/pages/angular/your-first-app/2-taking-photos.md
Templates should have no knowledge of the underlying implementation details and should never reference a service directly.
=> update: remove service references from template

src/components/color-gen/css-text/color-gen-css-text.tsx
This fixes a bug that currently does not to allow to import values as CSS.
1. go to the color generator page (https://ionicframework.com/docs/theming/color-generator)
2. scroll down to the `CSS Variables` section
3. edit the CSS, e.g. by pasting previously generated colors
The colors in the inputs should be updated accordingly as well as the colors in the demo app.
Nothing.
Obviously the code expected the CSS text input to be a `textarea` but actually it is a `div` with `[contenteditable=true]` which is why `ev.target.value` will always evaluate to `undefined` and so `value.length` will throw an exception:
https://github.com/ionic-team/ionic-docs/blob/bdf3a610a72783567e5c8868101dbd1bcf214176/src/components/color-gen/css-text/color-gen-css-text.tsx#L19-L21
=> fix(color-generator): update colors from CSS

src/assets/locales/en/messages.json, src/components/menu/templates/main.tsx, src/pages/theming/basics.md, src/pages/theming/colors.md, src/pages/theming/css-shadow-parts.md, src/pages/theming/css-variables.md
Implements a guide for CSS Shadow Parts. Adapted from https://ionicframework.com/blog/customize-your-ionic-framework-app-with-css-shadow-parts/
Closes #1343
=> docs(guide): add CSS Shadow Parts guide

src/pages/developing/keyboard.md
In iOS device `ev.detail` is `undefined` from KeyboardEvent.
Device: iPhoneX
=> fix: keyboard.md

src/components/native-ent-install/native-ent-install.tsx
After visiting plugins that have capacitorSlug property (splashscreen, statusbar, filesystem or keyboard), the capacitorSlug becomes null instead of undefined and the link to a null capacitor alternative plugins appears.
This PR checks that capacitorSlug is also not null before printing the alternative Capacitor plugin.
=> fix(enterprise-plugins): wrong Capacitor install text after visiting some plugins

src/pages/angular/navigation.md
Add StackBlitz live example to Angular Navigation/Routing page to provide user with a playground to see routing in action.
The StackBlitz has some comments around lifecycle hooks also to help users understand when they are called.
Link to StackBlitz
https://stackblitz.com/edit/ionic-angular-routing
=> docs(navigation): add live example of angular routing

src/pages/react/navigation.md
Add StackBlitz live example to React Navigation/Routing page to provide user with a playground to see routing in action.
Link to StackBlitz
https://stackblitz.com/edit/ionic-react-routing
=> docs(navigation): add live example for react routing

src/pages/layout/structure.md
Add StackBlitz live example to Layout Strcuture page to provide user with a playground to see the different structures in action in Angular
Link to StackBlitz-s
https://stackblitz.com/edit/ionic-ng-header-footer
https://stackblitz.com/edit/ionic-ng-tabs
https://stackblitz.com/edit/ionic-ng-menu-layout
https://stackblitz.com/edit/ionic-ng-split-pane
=> docs(layout): add angular live examples

src/pages/layout/grid.md
Add StackBlitz live example to Layout Grid page to provide user with a playground to see the different grid options in action in Angular
Link to StackBlitz-s
https://stackblitz.com/edit/ionic-ng-basic-grid
https://stackblitz.com/edit/ionic-ng-fixed-width-grid
https://stackblitz.com/edit/ionic-ng-set-width-col
https://stackblitz.com/edit/ionic-ng-var-width-col
https://stackblitz.com/edit/ionic-ng-stacked-horizontal-grid
https://stackblitz.com/edit/ionic-ng-offset-grid-cols
https://stackblitz.com/edit/ionic-ng-grid-vertical-align
https://stackblitz.com/edit/ionic-ng-grid-horizontal-align
=> docs(grid): add angular live examples

src/pages/layout/structure.md
Add StackBlitz live example to Layout Structure page to provide user with a playground to see the different structures in action in React
Link to StackBlitz-s
https://stackblitz.com/edit/ionic-react-head-foot
https://stackblitz.com/edit/ionic-react-tab-layout
https://stackblitz.com/edit/ionic-react-menu
https://stackblitz.com/edit/ionic-react-split-pane
=> docs(layout): add react live examples

src/pages/layout/grid.md
Add StackBlitz live example to Layout Grid page to provide user with a playground to see the different grid options in action in React
Link to StackBlitz-s
https://stackblitz.com/edit/ionic-react-basic-grid
https://stackblitz.com/edit/ionic-react-fixed-width-grid
https://stackblitz.com/edit/ionic-react-set-width-col
https://stackblitz.com/edit/ionic-react-var-width-col
https://stackblitz.com/edit/ionic-react-stacked-horizontal-grid
https://stackblitz.com/edit/ionic-react-offset-grid-cols
https://stackblitz.com/edit/ionic-react-grid-push-pull
https://stackblitz.com/edit/ionic-react-grid-vertical-align
https://stackblitz.com/edit/ionic-react-grid-horizontal-align
=> docs(grid): add react live examples

src/pages/appflow/build-stacks.md
I found myself constantly scrolling down and up on this page, comparing different versions.. this change would simply make the page *easier* to read.
however, the validity of this change very much depends on the source for this file, is it generated by a script or updated manually each time there's a change?
=> Condense "Build Stacks" version table

src/pages/vue/quickstart.md
`export default defineComponent({` was updated in other ares, this area still showed `export default {`
=> Update vue quickstart to include defineComponent

src/pages/angular/pwa.md
It's the first time I use firebase-tools and `firebase init` command failed because I wasn't logged in. So I added a note about `firebase login` command.
=> add login note on angular pwa guide

package-lock.json, package.json, src/pages/utilities/animations.md
v5.6.6 introduced a fix to what Ionic Vue recommends for listening to overlay component events: https://github.com/ionic-team/ionic-framework/releases/tag/v5.6.6
Need to update the docs so guidance is shown on there as well.
=> chore(): bump framework dependency to v5.6.6

src/pages/angular/your-first-app/6-deploying-mobile.md, src/pages/react/your-first-app/2-taking-photos.md, src/pages/react/your-first-app/4-loading-photos.md, src/pages/react/your-first-app/6-deploying-mobile.md, src/pages/vue/your-first-app/6-deploying-mobile.md
- Step 2 Taking Photos: fixed typo where `useCamera` should be `usePhotoGallery`
- Step 4 Loading Photos: fixed typo where `setPhotos(photos)` should be `setPhotos(photosInStorage)`
- Step 6 Deploying Mobile: modified Info.plist instructions (must be manually added and includes 2 addt. permissions)
Regarding Step 6, this might need to be updated for Angular and Vue as well. I have not looked through those guides, but while walking through this guide during a training session it was discovered that the `Info.plist` entries are not added when adding/syncing the Cap project.
=> fix(react-first-app): typos update Info.plist

src/pages/react/navigation.md
All pages that can be navigated to need `IonPage`. This example works fine in non-Tabs examples but breaks when adding a nested router outlet inside of a Tab due to the views lack of an `IonPage`.
See: https://github.com/ionic-team/ionic-framework/issues/23418
=> docs(react): add IonPage to nested outlet example

scripts/build-pages/markdown-renderer/code.ts, src/assets/locales/en/messages.json, src/components/code/prismjs-theme.css, src/components/menu/templates/main.tsx, src/pages/angular/virtual-scroll.md, src/pages/react/virtual-scroll.md, src/pages/vue/virtual-scroll.md
Related: https://github.com/ionic-team/ionic-framework/pull/23444
Adds virtual scroll recommendations for Angular, React, and Vue. Also provides steps for migrating `ion-virtual-scroll` to CDK Scroller.
=> docs(): add virtual scroll documentation

scripts/api.js
There are a handful of broken links to migration guides that I would like to have fixed before beta 1
=> docs(): bump api to dev build of v6 with some docs fixes

src/pages/angular/slides.md, src/pages/react/slides.md, src/pages/vue/slides.md
The current Slides migration guide only works with Swiper 6. Adding a note on this until we can figure out the Swiper 6 --> Swiper 7 changes that impact Ionic users
=> chore(): add swiper 6 note

docs/angular/slides.md, docs/react/slides.md, docs/vue/slides.md
The current Slides migration guide only works with Swiper 6. Adding a note on this until we can figure out the Swiper 6 --> Swiper 7 changes that impact Ionic users
=> chore(): swiper 6 note

docs/react/quickstart.md
Resolves https://github.com/ionic-team/ionic-docs/issues/1384
Loosely adapted from similar content in the Vue quickstart guide: https://ionicframework.com/docs/vue/quickstart#adding-icons
Global imports for icons don't seem to be a thing in React, so I left that piece out.
=> docs(react): add icons usage to quickstart

package-lock.json, package.json
Would like to get the infinite scroll examples for React corrected sooner rather than later, so adding a temp dev build for now.
=> chore(): bump Ionic dev build for infinite scroll examples

src/pages/angular/slides.md, src/pages/react/slides.md, src/pages/vue/slides.md
Same thing as https://github.com/ionic-team/ionic-docs/pull/2094 but for the v5 docs. Do not merge until Ionic 5.9 ships.
=> docs(slides): add Swiper 7 migration guide

src/pages/angular/slides.md, src/pages/react/slides.md, src/pages/vue/slides.md
The `:::note` syntax is a feature specific to Docusaurus and will not work on docs site built with Stencil.
=> fix(): remove :::note syntax for legacy docs

versioned_docs/version-v5/api/popover.md
Hello, this is my first PR and I saw some 'the' duplicates in the docs that would be fixed. Thanks in advance.
=> docs(): deletes double 'the' typing

docs/layout/rtl.md
This page just says "TODO" and is being indexed by our search component. Until we get a better RTL page up I would like to remove the placeholder content altogether so it's less confusing.
=> docs(rtl): remove unused page

docs/angular/your-first-app/7-live-reload.md
There's a mistake in the **deletePicture** definition. 
We have to change the type of the **photo** argument from `photo: Photo`  to `photo: UserPhoto`
=> Fixing a mistake in the deletePicture definition

docs/utilities/animations.md
Modal uses the Shadow DOM in Ionic 6, so the animation example was broken.
See https://github.com/ionic-team/ionic-framework/issues/24698
=> docs(animation): update modal example for ionic 6

docs/theming/css-shadow-parts.md
Double quotes in the CSS Shadow Parts docs were confusing; can only assume it's a typo.
=> docs(shadow-parts): remove double quotes

docs/playground/button.mdx, src/components/global/Playground/index.tsx, src/components/global/Playground/playground.css
Introduces the new `<Playground />` component for documenting Ionic Framework components in the docs site.
Displays the initial design with partial dark-mode support.
|Light Theme|Dark Theme|
|---|---|
|![Screen Shot 2022-02-08 at 5 30 42 PM](https://user-images.githubusercontent.com/13732623/153086606-243af567-5121-4d39-8c58-c6a246348f7f.png)|![Screen Shot 2022-02-08 at 5 31 06 PM](https://user-images.githubusercontent.com/13732623/153086653-e42d9361-c3f4-4753-8548-19586f397cef.png)|
Split from #2185
=> feat(playground): set-up playground component

scripts/api.js
I wanted to bump this to the `6` tag on npm, but there was a problem with the deploy scripts for @ionic/docs. This dev build has a fix for that. Once 6.0.10 ships we can safely change this to use the `6` npm tag.
See https://github.com/ionic-team/ionic-framework/pull/24850
=> fix(): bump to latest ionic 6

src/components/global/Playground/index.tsx
Introduces the button to copy the contents of the code block to the users clipboard.
You can verify by clicking the button and seeing that "Fake code block" text is copied to the users clipboard. 
Note: Tooltips for all icon buttons will be a later PR.
=> feat(playground): copy source code button

docs/vue/navigation.md
---
name: Invalid variable name
about: Invalid variable name
title: The variable name for vue when using ionRouter is invalid
labels: doc, vue
assignees: ''
---
**URL**
[The URL at which the content is missing or inaccurate](https://ionicframework.com/docs/vue/navigation#navigating-using-useionrouter)
**What is missing or inaccurate about the content on this page?**
We import a `ionrouter` but then we use an hypothetical variable named `router`:
Initial :
```js
const ionRouter = useIonRouter();
router.navigate('...');
```
Fixed:
```js
const ionRouter = useIonRouter();
ionRouter.navigate('...');
```
=> docs(vue): fix typo in useIonRouter example

docs/index.md
Regression from (markdown autogenerated) heading change since #1840 in e2503f5
Hat tip @pfurbacher for spotting this in #2176 🎩
=> fix(docs): broken Appflow anchor link

src/components/global/Playground/playground.css
This adds a new CSS variable that changes the background color of the expanded code block, and adds values for both light and dark mode in accordance with the designs.
(FW-717 is a ticket to add dark mode styling, but most of it was already present in the `component-playground` branch. As far as I can tell, this was the only piece missing.)
=> fix(playground): match code background to designs

scripts/api.js
Updates the API script to always point to the latest published release (semantic release) for the `core.json` asset. Unpkg is smart enough that when you do not specify a version, it will pull the latest.
=> fix(scripts): always load latest core.json

src/components/global/Playground/stackblitz.utils.ts, static/code/stackblitz/README.md, static/code/stackblitz/vue/App.vue, static/code/stackblitz/vue/index.html, static/code/stackblitz/vue/main.js, static/code/stackblitz/vue/package.json, static/code/stackblitz/vue/vite.config.js
Introduces the ability to generate Stackblitz examples for Vue (using Vite). 
This implementation required a little more customization than the others, since Stackblitz does not have a template starter that works with Vue & Vue Router. There is also an active issue open for their template starters with Vue 3 and `script setup`. This uses web containers for now, which is a beta feature from Stackblitz.
=> feat(playground): create stackblitz examples for vue/vite

package-lock.json, package.json, src/components/global/Playground/index.tsx, src/components/global/Playground/playground.types.ts, src/components/global/Playground/stackblitz.utils.ts, static/code/stackblitz/README.md, static/code/stackblitz/angular/angular.json, static/code/stackblitz/angular/app.component.ts, static/code/stackblitz/angular/app.module.ts, static/code/stackblitz/angular/main.ts, static/code/stackblitz/angular/styles.css, static/code/stackblitz/html/index.html, static/code/stackblitz/html/index.ts, static/code/stackblitz/react/app.tsx, static/code/stackblitz/react/index.js, static/code/stackblitz/vue/App.vue, static/code/stackblitz/vue/index.html, static/code/stackblitz/vue/main.js, static/code/stackblitz/vue/package.json, static/code/stackblitz/vue/vite.config.js, tsconfig.json
Introduces the ability to open individual examples in Stackblitz for the respective framework target. Does not currently support Vue (FW-715). 
All boilerplate files are located in `/static/code/stackblitz`. These files are required to create a valid Stackblitz example. 
Note: Opening the Stackblitz example will currently not populate a code snippet, sine that feature has not been implemented yet.
=> feat(playground): ability to open examples in Stackblitz

src/components/global/Playground/index.tsx, src/components/global/Playground/playground.css, src/components/global/Playground/playground.types.ts
- Adds the buttons for switching between languages.
- Populates the code block and Stackblitz editor with the code for your selected language.
- Cleans up some redundant code.
- Fixes the layout shifting when control buttons are selected, including a slight refactor of all control buttons to clean things up.
=> feat(playground): add language toggle buttons, populate selected code

package-lock.json, package.json, src/components/global/Playground/index.tsx, src/components/global/Playground/playground.css
Hovering over the source code, github, copy code, and stackblitz buttons now show tooltips.
=> feat(playground): buttons now show tooltips

docs/reference/support.md
This PR does the following:
1. Adds a new row to the support table for v6.
2. Indicates that v6 is the active version.
3. Moves v5 from "Active" to "Maintenance".
4. Defines "Maintenance Ends" and "Extended Support Ends" dates for v5.
5. Defines the "Extended Support Ends" date for v4.
=> docs(support): update v5 and v6 support policy

docs/angular/slides.md
Fixes a typo in the swiper example code snippet for Angular.
=> docs(slides): set swiper instance in angular

docs/intro/upgrading-to-ionic-6.md
Discovered in this framework issue: https://github.com/ionic-team/ionic-framework/issues/24497, React developers migrating from Ionic v5 to v6 will need to update controller imports to reference `@ionic/core/components`.
Without this change, they will create multiple instances of the menu controller and be unable to control their `ion-menu` through the menu controller.
=> docs(react): v6 migrating controller import path

docs/reference/browser-support.md
To support iOS 13, Angular 13 requires targeting es5 rather than es2015.
=> docs(angular): Support note for Angular 13 with iOS 13

docs/angular/virtual-scroll.md, docs/react/virtual-scroll.md, docs/vue/virtual-scroll.md
Updates the sections for note regarding Ionic components to include the usage instructions for the custom scroll target.
=> feat(virtual-scroll): usage with custom scroll target

docs/vue/quickstart.md
On the vue quickstart guide, there is an anchor link "#optimizing-your-app". It looks like this section title has been changed to "Optimizing your Build", and so the anchor link is no longer correct. This commit fixes the anchor link
=> fix: fix anchor link on Vue quickstart guide

docs/api/picker.md
Adds usage example for Angular to the `ion-picker`. 
Quick link for effected section: https://ionic-docs-git-docs-picker-usage-angular-ionic1.vercel.app/docs/api/picker#usage
=> docs(picker): angular usage example

docs/vue/quickstart.md
The heading "Dynamic Imports" is not an accurate heading for this section. This section describes the recommended approach of importing ionicons on a per-component basis, so I updated the heading to reflect that.
=> docs(vue): update ionicons usage heading

docs/api/modal.md, docs/api/popover.md
The isOpen one way data binding behavior is not clear in the docs. It is also not clear why the one way data binding exists.
As a result, I updated the modal and popover docs to highlight the intended behavior of isOpen and why it behaves that way.
See https://github.com/ionic-team/ionic-framework/issues/25166 for more information.
=> docs(modal, popover): add docs for explaining isOpen behavior

src/components/global/Playground/device-preview.js, src/components/global/Playground/device-preview.ts, src/components/global/Playground/index.tsx, src/components/global/Playground/playground.css, src/declarations.d.ts, static/usage/button/basic/index.md, static/usage/common.css
Introduces new `devicePreview` option that can be enabled per-playground example to render a "device chrome" around the example iframe for iOS vs. MD. Copies the implementation styles close to the existing Ionic Docs, but uses an SVG instead of a PNG asset.
The inner `device-preview` is a web component with shadow-dom, to prevent style conflicts with the device wrapper.
Updated the button example (in our temporary playground doc), to show the device emulation. 
Live preview (Chrome will likely say it is a dangerous site): https://ionic-docs-git-feat-device-preview-ionic1.vercel.app/docs/playground/button
iOS:
MD:
=> feat(component-playground): use devicePreview to render phone wrappers

src/components/global/Playground/index.tsx
- Updates the Stackblitz Icon from an arrow to the Stackblitz logo (based on latest Figma designs)
- Updates the button order to match Figma
=> fix(playground): updated stackblitz icon

src/components/global/Playground/index.tsx
Introduces a button that allows users to reload the rendered iframe previews back to their original state. Useful for examples where you may present a modal, but not show how to dismiss.
Builds on the updated stackblitz icon PR, to maintain correct button ordering.
=> feat(playground): ability to reset demos

src/components/global/Playground/stackblitz.utils.ts
Stackblitz doesn't appear to install the whole `@ionic/core` package to allow the extended JSX types to populate in the examples. This change manually installs `@ionic/core` at the same version as the `@ionic/angular` package, which resolves this problem.
An example where this occurred was doing this:
```html
<ion-modal #modal>
<ng-template>
<ion-button (click)="modal.dismiss()">Dismiss</ion-buton>
</ng-template>
</ion-modal>
```
`dismiss` would not exist on `IonModal` type.
=> fix(stackblitz): ionic core types in angular examples

static/code/stackblitz/react/app.tsx
Adds the stylesheets to the react Stackblitz examples for many of our commonly used helper global classes (i.e.: `ion-text-center`).
=> fix(stackblitz/react): global classes in example

src/components/global/Playground/stackblitz.utils.ts
`openReactEditor` does not find the correct component when given a React example with multiple files. By hardcoding the `componentTagName` variable to `Example` we can easily support both single file and multi file React examples without needing to parse the given code.
=> fix(playground): improve react component imports for stackblitz

docs/angular/slides.md
This PR fixes a small typo in the link pointing to the article on ViewEncapsulation in the Angular documentation.
=> docs(angular): fix typo in Angular Slides page

docs/react/overlays.md
Tiny fix for a link that leads to a different component than expected (Modal instead of Alert).
=> Fix link to alert component

docs/api/picker.md, src/components/global/Playground/stackblitz.utils.ts, static/code/stackblitz/html/index.ts, static/usage/picker/multiple-column/angular/app_component_html.md, static/usage/picker/multiple-column/angular/app_component_ts.md, static/usage/picker/multiple-column/demo.html, static/usage/picker/multiple-column/index.md, static/usage/picker/multiple-column/javascript.md, static/usage/picker/multiple-column/react.md, static/usage/picker/multiple-column/vue.md, static/usage/picker/single-column/angular/app_component_html.md, static/usage/picker/single-column/angular/app_component_ts.md, static/usage/picker/single-column/demo.html, static/usage/picker/single-column/index.md, static/usage/picker/single-column/javascript.md, static/usage/picker/single-column/react.md, static/usage/picker/single-column/vue.md
Introduces component playground examples for `ion-picker` for the single and multi-column examples. 
Verified each usage target example in Stackblitz, with both single and multiple columns.
Quick link to `ion-picker` page: https://ionic-docs-git-fw-1278-ionic1.vercel.app/docs/api/picker
=> docs(picker): component playground examples

static/code/stackblitz/html/index.ts
The Vanilla JS StackBlitz examples did not load the core CSS stylesheets. This resulted in certain layouts being wrong and fonts defaulting to serif fonts.
To test: https://ionic-docs-git-fw-1382-ionic1.vercel.app/docs/api/datetime#basic-usage
Make sure "JavaScript" is selected and open the StackBlitz. The font should be sans-serif.
=> fix(playground): vanilla JS stackblitz loads core styles

docs/angular/navigation.md, docs/react/navigation.md, docs/vue/navigation.md
This PR ports the Shared URLs vs Nested URLs docs from Vue to the Angular and React docs. The text is largely the same, but with framework specific code examples.
=> docs(angular, react): add shared URLs vs nested URLs docs

src/components/global/Playground/index.tsx, static/usage/button/basic/index.md
This PR adds the `expandCodeByDefault` prop to the playground. The prop is also set on the button example at URL `/docs/playground/button` for testing purposes.
=> feat(playground): add ability to expand code block by default

docs/api/modal.md, static/usage/modal/inline/basic/angular/app_component_html.md, static/usage/modal/inline/basic/angular/app_component_ts.md, static/usage/modal/inline/basic/angular/app_module_ts.md, static/usage/modal/inline/basic/demo.html, static/usage/modal/inline/basic/index.md, static/usage/modal/inline/basic/javascript.md, static/usage/modal/inline/basic/react.md, static/usage/modal/inline/basic/vue.md, static/usage/modal/inline/is-open/angular/app_component_html.md, static/usage/modal/inline/is-open/angular/app_component_ts.md, static/usage/modal/inline/is-open/demo.html, static/usage/modal/inline/is-open/index.md, static/usage/modal/inline/is-open/javascript.md, static/usage/modal/inline/is-open/react.md, static/usage/modal/inline/is-open/vue.md
Re-approach to the inline modal component playground examples. 
Shows two examples:
1. Kitchen sink (presenting, dismissing with data & role)
2. `isOpen` (isolated example of using `isOpen` property)
This will still have the extra padding in the device header, compared to the legacy example. We will likely need to capture that as a separate work item.
This PR is in favor of: #2317 and #2313.
=> docs(modal): inline playground

docs/api/modal.md, static/usage/modal/card/basic/angular/app_component_css.md, static/usage/modal/card/basic/angular/app_component_html.md, static/usage/modal/card/basic/angular/app_component_ts.md, static/usage/modal/card/basic/demo.html, static/usage/modal/card/basic/index.md, static/usage/modal/card/basic/javascript.md, static/usage/modal/card/basic/react.md, static/usage/modal/card/basic/vue.md
Introduces the card style playground for `ion-modal`.
Decided to remove the full screen section (already cover heavily in the inline and controller examples) and the sizes section (changing modal height can be covered in the styling section).
=> docs(modal): card playground

docs/api/modal.md, src/components/global/Playground/stackblitz.utils.ts, static/code/stackblitz/angular/app.component.ts, static/usage/modal/styling/animations/angular/app_component_html.md, static/usage/modal/styling/animations/angular/app_component_ts.md, static/usage/modal/styling/animations/demo.html, static/usage/modal/styling/animations/index.md, static/usage/modal/styling/animations/javascript/index_html.md, static/usage/modal/styling/animations/javascript/index_ts.md, static/usage/modal/styling/animations/react.md, static/usage/modal/styling/animations/vue.md, static/usage/modal/styling/theming/angular/app_component_css.md, static/usage/modal/styling/theming/angular/app_component_html.md, static/usage/modal/styling/theming/demo.html, static/usage/modal/styling/theming/index.md, static/usage/modal/styling/theming/javascript.md, static/usage/modal/styling/theming/react/main_css.md, static/usage/modal/styling/theming/react/main_js.md, static/usage/modal/styling/theming/vue.md
Introduces component playground examples for styling and custom animations for `ion-modal`. 
Updated the Angular Stackblitz base example, so it always includes an `app.component.css`. This allows us to have examples that customize `app.component.html` and `app.component.css`, but don't need to include an `app.component.ts` in the code snippet section, as we aren't making any changes to it.
=> docs(modal): modal styling playground

docs/api/modal.md, static/usage/modal/sheet/background-content/angular/app_component_css.md, static/usage/modal/sheet/background-content/angular/app_component_html.md, static/usage/modal/sheet/background-content/angular/app_component_ts.md, static/usage/modal/sheet/background-content/demo.html, static/usage/modal/sheet/background-content/index.md, static/usage/modal/sheet/background-content/javascript.md, static/usage/modal/sheet/background-content/react.md, static/usage/modal/sheet/background-content/vue.md, static/usage/modal/sheet/basic/angular.md, static/usage/modal/sheet/basic/demo.html, static/usage/modal/sheet/basic/index.md, static/usage/modal/sheet/basic/javascript.md, static/usage/modal/sheet/basic/react.md, static/usage/modal/sheet/basic/vue.md
Introduces the sheet modal examples to the component playground.
Combined the basic and move to breakpoint sections, as the examples felt redundant. 
In the basic example, if you click the backdrop to dismiss the background you will notice that the searchbar will no longer move to the correct breakpoint. This has been resolved and you can use this dev build: `6.1.5-dev.11651770915.1670c308` if that is a blocker for you.
=> docs(modal): modal sheet playground

docs/api/popover.md, static/usage/popover/customization/positioning/angular/angular_css.md, static/usage/popover/customization/positioning/angular/angular_html.md, static/usage/popover/customization/positioning/angular/angular_ts.md, static/usage/popover/customization/positioning/demo.html, static/usage/popover/customization/positioning/index.md, static/usage/popover/customization/positioning/javascript.md, static/usage/popover/customization/positioning/react/react_css.md, static/usage/popover/customization/positioning/react/react_ts.md, static/usage/popover/customization/positioning/vue.md, static/usage/popover/customization/sizing/angular.md, static/usage/popover/customization/sizing/demo.html, static/usage/popover/customization/sizing/index.md, static/usage/popover/customization/sizing/javascript.md, static/usage/popover/customization/sizing/react.md, static/usage/popover/customization/sizing/vue.md, static/usage/popover/customization/styling/angular/angular_css.md, static/usage/popover/customization/styling/angular/angular_html.md, static/usage/popover/customization/styling/demo.html, static/usage/popover/customization/styling/index.md, static/usage/popover/customization/styling/javascript.md, static/usage/popover/customization/styling/react/react_css.md, static/usage/popover/customization/styling/react/react_ts.md, static/usage/popover/customization/styling/vue.md
Adds the following playgrounds:
- Positioning (Size and Alignment Demo)
- Sizing
- Styling
Also removes a dead link from the existing docs.
=> docs(popover): add customization playgrounds

docs/api/popover.md, static/usage/popover/customization/positioning/angular/angular_css.md, static/usage/popover/customization/positioning/angular/angular_html.md, static/usage/popover/customization/positioning/angular/angular_ts.md, static/usage/popover/customization/positioning/demo.html, static/usage/popover/customization/positioning/index.md, static/usage/popover/customization/positioning/javascript.md, static/usage/popover/customization/positioning/react/react_css.md, static/usage/popover/customization/positioning/react/react_ts.md, static/usage/popover/customization/positioning/vue.md, static/usage/popover/customization/sizing/angular.md, static/usage/popover/customization/sizing/demo.html, static/usage/popover/customization/sizing/index.md, static/usage/popover/customization/sizing/javascript.md, static/usage/popover/customization/sizing/react.md, static/usage/popover/customization/sizing/vue.md, static/usage/popover/customization/styling/angular/angular_css.md, static/usage/popover/customization/styling/angular/angular_html.md, static/usage/popover/customization/styling/demo.html, static/usage/popover/customization/styling/index.md, static/usage/popover/customization/styling/javascript.md, static/usage/popover/customization/styling/react/react_css.md, static/usage/popover/customization/styling/react/react_ts.md, static/usage/popover/customization/styling/vue.md, static/usage/popover/nested/angular.md, static/usage/popover/nested/demo.html, static/usage/popover/nested/index.md, static/usage/popover/nested/javascript.md, static/usage/popover/nested/react.md, static/usage/popover/nested/vue.md
Adds the Nested Popovers playground. `dismissOnSelect` was folded in here rather than having its own separate playground, since separating the two felt redundant.
=> docs(popover): add nested playground

docs/api/modal.md
A dev pointed out that we never explicitly state that `ion-modal` must use `ion-content` in order for certain features to work. This PR corrects that omission.
See https://github.com/ionic-team/ionic-framework/issues/25362
=> docs(modal): explicitly state ion-content requirement

docs/api/range.md
Sets up the playground example sections for `ion-range`.
=> feat(range): component playground set-up

docs/api/range.md, static/usage/range/basic/angular.md, static/usage/range/basic/demo.html, static/usage/range/basic/index.md, static/usage/range/basic/javascript.md, static/usage/range/basic/react.md, static/usage/range/basic/vue.md
Introduces the basic usage playground example for `ion-range`. Opted for not configuring the `min` and `max` properties for the basic examples, since without event handling or showing the ticks, the user experience does not change. 
Added a call out that explains the default `min`/`max` values and that they can be configured.
=> feat(range): basic playground example

docs/reference/support.md
This PR updates the support table for Angular to include Angular 14 as the maximum angular version
=> docs(support): add angular 14 support

docs/reference/support.md
The team has adopted a new process internally for adding support for new major releases of 3rd party packages. While we still try to get support added as soon as possible, we also want to allow for additional flexibility if there are large breaking changes that require additional work in Ionic.
=> docs(): remove compatibility timeframe

docs/api/range.md, static/usage/range/pins/angular.md, static/usage/range/pins/angular/app_component_html.md, static/usage/range/pins/angular/app_component_ts.md, static/usage/range/pins/demo.html, static/usage/range/pins/index.md, static/usage/range/pins/javascript.md, static/usage/range/pins/react.md, static/usage/range/pins/vue.md
Introduces the component playground for displaying a pin with `ion-range`. 
Quick link: https://ionic-docs-git-range-playground-pins-ionic1.vercel.app/docs/api/range#pins
=> docs(range): pins playground

src/components/global/Playground/device-preview.js
Currently, when viewing the device preview frame in Chromium browsers, there are white pixels at the corners of the content. This can be most easily seen in the card modal playground:
This happens due to a browser rendering issue around combining `border-radius` with `overflow: hidden`. Tweaking the `border-radius` values does not fix the issue.
This PR fixes things by removing an extra `overflow: hidden`. It isn't needed anyway since the inner content also has `overflow: hidden` and a border radius of its own.
An alternative fix would be to add `background-color: black` to the `figure`, but this leads to the frame being solid black while the iframe loads, which doesn't look great.
=> fix(playground): avoid white pixels at corners of device preview

docs/developing/hardware-back-button.md, versioned_docs/version-v5/developing/hardware-back-button.md
In Capacitor 3+ the plugins are separate and App plugin is on it's own package instead of in @capacitor/core
closes https://github.com/ionic-team/ionic-docs/issues/2101
=> Update back button docs for Capacitor 3+

static/usage/datetime/theming/index.md
Ben noted that the MD playground for the datetime theming section is too short, causing the shadow to get cut off:
=> docs(datetime): make theming playground taller

src/components/global/Playground/playground.css, src/components/global/PlaygroundTabs/styles.module.css
Light Mode (note: there should be no changes):
| `main` | branch |
| ------ | ----- |
| ![light-before](https://user-images.githubusercontent.com/2721089/174850671-d37eb993-b8ff-466d-9165-8fdf6ee056b6.png) | ![light-after](https://user-images.githubusercontent.com/2721089/174850699-74fae04b-554e-47b4-8877-607bef4bb18d.png) |
Dark Mode:
| `main` | branch |
| ----- | ----- |
| ![dark-before](https://user-images.githubusercontent.com/2721089/174850765-2026a61c-ef64-4bf1-aab4-cceec3cc73c6.png) | ![Screen Shot 2022-06-21 at 12 31 07 PM](https://user-images.githubusercontent.com/2721089/174851056-9e02b58c-fc70-4594-bb25-fa36fac7a6d3.png) |
=> fix(playground): tabs now have dark theme

docs/index.md
url: https://ionicframework.com/docs/#license
=> docs(index): license typo 

docs/api/datetime.md
When removing the inline TOC, I forgot to remove the "Contents" header.
=> docs(datetime): remove stray contents header

docs/react/navigation.md
IonTabs already renders `.ion-page`, so adding another one causes the view to be hidden: https://github.com/ionic-team/ionic-framework/issues/25562
=> docs(react): remove extra IonPage from tabs sample

docs/api/nav.md, static/usage/nav/nav-link/angular/app_component_html.md, static/usage/nav/nav-link/angular/app_component_ts.md, static/usage/nav/nav-link/angular/app_module_ts.md, static/usage/nav/nav-link/angular/page_one_component_ts.md, static/usage/nav/nav-link/angular/page_three_component_ts.md, static/usage/nav/nav-link/angular/page_two_component_ts.md, static/usage/nav/nav-link/demo.html, static/usage/nav/nav-link/index.md, static/usage/nav/nav-link/javascript.md, static/usage/nav/nav-link/react/main_tsx.md, static/usage/nav/nav-link/react/page_one_tsx.md, static/usage/nav/nav-link/react/page_three_tsx.md, static/usage/nav/nav-link/react/page_two_tsx.md, static/usage/nav/nav-link/vue/example_vue.md, static/usage/nav/nav-link/vue/page_one_vue.md, static/usage/nav/nav-link/vue/page_three_vue.md, static/usage/nav/nav-link/vue/page_two_vue.md
Quick link: https://ionic-docs-git-docs-nav-link-playground-ionic1.vercel.app/docs/api/nav#using-navlink
To verify the React example, you will need to manually install the dev-build: `6.1.12-dev.11656705976.18fe5a46`
=> docs(nav): nav link component playground

docs/api/picker.md
Removes refresh key from PickerColumn interface
See https://github.com/ionic-team/ionic-framework/issues/25631 for context.
=> docs(picker): remove refresh key

src/components/global/Playground/icons/IconDots.css, src/components/global/Playground/icons/IconDots.tsx, src/components/global/Playground/icons/index.ts, src/components/global/Playground/index.tsx, src/components/global/Playground/playground.css
Component playgrounds are now lazily loaded as you scroll the page (as opposed to all up front on page load). As a result, there is a moment between when the iframes are initialized and the source page is rendered. This PR adds a simple loading screen to inform users that the content is being loaded. Without this loading screen, the playgrounds may be perceived as broken, especially when a playground is being loaded over a slow connection.
Discussed with Ben and we decided on showing 3 animated dots on the same line instead of loading text.
Demo: https://ionic-docs-git-fw-1430-ionic1.vercel.app/docs/api/datetime#basic-usage
=> docs(playground): add loading screen

src/components/global/Playground/index.tsx, src/components/global/Playground/playground.css, static/usage/accordion/basic/index.md, static/usage/accordion/listen-changes/index.md, static/usage/accordion/multiple/index.md
We've received feedback that the collapsing behavior is confusing; namely, all snippets should be expanded by default, and the JS framework tab should not appear selected if its code isn't expanded. To keep things simple, we decided to remove the expand/collapse feature entirely and wait for user feedback before iterating further.
=> fix(playground): remove code expand/collapse feature

docs/api/modal.md, static/usage/modal/sheet/background-content/angular/app_component_html.md, static/usage/modal/sheet/handle-behavior/angular.md, static/usage/modal/sheet/handle-behavior/demo.html, static/usage/modal/sheet/handle-behavior/index.md, static/usage/modal/sheet/handle-behavior/javascript.md, static/usage/modal/sheet/handle-behavior/react.md, static/usage/modal/sheet/handle-behavior/vue.md
Introduces a new section for the `handleBehavior` option available with Modal. 
Quick link: https://ionic-docs-git-docs-modal-handle-behavior-ionic1.vercel.app/docs/api/modal#handle-behavior
Misc:
- Fixed missing class for Angular background content example.
Note: The demo and Stackblitz examples are not using the dev-build. I can temporarily update the version they use, if that would be helpful for reviewing. 
Dev-build for testing: `6.1.14-dev.11658252995.1c2781cc`
=> docs(modal): handleBehavior playground example

docs/vue/navigation.md
Title & changes are clear! No description needed.
=> docs(vue/navigation): typo in brief note section

docs/api/datetime.md, static/usage/datetime/multiple/angular.md, static/usage/datetime/multiple/demo.html, static/usage/datetime/multiple/index.md, static/usage/datetime/multiple/javascript.md, static/usage/datetime/multiple/react.md, static/usage/datetime/multiple/vue.md
PR for feature: https://github.com/ionic-team/ionic-framework/pull/25514
Dev build: `6.1.14-dev.11657720710.1df41c89`
The demo example is hard-coded to use the above dev build, but you'll need to install it on the Stackblitz examples manually.
=> docs(datetime): add multiple selection playground

static/usage/datetime/multiple/demo.html, static/usage/datetime/presentation/wheel/demo.html, static/usage/modal/performance/mount/demo.html, static/usage/modal/sheet/handle-behavior/demo.html, static/usage/popover/performance/mount/demo.html
JSDelivr caches `latest` for about 7 days: https://github.com/jsdelivr/jsdelivr#caching. Until we can get access to purging the cache, we need to fix the CDN version.
=> docs(): fix 6.2 demos to use correct cdn version

static/usage/datetime/multiple/demo.html, static/usage/datetime/presentation/wheel/demo.html, static/usage/modal/performance/mount/demo.html, static/usage/modal/sheet/handle-behavior/demo.html, static/usage/popover/performance/mount/demo.html
This reverts commit c61e638cbd1e386670c1bd7224594b5b1a914535.
I now have the ability to purge the JSDelivr cache, so this fix is no longer needed.
=> docs(playground): revert 6.2.0 version fix

src/components/global/Playground/index.tsx
- Orders framework buttons alphabetically
- Changes default active usage target from "Javascript" to "Angular" (first available option)
- Fixes `class` to `className` usage
=> fix(playground): order framework buttons alphabetically

docs/reference/support.md
Updates the support table to list Ionic 5 as Extended Support Only, since maintenance ended in June.
=> docs(support): update v5 to extended support only

scripts/release-notes.js
Adds version names for Ionic 6.2 and Ionic 6.3
=> docs(release-notes): update version names

src/components/global/Playground/index.tsx
Currently, if the page is set to dark mode on initial load, the playground iframes will still display in light mode. They only update when the mode is toggled on and off after the fact.
While the `useEffect` callback _does_ run on initial page load, the iframe refs haven't yet loaded, so the first run of the callback does nothing. The fix is to make use of a [callback ref](https://reactjs.org/docs/refs-and-the-dom.html#callback-refs) instead, which allows additional side effects to run only after both refs are ready.
This PR also fixes the two async `useEffect` callbacks (both the one that handles the dark mode message, and the one below it that clears the iframe loading dots), as that pattern is not allowed. Further reading: https://devtrium.com/posts/async-functions-useeffect
=> fix(playground): ensure dark mode loads on iframes at start

docs/api/skeleton-text.md, static/usage/skeleton-text/basic/angular/angular-html.md, static/usage/skeleton-text/basic/demo.html, static/usage/skeleton-text/basic/javascript.md, static/usage/skeleton-text/basic/react.md, static/usage/skeleton-text/basic/vue.md, static/usage/skeleton-text/theming/angular/angular-css.md, static/usage/skeleton-text/theming/angular/angular-html.md, static/usage/skeleton-text/theming/demo.html, static/usage/skeleton-text/theming/index.md, static/usage/skeleton-text/theming/javascript.md, static/usage/skeleton-text/theming/react/react-css.md, static/usage/skeleton-text/theming/react/react-tsx.md, static/usage/skeleton-text/theming/vue.md
- Adds a theming example to customize the colors
- Removes "Animation" section
- Fixes some syntax issues I found re: best practices
Preview link: https://ionic-docs-git-1266-theming-ionic1.vercel.app/docs/api/skeleton-text
=> docs(skeleton-text): add theming example

docs/api/accordion.md, docs/api/alert.md, docs/api/breadcrumbs.md, docs/api/chip.md, docs/api/datetime-button.md, docs/api/datetime.md, docs/api/loading.md, docs/api/picker.md, docs/api/popover.md, docs/api/range.md, docs/api/select.md, docs/api/skeleton-text.md
Most components that we've added playgrounds to (and thus have had their TOCs moved to the sidebar) still had the import for the inline TOC component sitting around, now unused. This PR just removes the import from applicable components.
=> refactor(): remove unused TOC imports

docs/index.md
Ionic is primarily focused on mobile/tablet applications, so calling out desktop is a bit confusing. Note: We are not making any changes to Ionic Framework as a result of this, just updating the docs to make the intent of Ionic clear.
=> docs(): remove desktop wording

docs/reference/browser-support.md, docs/reference/support.md
Updates the following info for Ionic 7:
- Desktop browser support
- Mobile platform support
- JS Framework support for Angular, React, and Vue
- Updated the Angular 13 note to remove Ionic version-specific language. As a result, I moved it to the Platform support page.
JS Framework Support Policy: https://ionic-docs-git-fw-2005-ionic1.vercel.app/docs/reference/support
Browser Support: https://ionic-docs-git-fw-2005-ionic1.vercel.app/docs/reference/browser-support
=> docs(support): update JS framework and browser support

docs/api/modal.md
Part of https://github.com/ionic-team/ionic-framework/issues/23108. These docs explain how to add labels to the modal.
=> docs(modal): add label info

docs/api/alert.md
This adds some notes about the best practices for ARIA attributes on `ion-alert`, with the changes from https://github.com/ionic-team/ionic-framework/pull/25805 in mind.
=> docs(alert): add accessibility section

docs/api/infinite-scroll.md
Documents general best practices regarding the use of `role="feed"` on the scrollable element and `role="article"` or `<article>` in an infinite scroll experience. 
This doesn't outline behavior for `aria-busy`, as this will likely be a responsibility of the infinite scroll component in the near future.
=> docs(infinite-scroll): accessibility best practice for role="feed"

docs/api/action-sheet.md
Adds some accessibility best practices with the change from https://github.com/ionic-team/ionic-framework/pull/25837 in mind.
=> docs(action-sheet): add accessibility section

docs/react/virtual-scroll.md
Removes the outdated section from the React virtual scroll docs that references the resolved issue.
=> docs(react): remove virtual scroll outdated section

docs/api/toast.md
aria-live controls how screen readers announce _updates_ to toast content. It does not handle the initial presentation (despite what VoiceOver may do on macOS/iOS).
=> docs(toast): fix aria-live usage

docs/api/checkbox.md, static/usage/checkbox/basic/angular.md, static/usage/checkbox/basic/demo.html, static/usage/checkbox/basic/index.md, static/usage/checkbox/basic/javascript.md, static/usage/checkbox/basic/react.md, static/usage/checkbox/basic/vue.md
- Adds basic playground that shows how to use checkbox, label, and item together.
Live preview: https://ionic-docs-git-1298-basic-ionic1.vercel.app/docs/api/checkbox#basic
=> docs(checkbox): add basic playground

src/components/global/Playground/icons/IconDots.tsx
During development I noticed the following error in the console:
```
react-dom.development.js?ac89:67 Warning: Invalid DOM property `class`. Did you mean `className`?
at div
at IconDots
at div
at div
at div
at div
at Playground (webpack-internal:///./src/components/global/Playground/index.tsx:23:35)
```
The dots icon component should use `className` instead of `class`.
=> fix(playground): use className instead of class

docs/api/checkbox.md, src/components/global/Playground/icons/IconDots.tsx, src/components/global/Playground/index.tsx, static/usage/checkbox/indeterminate/angular.md, static/usage/checkbox/indeterminate/demo.html, static/usage/checkbox/indeterminate/index.md, static/usage/checkbox/indeterminate/javascript.md, static/usage/checkbox/indeterminate/react.md, static/usage/checkbox/indeterminate/vue.md
- Adds a playground for using the indeterminate state in  `ion-checkbox`
=> docs(checkbox): add indeterminate demos

docs/api/checkbox.md, static/usage/checkbox/theming/angular/example_component_css.md, static/usage/checkbox/theming/angular/example_component_html.md, static/usage/checkbox/theming/demo.html, static/usage/checkbox/theming/index.md, static/usage/checkbox/theming/javascript.md, static/usage/checkbox/theming/react/main_css.md, static/usage/checkbox/theming/react/main_tsx.md, static/usage/checkbox/theming/vue.md
- Adds a playground that shows how to use CSS Variables and Shadow Parts with `ion-checkbox`.
=> docs(checkbox): add theming playground

scripts/data/native.json
Adds a description for the https://github.com/iamport/iamport-cordova plugin (translated from Github repo description/about section).
=> docs(native/iamport): add description for cordova plugin

docs/deployment/desktop-app.md
Updating the electron link to include the new link for tutorial-first-app
=> docs(desktop-app): Update link to electron first app tutorial

docs/api/menu.md, static/usage/menu/basic/angular.md, static/usage/menu/basic/demo.html, static/usage/menu/basic/index.md, static/usage/menu/basic/javascript.md, static/usage/menu/basic/react.md, static/usage/menu/basic/vue.md
Adds an example on how to use the menu with a menu button + configure it with the content to get the swipe gesture.
https://ionic-docs-git-1282-basic-ionic1.vercel.app/docs/api/menu#basic-usage
=> docs(menu): add basic usage

docs/api/menu.md, static/usage/menu/theming/angular/example_component_css.md, static/usage/menu/theming/angular/example_component_html.md, static/usage/menu/theming/demo.html, static/usage/menu/theming/index.md, static/usage/menu/theming/javascript.md, static/usage/menu/theming/react/main_css.md, static/usage/menu/theming/react/main_tsx.md, static/usage/menu/theming/vue.md
Adds a playground for showing how to use CSS Shadow Parts with `ion-menu`.
https://ionic-docs-git-1282-theming-ionic1.vercel.app/docs/api/menu
=> docs(menu): add theming playground

docs/api/spinner.md, static/usage/spinner/basic/angular.md, static/usage/spinner/basic/demo.html, static/usage/spinner/basic/index.md, static/usage/spinner/basic/javascript.md, static/usage/spinner/basic/react.md, static/usage/spinner/basic/vue.md, static/usage/spinner/theming/colors/angular.md, static/usage/spinner/theming/colors/demo.html, static/usage/spinner/theming/colors/index.md, static/usage/spinner/theming/colors/javascript.md, static/usage/spinner/theming/colors/react.md, static/usage/spinner/theming/colors/vue.md, static/usage/spinner/theming/css-properties/angular.md, static/usage/spinner/theming/css-properties/angular/example_component_css.md, static/usage/spinner/theming/css-properties/angular/example_component_html.md, static/usage/spinner/theming/css-properties/demo.html, static/usage/spinner/theming/css-properties/index.md, static/usage/spinner/theming/css-properties/javascript.md, static/usage/spinner/theming/css-properties/react.md, static/usage/spinner/theming/css-properties/react/main_css.md, static/usage/spinner/theming/css-properties/react/main_tsx.md, static/usage/spinner/theming/css-properties/vue.md
Adds playgrounds for:
- Basic Usage
- Theming
- Colors
- CSS Custom Properties
At first I had both playgrounds with the spinners in a list, but I changed the colors one to be more simple. If you think the first one shouldn't use a list either, or they both should, let me know. 
Corrects the usage section which stated the default for Material Design was `crescent` as it is now `circular`.
https://ionic-docs-git-fw-1265-ionic1.vercel.app/docs/api/spinner
=> docs(spinner): add component playgrounds

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/content-issue.yml, .github/ISSUE_TEMPLATE/feature_request.yml
The templates should say "validations" instead of "validation".
=> docs(template): fix validation typo

static/code/stackblitz/angular/app.component.html, static/code/stackblitz/angular/app.component.withContent.html
This adds the `ion-page` class to the stackblitz code that is used for Angular projects when `includeIonContent={false}`. I didn't add it to the code that adds an `ion-content` wrapper because it will cause the content to cover up the padding area. It is required to properly position header, content, footer in the demos. 
Angular before fix:
JavaScript before fix:
=> fix(playground): add ion-page class to angular stackbiltz code

docs/vue/overview.md
There is an extra `overview` heading at https://ionicframework.com/docs/vue/overview
This PR removes that heading:
=> docs(vue): remove extra 'overview' heading

docs/api/accordion.md, docs/api/item-divider.md, docs/api/item-group.md, docs/api/item-sliding.md, docs/api/list-header.md, docs/api/list.md, docs/api/progress-bar.md, docs/api/segment-button.md, docs/api/segment.md, docs/api/spinner.md
The "Contents" header was missed when porting some api docs:
This PR removes it from the ones that have been moved over and no longer have a TOC
=> docs(api): remove contents header from new api docs

docs/developing/hardware-back-button.md
in `docs/developing/hardware-back-button.md` , I found the following code for Angular, to exit from an Ionic  app:
```
import { IonRouterOutlet, Platform } from '@ionic/angular';
import { App } from '@capacitor/app';
...
constructor(
private platform: Platform,
private routerOutlet: IonRouterOutlet
) {
this.platform.backButton.subscribeWithPriority(-1, () => {
if (!this.routerOutlet.canGoBack()) {
App.exitApp();
}
});
}
```
The problem is when you run `ionic serve` with that code you will get the following error:
```
ERROR NullInjectorError: R3InjectorError(AppModule)[IonRouterOutlet -> IonRouterOutlet -> IonRouterOutlet]: 
NullInjectorError: No provider for IonRouterOutlet!
```
so I searched for a solution and I founed this post …
=> docs(hardware-back-button): IonRouterOutlet is an optional provider

static/usage/datetime-button/basic/react.md
Currently, the basic usage playground for `ion-datetime-button` (https://ionicframework.com/docs/api/datetime-button) will error out in the React Stackblitz.
This PR adds fragment tags to resolve this error.
Preview shortcut: https://ionic-docs-git-datetime-button-react-fix-ionic1.vercel.app/docs/api/datetime-button
=> fix(datetime-button): add fragment tags to React example

docs/api/modal.md
The `ModalOptions` interface is currently manually written. I forgot to add `canDismiss` and deprecate `swipeToClose` when the `canDismiss` feature was added.
=> docs(modal): add canDismiss, deprecate swipeToClose

static/usage/modal/can-dismiss/function/angular/example_component_html.md
The `presentingElement` was never passed to the `ion-modal` element, so the card style was not activated.
=> docs(modal): fix angular card modal example

docs/reference/support.md
"Extended Support" for Ionic v4 ended on September 30, 2022. This PR updates the support table to reflect that.
=> chore(support): move v4 to end of support

docs/theming/css-shadow-parts.md
this commit removes a '>' that doesn't appear to be used/needed following an internal link
=> docs(shadow-parts): remove errant '>' char

docs/developing/hardware-back-button.md
As noted here: https://github.com/ionic-team/ionic-docs/issues/2337 It was unclear the @capacitor/app is required for the hardware back button to work correctly in ionic apps.
=> docs(hardware-back-button): mention capacitor app package

src/components/global/Playground/stackblitz.utils.ts, static/code/stackblitz/angular/angular.json, static/code/stackblitz/angular/styles.css, static/code/stackblitz/angular/variables.css, static/code/stackblitz/html/index.ts, static/code/stackblitz/html/variables.css, static/code/stackblitz/react/app.tsx, static/code/stackblitz/react/app.withContent.tsx, static/code/stackblitz/react/variables.css, static/code/stackblitz/vue/main.ts, static/code/stackblitz/vue/variables.css
This PR does the following:
- Adds the `variables.css` file to the angular, javascript (html), react and vue directories.
- The source code for this file was copied from the starters
- Adds the missing import of `display.css` to the react, javascript and angular css imports.
- Passes the `variables.css` file to StackBlitz in a folder called `theme`
- This was done to match the directory structure of the starters
**Issue found:**
When viewing the website in light mode, then opening a StackBlitz (any language) while the system is set to prefer dark mode, it will display the StackBlitz example in dark mode. This is working as intended based on the content in the `variable.css` file, but it may be unexpected for users since the website is not automatically displayed in dark mode until you …
=> feat(playground): pass the variables theming file to StackBlitz

docs/index.md
=> docs(react): update link to react overview

src/components/global/Playground/index.tsx, src/components/global/Playground/stackblitz.utils.ts, static/code/stackblitz/angular/app.module.ts, static/code/stackblitz/html/index.html, static/code/stackblitz/html/index.withContent.html, static/code/stackblitz/react/app.tsx, static/code/stackblitz/react/app.withContent.tsx, static/code/stackblitz/vue/main.ts
This PR passes the mode from the `ios` / `md` toggle on the playground to StackBlitz so you can see the examples in the same mode you have selected.
I know we discussed doing this by setting it on `ion-app` but I found two issues with that approach:
1) It doesn't work at all for React 
2) The styling is actually slightly off with it set on `ion-app`, see below
Buttons with `<ion-app mode="ios">`:
Buttons with mode set via the config:
So that's why I decided to set it via the config for all of the examples. Let me know if you think there's a better way.
=> feat(playground): add support for opening in StackBlitz in ios mode

docs/developing/android.md
Installing Android SDK today via Android Studio on Linux leads typically to "$HOME/Android/Sdk" and not "$HOME/Android/sdk".
=> docs(developing): fix sdk uppercase directory

docs/api/textarea.md, static/usage/textarea/autogrow/angular.md, static/usage/textarea/autogrow/demo.html, static/usage/textarea/autogrow/index.md, static/usage/textarea/autogrow/javascript.md, static/usage/textarea/autogrow/react.md, static/usage/textarea/autogrow/vue.md, static/usage/textarea/basic/angular.md, static/usage/textarea/basic/demo.html, static/usage/textarea/basic/index.md, static/usage/textarea/basic/javascript.md, static/usage/textarea/basic/react.md, static/usage/textarea/basic/vue.md, static/usage/textarea/clear-on-edit/angular.md, static/usage/textarea/clear-on-edit/demo.html, static/usage/textarea/clear-on-edit/index.md, static/usage/textarea/clear-on-edit/javascript.md, static/usage/textarea/clear-on-edit/react.md, static/usage/textarea/clear-on-edit/vue.md, static/usage/textarea/theming/angular/example_component_css.md, static/usage/textarea/theming/angular/example_component_html.md, static/usage/textarea/theming/demo.html, static/usage/textarea/theming/index.md, static/usage/textarea/theming/javascript.md, static/usage/textarea/theming/react/main_css.md, static/usage/textarea/theming/react/main_tsx.md, static/usage/textarea/theming/vue.md
Adds the following playgrounds for `ion-textarea`:
- Basic Usage
- Autogrow
- Clear on Edit
- Theming
For the Clear on Edit playground, I elected to leave off the default `value` since the `clearOnEdit` behavior currently requires focusing the input, blurring it, and then focusing it again. This will be resolved in Ionic v7.
=> docs(textarea): add playgrounds

docs/api/ripple-effect.md, static/usage/ripple-effect/basic/angular/example_component_css.md, static/usage/ripple-effect/basic/angular/example_component_html.md, static/usage/ripple-effect/basic/demo.html, static/usage/ripple-effect/basic/index.md, static/usage/ripple-effect/basic/javascript.md, static/usage/ripple-effect/basic/react/main_css.md, static/usage/ripple-effect/basic/react/main_tsx.md, static/usage/ripple-effect/basic/vue.md, static/usage/ripple-effect/customizing/angular/example_component_css.md, static/usage/ripple-effect/customizing/angular/example_component_html.md, static/usage/ripple-effect/customizing/demo.html, static/usage/ripple-effect/customizing/index.md, static/usage/ripple-effect/customizing/javascript.md, static/usage/ripple-effect/customizing/react/main_css.md, static/usage/ripple-effect/customizing/react/main_tsx.md, static/usage/ripple-effect/customizing/vue.md, static/usage/ripple-effect/type/angular/example_component_css.md, static/usage/ripple-effect/type/angular/example_component_html.md, static/usage/ripple-effect/type/demo.html, static/usage/ripple-effect/type/index.md, static/usage/ripple-effect/type/javascript.md, static/usage/ripple-effect/type/react/main_css.md, static/usage/ripple-effect/type/react/main_tsx.md, static/usage/ripple-effect/type/vue.md
Adds the following playgrounds for ripple effect:
- Basic Usage
- Type
- Customizing
I got the idea to use shapes for the examples from Material Design here: https://material.io/develop/ios/supporting/ripple
Preview: https://ionic-docs-git-fw-1271-ionic1.vercel.app/docs/api/ripple-effect
=> docs(ripple-effect): add component playgrounds

.gitignore, static/code/stackblitz/react/package-lock.json, static/code/stackblitz/vue/package-lock.json
Updates the dependency lock files used by the React and Vue Stackblitz examples.
=> chore(playground): update react/vue lock dependencies

docs/developing/android.md
Changed the section for Android Live Reload with Capacitor to use --external instead, otherwise (on MacOS) the prompt will get stuck on `[INFO] Waiting for connectivity with ng...`
=> Updated android.md

docs/angular/platform.md
Updates the formatting of the public API methods for the Angular "Platform" page to match other documentation pages.
- No content adjustments
Main: https://ionicframework.com/docs/angular/platform
PR: https://ionic-docs-git-docs-angular-platform-ionic1.vercel.app/docs/angular/platform
=> docs(angular): format public api methods as a table

docs/angular/config.md
Revamps the documentation surrounding the `Config` provider and usage in Angular. If we agree with the general layout and content adjustments, I can make similar changes to React and Vue.
Related issues: #2580
Quick preview: https://ionic-docs-git-docs-angular-config-ionic1.vercel.app/docs/angular/config
=> docs(angular): config provider usage and content updates

docs/react/config.md, docs/vue/config.md
Aligns the headings for the "Config" page to match the changes in: https://github.com/ionic-team/ionic-docs/pull/2614
Preview links:
- React: https://ionic-docs-git-docs-config-toc-ionic1.vercel.app/docs/react/config#interfaces
- Vue: https://ionic-docs-git-docs-config-toc-ionic1.vercel.app/docs/vue/config#interfaces
=> docs(react/vue): heading levels for interfaces and IonicConfig

src/components/global/Playground/playground.css
While working on https://github.com/ionic-team/ionic-docs/pull/2622 I noticed that the `fullscreen` property would only apply to the first iframe that gets loaded, so usually `ios` only and not `md`. This can be reproduced on the live documentation too.
**Steps to reproduce:**
1) Go to https://ionicframework.com/docs/api/footer#translucent-footer
2) Scroll down in the demo on `ios` mode, you'll see the footer is translucent and content is behind it.
3) Switch to `md` mode, scroll to the very bottom and you'll see the scrollbar ends above the footer. This should be behind the footer. 
**An easier way to see** it is by running the documentation locally on `main` and adding the following CSS to the test at `static/usage/footer/translucent/demo.html`:
```
<style>
ion-content {
--background: …
```
=> fix(playground): use visibility hidden to hide iframe for proper loading

docs/api/img.md, static/usage/img/basic/angular.md, static/usage/img/basic/demo.html, static/usage/img/basic/index.md, static/usage/img/basic/javascript.md, static/usage/img/basic/react.md, static/usage/img/basic/vue.md
This PR removes the old Usage tabs and the inline TOC. It also adds a basic usage playground that shows how to use the `src` and `alt` properties on `ion-img`.
=> docs(img): add playground

scripts/api.js
Currently the deprecated messages in our property documentation is not displaying in the generated output: https://ionicframework.com/docs/api/modal#swipetoclose
This PR adds support for adding ` (deprecated)` to the title of deprecated properties as well as displaying the deprecation message in the description. 
Quick-preview: https://ionic-docs-git-fix-deprecated-docs-ionic1.vercel.app/docs/api/modal#swipetoclose-deprecated
=> fix(docs): deprecated message for props

static/usage/list-header/lines/angular.md, static/usage/list-header/lines/javascript.md, static/usage/list-header/lines/react.md, static/usage/list-header/lines/vue.md
The playground example for [List Header Lines](https://ionicframework.com/docs/api/list-header#list-header-lines) is incorrect from the demo.
This PR updates the usage code snippets to match the rendered demo. 
Resolves: #2638
=> docs(list-header): lines playground example

docs/vue/troubleshooting.md
Some developers were unaware of the kebab case behavior in Vue applications, so I added updated the troubleshooting guide to explain this: https://forum.ionicframework.com/t/ionbreakpointdidchange-not-firing-event/226446
=> docs(vue): add event troubleshooting

docs/api/datetime.md
The `ion-datetime` documentation refers to the `done` API, which does not exist. This was a typo and was meant to reference the `confirm` API. I've additionally linked to these APIs to help developers navigating the docs. 
Resolves #2637
=> docs(datetime): confirmation buttons use the confirm api

docs/reference/support.md
⚠️ Do not merge until Angular 15 release.
This PR updates the Framework Support guide to note that Angular 15 is supported starting in Ionic v6.3.6
=> docs(support): add angular 15

docs/api/split-pane.md, static/usage/split-pane/basic/angular.md, static/usage/split-pane/basic/demo.html, static/usage/split-pane/basic/index.md, static/usage/split-pane/basic/javascript.md, static/usage/split-pane/basic/react.md, static/usage/split-pane/basic/vue.md
- Adds basic usage for spit pane.
I opted to set `when="xs"` on the split pane otherwise it would also be collapsed in the playground
Preview: https://ionic-docs-git-1264-basic-ionic1.vercel.app/docs/api/split-pane#basic-usage
=> docs(split-pane): add basic usage

docs/api/split-pane.md, static/usage/spinner/theming/css-properties/angular.md, static/usage/split-pane/basic/angular.md, static/usage/split-pane/basic/demo.html, static/usage/split-pane/basic/index.md, static/usage/split-pane/basic/javascript.md, static/usage/split-pane/basic/react.md, static/usage/split-pane/basic/vue.md, static/usage/split-pane/theming/css-properties/angular/example_component_css.md, static/usage/split-pane/theming/css-properties/angular/example_component_html.md, static/usage/split-pane/theming/css-properties/demo.html, static/usage/split-pane/theming/css-properties/index.md, static/usage/split-pane/theming/css-properties/javascript.md, static/usage/split-pane/theming/css-properties/react/main_css.md, static/usage/split-pane/theming/css-properties/react/main_tsx.md, static/usage/split-pane/theming/css-properties/vue.md
Adds component playgrounds for:
- Basic usage with a menu
- Usage with CSS properties for customization
=> docs(split-pane): add component playgrounds

docs/vue/quickstart.md
Hi awesome people :)
Found a tiny syntax error when going through the Quickstart for Vue. The example just needed a Typescript lang attribute value.
Cheers and amazing work!
=> docs(vue): specify lang attribute for quickstart example

static/usage/content/scroll-methods/angular/example_component_ts.md, static/usage/content/scroll-methods/demo.html, static/usage/content/scroll-methods/javascript.md, static/usage/content/scroll-methods/react.md, static/usage/content/scroll-methods/vue.md
The commented description of the `ion-content` component has been corrected by fixing the typo (and by adding for the example of Vue.js).
=> docs(content): code example comments

docs/reference/versioning.md
The Framework team has moved to patch releases every week and minor releases every 6 weeks.
=> chore(releases): revise release schedule

docs/reference/support.md
Extended Support on v5 ended Dec 8th, 2022. This PR updates the support document to reflect this.
=> chore(support): move v5 to end of extended support

docs/api/modal.md
Adds updated type definition for `canDismiss` from Ionic 6.4.0.
Related issue: https://github.com/ionic-team/ionic-framework/issues/26544
=> docs(modal): canDismiss type definition

docs/api/tabs.md
this isn't an edit about wrong stuff or not, but it's not clear why is it missing the ion-router-outlet while if I added it as-is it warns me of the lack of an ion router outlet. and it's confusing for why it's not referenced here. in addition to that it's not clear where should I add the tabs component and the schedule component etc
=> docs(tabs): vue usage includes router outlet

docs/api/tab-button.md, docs/api/tabs.md
The icons in each tab serve as decoration as each tab button has a visible label. As a result, they should not be announced by screen readers. This PR adds aria-hidden="true" to the icons used in the usage examples.
=> docs(tabs): icons are hidden in usage examples

docs/api/button.md
A developer noted that the usage of "block" terms is confusing: https://github.com/ionic-team/ionic-framework/issues/26565
I updated the "expand" docs to clarify the difference between "block" as a CSS keyword and "block" as a value in the `expand` property
=> docs(button): clarify display behavior for expand

docs/vue/your-first-app.md, docs/vue/your-first-app/2-taking-photos.md, docs/vue/your-first-app/3-saving-photos.md, docs/vue/your-first-app/4-loading-photos.md, docs/vue/your-first-app/5-adding-mobile.md, docs/vue/your-first-app/7-live-reload.md
Since this tutorial was written, a few changes have happened:
1. File naming in the starters changed (Tab2.vue -> Tab2Page.vue)
2. We switched to `script setup` syntax in SFCs
3. The Vue tooling got tighter with regard to linting errors, so some steps actually caused temporary build issues since Vue does a lint as part of the serve
This is an attempt to bring the tutorial itself in line with these changes.
=> docs(vue): bring the photo gallery app up to date

scripts/cli.js, scripts/data/cli.json, scripts/utils.js
- Commands that do not have options wont have examples like `ionic signup [options]`
- Option for `--lab` has been removed from description of ionic serve
- Option for `--lab-port` has been removed from ionic serve
- Tables for options and advanced options replaced with standard headers and text
- Any inputs to commands are shown as arguments. Eg `ionic cordova build [platform]` rather than `ionic cordova build [inputs]`
- `doctor` commands now have a deprecation warning
=> fix(cli): Handle deprecated commands, replace tables with formatting similar to Capacitor CLI docs

static/usage/v7/modal/performance/mount/demo.html, static/usage/v7/toast/buttons/angular/example_component_ts.md
This PR removes a couple of leftover controller imports from playgrounds that have been migrated to show the new inline usage for their respective overlays.
=> chore(modal, toast): remove unneeded controller imports

docs/api/loading.md
This PR notes the following loading behaviors:
1. `role="dialog"` automatically set on host
2. `aria-labelledby` set to the message element ID if there is a message
3. Developers must set `aria-label` if no message property is set.
4. Developers can customize all ARIA attributes using `htmlAttributes`.
=> docs(loading): add accessibility section

docs/api/fab.md
Part of https://github.com/ionic-team/ionic-framework/pull/26619
This PR notes that developers must add a label to each fab button.
=> docs(fab): add label notes for fab

docs/intro/upgrading-to-ionic-7.md, docs/updating/4-0.md, docs/updating/5-0.md, docs/updating/6-0.md, docs/updating/7-0.md, sidebars.js
This PR does a few things:
1. Remove the "Upgrading to Ionic 6" and "Migration" links in favor of a dedicated "Upgrade Guides" section on the sidebar. This improves the visibility of the migration guides. It also scales better than the previous approach as we can add an `8-0.md` file to the `updating` directory when it comes time to write the Ionic 8 migration guide.
2. Creates the Ionic 7 migration. I only included the changes that are required in order for an app to compile. (This is what we did with the Ionic 6 migration guide too)
3. Adds a note to the v5, v6, and v7 upgrade guides reminding users to update to the latest version of the previous major release before proceeding with upgrading.
~Note: I still need to create 301 redirects so the old migration guide links do not break. …
=> docs(upgrade-guides): add v7 migration, new upgrade guide links

docs/updating/7-0.md
I forgot to add a note about how to migrate the browserslist file when updating to v7. This is important so framework compilers (such as the Angular CLI) correctly transpile code during the build process.
=> docs(migration): add browserslist step

docusaurus.config.js
Updates the primary call to action for the upgrade guide to reference Ionic v7.0.0 and to link to the new upgrade guide.
=> fix(docs): update upgrade guide cta

docs/api/icon.md, docs/components.md, sidebars.js, static/usage/v6/icon/basic/angular.md, static/usage/v6/icon/basic/demo.html, static/usage/v6/icon/basic/index.md, static/usage/v6/icon/basic/javascript.md, static/usage/v6/icon/basic/react.md, static/usage/v6/icon/basic/vue.md, static/usage/v7/icon/basic/angular.md, static/usage/v7/icon/basic/demo.html, static/usage/v7/icon/basic/index.md, static/usage/v7/icon/basic/javascript.md, static/usage/v7/icon/basic/react.md, static/usage/v7/icon/basic/vue.md, versioned_docs/version-v6/api/icon.md, versioned_docs/version-v6/components.md, versioned_sidebars/version-v6-sidebars.json
Currently, our docs just link to https://ionic.io/ionicons for info on `ion-icon`. This PR adds a dedicated page for the component, so that we can include a playground in an easy-to-find spot showing how to import and use the icon names with each framework. It also edits the links in the sidebar and main components index page to point to this new dedicated page instead of the Ionicons site.
Some things to note:
- While this PR includes docs for both v6 and v7, it's off the v7 branch so no extra work is needed given the structural changes to the docs repo. There is a separate PR at https://github.com/ionic-team/ionic-docs/pull/2710 which backports the updates to `main`.
- I left off the autogenerated props, methods, etc. because the docs site pulls this info from a file auto-generated by …
=> docs(icon): add dedicated component page and playground

docs/developing/scaffolding.md
The `ionic generate` command is only supported in Ionic Angular. While this is mentioned in the dedicated docs for the command (https://ionicframework.com/docs/cli/commands/generate), the Scaffolding docs are more misleading: https://ionicframework.com/docs/developing/scaffolding#generating-new-features This PR adds a note to this section to clarify the support situation.
Resolves https://github.com/ionic-team/ionic-docs/issues/1799
=> docs(scaffolding): add support note to ionic generate docs

docs/react.md, docs/react/adding-ionic-react-to-an-existing-react-project.md, sidebars.js
The Ionic React resources is linking out to an outdated blog post for adding `@ionic/react` to an existing React application. This PR migrates that content into the Ionic Docs and updates the content to reflect the required changes as of Ionic 6. 
Resolves #2714
=> docs(react): adding react to an existing app

docusaurus.config.js
Reverts the CTA for the upgrade guide back to v6 in the interim.
=> fix(upgrade-pill): revert back to v6 upgrade guide

docs/api/modal.md, versioned_docs/version-v6/api/modal.md
Resolves https://github.com/ionic-team/ionic-docs/issues/2155. This behavior is also noted in the `canDismiss` section (https://ionicframework.com/docs/api/modal#preventing-a-modal-from-dismissing) but this makes the info easier to find.
=> docs(modal): note that 0 breakpoint is required for dismiss on swipe

versioned_docs/version-v6/angular/slides.md, versioned_docs/version-v6/angular/virtual-scroll.md, versioned_docs/version-v6/api/slide.md, versioned_docs/version-v6/api/slides.md, versioned_docs/version-v6/api/virtual-scroll.md, versioned_docs/version-v6/react/slides.md, versioned_docs/version-v6/react/virtual-scroll.md, versioned_docs/version-v6/vue/slides.md, versioned_docs/version-v6/vue/virtual-scroll.md, versioned_sidebars/version-v6-sidebars.json
The slides and virtual scroll docs got removed from the v6 docs during versioning.
1. Adds the slides, slide, and virtual scroll docs back into the v6 docs.
2. Adds deprecation messages at the top of each component page.
3. Adds each page back to their original locations in the sidebar.
=> docs(many): restore slides and virtual scroll docs

versioned_docs/version-v6/reference/support.md
Some changes were lost during the Docusaurus versioning for v7. This PR restores the changes made to the support policy page for v6.
=> docs(support): update support policy for v6

static/usage/v7/toggle/migration/index.md
The migration guide for `ion-toggle` references `ion-input` in some places. It should reference `ion-toggle` instead.
=> docs(toggle): migration guide references toggles

docs/api/input.md, docs/api/select.md
This PRs clarifies the migration for new form control syntax to state that devs can migrate one by one (i.e. they do not need to do the migration all at once).
Textarea: https://github.com/ionic-team/ionic-docs/pull/2720#discussion_r1092323399
Range: https://github.com/ionic-team/ionic-docs/pull/2742/commits/64c36f981a06fe49997cfa7b9e28d4414bbc45e9
(Checkbox and Radio will have this when the docs are updated)
=> docs(input, select): add note about migrating

src/components/global/Playground/index.tsx
This PR updates Playgrounds to allow for optional usage targets:
1. If a usage target is not defined, then its corresponding JS Framework button will be disabled.
2. The default usage target now accounts for undefined targets. It will default to Angular, otherwise it will fall back to the first key passed.
This functionality is needed for playgrounds that apply to specific usages (i.e. `ion-router` is only usage in vanilla JS apps)
=> feat(playground): usage targets are now optional

src/components/global/Playground/playground.css
This PR fixes the sizing of the rendered `iframe` to fill the available space.
When previewing on a Pixel 5 (can be observed with Chrome Dev Tools/Device Emulation): https://ionicframework.com/docs/v7/api/toast the rendered previews are not visible.
Reported on Twitter: https://twitter.com/vberchet/status/1620981423644475396
Quick preview: https://ionic-docs-git-fix-playground-sizing-ionic1.vercel.app/docs/api/toast
=> fix(playground): demo container is visible on small viewports

static/usage/v6/datetime/basic/demo.html, static/usage/v7/datetime/basic/demo.html
When viewing the [basic usage](https://ionicframework.com/docs/api/datetime#basic-usage) example for `ion-datetime` in MD mode, toggling the month/year picker results in a UI shift. 
This isn't a behavior of Ionic, but the result of the container styles in the demo. 
Aligning the container to the start removes this layout shift.
Before:
<video src="https://user-images.githubusercontent.com/13732623/217121595-2ec22191-b2a2-4053-8c24-fb604dcd719d.mp4"></video>
After:
<video src="https://user-images.githubusercontent.com/13732623/217121683-c9738564-e661-4c56-a6b3-a3266224ebad.mp4"></video>
=> fix(datetime): align basic demo container to the start

static/usage/v7/input/theming/css-properties/angular/example_component_css.md, static/usage/v7/input/theming/css-properties/angular/example_component_html.md, static/usage/v7/input/theming/css-properties/demo.html, static/usage/v7/input/theming/css-properties/javascript.md, static/usage/v7/input/theming/css-properties/react/main_css.md, static/usage/v7/input/theming/css-properties/react/main_tsx.md, static/usage/v7/input/theming/css-properties/vue.md, static/usage/v7/textarea/theming/angular/example_component_css.md, static/usage/v7/textarea/theming/angular/example_component_html.md, static/usage/v7/textarea/theming/demo.html, static/usage/v7/textarea/theming/javascript.md, static/usage/v7/textarea/theming/react/main_css.md, static/usage/v7/textarea/theming/react/main_tsx.md, static/usage/v7/textarea/theming/vue.md
See: https://github.com/ionic-team/ionic-framework/issues/26737
This PR makes use of the bottom content on `ion-input` and `ion-textarea` in the theming demos to show how to style this content. I also changed the class on the textarea demo from `custom-textarea` to `custom` for consistency with the input demo (which also uses the `custom` class).
=> docs(input, textarea): add bottom content styling example

docs/angular/slides.md, docs/react/slides.md, docs/vue/slides.md, versioned_docs/version-v6/angular/slides.md, versioned_docs/version-v6/react/slides.md, versioned_docs/version-v6/vue/slides.md
Swiper 9 was recently released and introduced some breaking changes. As a result, our migration guide does not work with Swiper 9. We are working on updating the guide for Swiper 9. Until then, I have added a note stating the guide is only for Swiper 8.
=> docs(slides): note migration guide is for swiper 8

static/usage/v6/select/objects-as-values/multiple-selection/react.md, static/usage/v7/select/objects-as-values/multiple-selection/react.md
https://ionicframework.com/docs/api/select#object-values-and-multiple-selection
The live demo and other examples say "Current value" for the label, but React currently says "Current food".
Resolves https://github.com/ionic-team/ionic-docs/issues/2770
=> docs(select): fix typo in object values and multiple selection React code

docs/api/toast.md, static/usage/v6/toast/layout/angular/example_component_html.md, static/usage/v6/toast/layout/angular/example_component_ts.md, static/usage/v6/toast/layout/demo.html, static/usage/v6/toast/layout/index.md, static/usage/v6/toast/layout/javascript.md, static/usage/v6/toast/layout/react.md, static/usage/v6/toast/layout/vue.md, static/usage/v7/toast/layout/angular/example_component_html.md, static/usage/v7/toast/layout/angular/example_component_ts.md, static/usage/v7/toast/layout/demo.html, static/usage/v7/toast/layout/index.md, static/usage/v7/toast/layout/javascript.md, static/usage/v7/toast/layout/react.md, static/usage/v7/toast/layout/vue.md, versioned_docs/version-v6/api/toast.md
⚠️ Remove dev builds from html demo prior to merging.
Part of https://github.com/ionic-team/ionic-framework/pull/26790
This PR adds a playground to both the v7 and v6 docs to show how to use the new layout feature for `ion-toast`.
Note: I made two dev builds, one for v6 and one for v7, to show in the iframe demos. However, the layout feature will not work on StackBlitz since those are pulling the latest versions of Ionic. The toasts in StackBlitz demos _should_ still open/close properly though.
Preview: https://ionic-docs-git-1503-docs-ionic1.vercel.app/docs/api/toast#layout
=> docs(toast): add layout demos

versioned_docs/version-v6/react/virtual-scroll.md
This issue was resolved in Ionic 6.1, but we missed removing this documentation just from the React docs.
=> docs(react): remove old virtual scroll docs

static/usage/v7/select/typeahead/angular/modal-example_component_html.md, static/usage/v7/select/typeahead/demo.html, static/usage/v7/select/typeahead/javascript.md, static/usage/v7/select/typeahead/react/typeahead_component_tsx.md, static/usage/v7/select/typeahead/vue/typeahead_component_vue.md
The typeahead demo for v7 was not using the newer checkbox syntax.
=> docs(select): use new rendering syntax for typeahead

docs/api/datetime.md, static/usage/v6/datetime/highlightedDates/array/angular/example_component_html.md, static/usage/v6/datetime/highlightedDates/array/angular/example_component_ts.md, static/usage/v6/datetime/highlightedDates/array/demo.html, static/usage/v6/datetime/highlightedDates/array/index.md, static/usage/v6/datetime/highlightedDates/array/javascript.md, static/usage/v6/datetime/highlightedDates/array/react.md, static/usage/v6/datetime/highlightedDates/array/vue.md, static/usage/v6/datetime/highlightedDates/callback/angular/example_component_html.md, static/usage/v6/datetime/highlightedDates/callback/angular/example_component_ts.md, static/usage/v6/datetime/highlightedDates/callback/demo.html, static/usage/v6/datetime/highlightedDates/callback/index.md, static/usage/v6/datetime/highlightedDates/callback/javascript.md, static/usage/v6/datetime/highlightedDates/callback/react.md, static/usage/v6/datetime/highlightedDates/callback/vue.md, static/usage/v7/datetime/highlightedDates/array/angular/example_component_html.md, static/usage/v7/datetime/highlightedDates/array/angular/example_component_ts.md, static/usage/v7/datetime/highlightedDates/array/demo.html, static/usage/v7/datetime/highlightedDates/array/index.md, static/usage/v7/datetime/highlightedDates/array/javascript.md, static/usage/v7/datetime/highlightedDates/array/react.md, static/usage/v7/datetime/highlightedDates/array/vue.md, static/usage/v7/datetime/highlightedDates/callback/angular/example_component_html.md, static/usage/v7/datetime/highlightedDates/callback/angular/example_component_ts.md, static/usage/v7/datetime/highlightedDates/callback/demo.html, static/usage/v7/datetime/highlightedDates/callback/index.md, static/usage/v7/datetime/highlightedDates/callback/javascript.md, static/usage/v7/datetime/highlightedDates/callback/react.md, static/usage/v7/datetime/highlightedDates/callback/vue.md, versioned_docs/version-v6/api/datetime.md
Adds playgrounds for the new `highlightedDates` property added here: https://github.com/ionic-team/ionic-framework/pull/26775 Demos for using the prop as both an array and a callback are included, as well as versions for both v6 and v7.
Dev build for feature: `6.5.3-dev.11676573595.1564fefe`
=> docs(datetime): add highlightedDates playgrounds

docs/react/quickstart.md
react router 5 which is now used by the CLI.  Props.history has been removed from this version
=> docs(react): update router quick start for react router 5

docs/reference/support.md, docs/updating/7-0.md
- Updates minimum Angular version to Angular 14
- Adds input, searchbar, and textarea guides to migration guide re: `ionInput` detail payload
=> docs(migrate): update guide for v7 beta 5

src/components/global/Playground/playground.css
Currently, when viewing a playground with the device frame turned on (e.g. https://ionicframework.com/docs/api/modal#inline-modals-recommended), there is a horizontal scroll bar on iOS mode.
https://github.com/ionic-team/ionic-docs/pull/2623 removed some CSS that was causing this, but it was re-added in https://github.com/ionic-team/ionic-docs/pull/2754 to fix the iframe not filling the space on smaller screen sizes. This PR restricts the CSS to screen sizes where the device frame no longer shows around the iframe (due to [this styling](https://github.com/ionic-team/ionic-docs/blob/ios-scrollbar-fix/src/components/global/Playground/device-preview.js#L124)), since it isn't needed otherwise. This way, no horizontal scroll bar appears, but the iframe is still viewable on smaller screens.
=> fix(playground): prevent horizontal scrollbar on ios device frame view

src/components/global/Playground/index.tsx
Hidden iframes can still be accessed using screen readers via swiping. You can test this on the basic demo for: https://ionicframework.com/docs/api/action-sheet
Open the action sheet and then swipe right with a screen reader on. You should be able to access the hidden MD modal.
=> fix(playground): hidden iframes are hidden from screen readers

static/usage/v6/img/basic/angular.md, static/usage/v6/img/basic/demo.html, static/usage/v6/img/basic/javascript.md, static/usage/v6/img/basic/react.md, static/usage/v6/img/basic/vue.md, versioned_docs/version-v5/index.md, versioned_docs/version-v6/index.md
This PR updates the v5 and v6 docs to use the new versioned deployments of the phone demo app. No changes are necessary for v7 since the latest version of Ionic will always point to `docs-demo.ionic.io`.
However, until the `main` deployment for `docs-demo` is updated the v7 phone demo will still show a v6 app.
=> chore(version): update v5 and v6 docs to use the versioned docs demo deployment

docs/api/icon.md
Sister PR: https://github.com/ionic-team/ionicons-site/pull/31
Preview: https://ionic-docs-git-docs-icons-a11y-ionic1.vercel.app/docs/v7/api/icon#accessibility
=> docs(api): add accessibility section for icons

docs/layout/css-utilities.md
I kept the grid because this saves us from having to clear the floats between examples, but I moved the float css to an image so you can properly see it 
Code preview: https://1vutb4.stackblitz.io
Site preview: https://ionic-docs-git-fw-3055-ionic1.vercel.app/docs/v7/layout/css-utilities#float-elements
closes #265
=> docs(layout): update css-utilities to float properly

src/components/global/Playground/playground.css
resolves https://github.com/ionic-team/ionic-docs/issues/2778
This issue was introduced in https://github.com/ionic-team/ionic-docs/pull/2623 when switching from `display: none` to visibility/width. The IntersectionObserver in `ion-datetime` does not fire when the width/visibility change. As a result, the datetime was attempting to center its contents with the width was `0px`. When the width was reset when the iframe shows, datetime does not adjust again.
The visibility/width code was added because the fullscreen offset variables were not being set correctly on `ion-content` with `display: none`. However, I fixed an issue in https://github.com/ionic-team/ionic-framework/pull/26782 which causes the content to recalculate the offset variables when the `resize` event is dispatched on the …
=> fix(playground): iframe is hidden using display

scripts/native.js, scripts/utils.js
Delete all markdown files that were previously generated from the `docs/native` directory. This avoids the local dev experience having broken links when versioning docs or changing directory structures. 
Additionally removed a really noisy `console.log` in the CLI script.
=> chore: clear docs/native directory when generating markdown

static/usage/v6/toolbar/segments/angular.md, static/usage/v6/toolbar/segments/demo.html, static/usage/v6/toolbar/segments/javascript.md, static/usage/v6/toolbar/segments/react.md, static/usage/v6/toolbar/segments/vue.md, static/usage/v7/toolbar/segments/angular.md, static/usage/v7/toolbar/segments/demo.html, static/usage/v7/toolbar/segments/javascript.md, static/usage/v7/toolbar/segments/react.md, static/usage/v7/toolbar/segments/vue.md
In [Ionic v4](https://github.com/ionic-team/ionic-framework/blob/main/BREAKING_ARCHIVE/v4.md#segment-button) it became a requirement for text inside of a segment button to be wrapped in a label. This PR updates the only Segment playground that doesn't use a label.
=> docs(segment): wrap text in labels for segments in toolbar playground

docs/techniques/security.md, versioned_docs/version-v5/techniques/security.md, versioned_docs/version-v6/techniques/security.md
It is not clear that the built-in sanitizer is not a comprehensive solution. Developers should make sure that any untrusted data is properly sanitized.
=> docs(security): clarify sanitizer

docs/reference/browser-support.md, docs/utilities/gestures.md, versioned_docs/version-v5/reference/browser-support.md, versioned_docs/version-v5/utilities/gestures.md, versioned_docs/version-v6/reference/browser-support.md, versioned_docs/version-v6/utilities/gestures.md
Removes the browser support section from the v6 & v7 docs for the "Gestures" page.
=> docs(gestures): remove browser support section

docs/api/icon.md, versioned_docs/version-v6/api/icon.md
Resolves https://github.com/ionic-team/ionic-docs/issues/2813
The docs page for `ion-icon` mentions that it's possible to use a custom SVG, but doesn't show how to do so. We intentionally avoided including it since it's on the Ionicons site already, but this connection isn't obvious, so I added a note to point people in the right direction.
=> docs(icon): indicate where to find custom SVG usage

docs/utilities/animations.md, versioned_docs/version-v5/utilities/animations.md, versioned_docs/version-v6/utilities/animations.md
- Removes the "Browser Support" section from the animation docs
- Rewords the summary
- Organizes the API related types, methods, etc. under an "API" section with a description of what it pertains to
- Adds missing type information for the `AnimationBuilder`
=> docs(animations): add type interfaces

docs/api/alert.md, versioned_docs/version-v6/api/alert.md
The `label` property on `AlertInput` does not currently explain that it is only applied to radios and checkboxes. This is confusing when a developer renders an input or textarea and expects the label to display.
Issue: https://github.com/ionic-team/ionic-framework/issues/26915
Added a description to the documented interface, so explain that the label is only shown when the input type is `radio` or `checkbox`.
=> docs(alert): alert input label is only for radio/checkbox

docs/react/slides.md, docs/vue/slides.md, versioned_docs/version-v6/react/slides.md, versioned_docs/version-v6/vue/slides.md
Because we decided to stick with Swiper's React/Vue components instead of Swiper Element for now, updating the guides for these two frameworks is mostly minor cleanup things. I also took the liberty of fixing some typos and adjusting the React docs to use the React-formatted component name.
Angular will be handled in a separate PR, as it will be a more significant overhaul to use Swiper Element instead. Updating the example repo linked at the bottom of the docs will also be done later. These changes should all be merged at the same time.
=> docs(slides): update React and Vue migration guides to be compatible with Swiper 9

docs/angular/slides.md, versioned_docs/version-v6/angular/slides.md
Shortcut: https://ionic-docs-git-fw-3513-angular-ionic1.vercel.app/docs/angular/slides
This was a more significant overhaul than the [React and Vue migrations](https://github.com/ionic-team/ionic-docs/pull/2819) because Swiper has removed its Angular component completely, in favor of Swiper Element.
Updating the example repo linked at the bottom of the docs will be done later. Those changes will be merged into `main` at the same time as this one.
If you want to play around with Swiper Element, [here's the repo I've been using to test](https://github.com/amandaejohnston/sandbox-ionic-angular/tree/swiper-migration-testing). Note that you'll also need [this fix in Swiper](https://github.com/nolimits4web/swiper/pull/6474) for any of the functionality to work within an Ionic app; at the time …
=> docs(slides): update Angular migration guide to be compatible with Swiper 9

static/usage/v7/input/migration/index.md, static/usage/v7/textarea/migration/index.md
As a result of the team's recent discussion on item/list I have updated the migration guide to note that metadata on inputs should be used outside of lists. This will require a more in-depth usage guide for items/lists, but this at least removes the incorrect usage.
=> docs(input, textarea): update migration guide for proper metadata usage

docs/updating/4-0.md, docs/updating/5-0.md, docs/updating/6-0.md, docs/updating/7-0.md
This PR updates the following:
- Removes the second "Ionic" in the upgrade guide titles to avoid wrapping title (`Updating from Ionic 5 to Ionic 6` -> `Updating from Ionic 5 to 6`)
- References in the sidebar change from 4.0 to v4 (`Ionic 4.0` -> `Ionic v4`)
- Breaking Changes callout 
- Added to the top of every page (already existed on v4 and v5 pages, exists at the bottom for v6 and v7)
- Becomes a "caution" block instead of a "note" which highlights it red, this could be changed to info instead which would highlight it blue, but I thought it should be highlighted differently
- Updates broken links to the breaking changes documents
- Renames all mentions of versions as `4.0` to `4`, `3.0` to `3`, etc. 
- Change links to other guides from `Upgrades to` to `Updates to` for consistency …
=> docs(updating): clean up verbiage on updating documents

docs/api/badge.md, versioned_docs/version-v6/api/badge.md
resolves #1658 
`<ion-badge>` will be displayed with the style of `none` when no content is provided. This behavior is on v6 and v7 (beta). I added this behavior on the documentation.
=> docs(badge): content must be passed to be shown

versioned_docs/version-v6/cli/livereload.md
Resolves #2805 
Changes v6 docs to remove text that is no longer accurate regarding Capacitor programmatic builds.
Note: The current docs were [already changed](https://github.com/ionic-team/ionic-docs/pull/2687).
=> docs(live reload): update docs about Capacitor programmatic builds

docs/api/back-button.md, versioned_docs/version-v5/theming/platform-styles.md, versioned_docs/version-v6/angular/platform.md, versioned_docs/version-v6/api/back-button.md, versioned_docs/version-v6/intro/upgrading-to-ionic-6.md, versioned_docs/version-v6/react/platform.md, versioned_docs/version-v6/theming/platform-styles.md, versioned_docs/version-v6/vue/platform.md
I missed some links when merging https://github.com/ionic-team/ionic-docs/commit/d28c8314438091c7f8137a223fc9d8671766ebdd. This PR updates affected links to direct to the new `/developing/config` page.
=> docs(many): update config links

CONTRIBUTING.md
`npm install` fails due to:
1. having the wrong version of `npm` and `node`
2. peer dependencies
Instructions have been modified to overcome this until a permanent fix is implemented.
=> docs: update dev workflow instructions

docs/api/input.md, docs/api/textarea.md
Someone on the Ionic Discord noted that we do not state `.ion-touched` is needed. This was a bug we fixed in https://github.com/ionic-team/ionic-framework/commit/ef33270b55122574e0fdb32187410d8d8a4fa1ae, but we did not update the docs.
=> docs(input, textarea): clarify error text behavior

docs/updating/7-0.md
When upgrading a reproduction example to v7, I observed that the `ng update` command does not necessarily update the `rxjs` dependency.
`@ionic/angular` requires at least a minimum version of `7.5.0` of `rxjs`. We do not currently state this in our migration guide.
=> docs: rxjs migration guide for v7

docs/react/slides.md, versioned_docs/version-v6/react/slides.md
When updating the swiper migration repo I discovered that the Swiper React direct import issue can be avoided by using `react-scripts@5`: https://github.com/ionic-team/slides-migration-samples/pull/2
As a result, it is possible to use the aliased imports that Swiper documents on the Swiper website. Unfortunately, I also discovered that I was unable to continue using the direct imports on Swiper 9 (unclear if this is a recent change).
This PR updates the React migration guide to recommend react-scripts v5 and show how to use the aliased imports.
v6 Preview: https://ionic-docs-git-swiper-react-cra-ionic1.vercel.app/docs/react/slides
v7 Preview: https://ionic-docs-git-swiper-react-cra-ionic1.vercel.app/docs/v7/react/slides
=> docs(react): update imports for swiper migration

docs/api/toast.md, docs/developing/hardware-back-button.md, versioned_docs/version-v6/api/toast.md, versioned_docs/version-v6/developing/hardware-back-button.md
Removed any mentions that `ion-toast` can use the hardware back button to dismiss. The change was added to v6 and v7 (beta).
=> docs(toast): remove hardware back button dismissal

docs/angular/lifecycle.md, docs/react/lifecycle.md, docs/vue/lifecycle.md, versioned_docs/version-v6/angular/lifecycle.md, versioned_docs/version-v6/react/lifecycle.md, versioned_docs/version-v6/vue/lifecycle.md
There is some confusion over which components can receive Ionic lifecycles: https://github.com/ionic-team/ionic-framework/issues/27026
This PR updates the lifecycles docs to note that Ionic lifecycles are only called on components mapped to by the router.
=> docs(lifecycle): clarify when lifecycles are called

plugins/docusaurus-plugin-ionic-component-api/index.js
When generating the API docs, we do not account for versions that have no path in the config (i.e. the current version). This causes deployments to fail when updating the latest version of Ionic for the docs.
=> fix(plugin): account for versions with no paths

docusaurus.config.js
Migrates the upgrade guide CTA to the v7 migration gude.
Do not merge until v7 is the default version on the Ionic docs site.
=> docs(upgrade-pill): link to v7 upgrade guide

docs/updating/7-0.md
Updates the link to the breaking changes guide now that `feature-7.0` has been merged into `main` on https://github.com/ionic-team/ionic-framework
=> docs(v7): update breaking changes link

docs/updating/4-0.md
These headers were on the same level as the "Updating From 3 to 4" header at the top, but they should be one layer deeper.
=> docs(migration): fix header levels in v4 migration guide

scripts/i18n.sh
The Japanese docs failed to deploy after we merged https://github.com/ionic-team/ionic-docs/pull/2797 because they only get built in production. I'd like to remove this production-only check so we can catch build errors before PRs merge.
=> chore(i18n): remove production check for Japanese docs

docs/deployment/desktop-app.md
Assuming the Windows section was copied from the macOS section. Should read four instead of two.
=> docs(deployment): typo with windows requirements

scripts/i18n.sh
Currently, v7 documents are tied to v6 at https://ionicframework.com/docs/ja.
The "current" path refers to the commit at https://github.com/ionic-team/ionic-docs/commit/b2e6a101f3d3cffba4b3648aa568df30fe968e67.
And, please tell me if this script is running in the main branch or in the translate/jp branch.
=> fix(jp): set the v7 document version to v7

docs/api/select.md
Multi-select popovers in `ion-select` were added in https://github.com/ionic-team/ionic-framework/pull/23474, but the docs still say you can't use popovers with `multiple="true"`.
=> docs(select): popover can be used with multiple prop

scripts/i18n.sh
Reverts ionic-team/ionic-docs#2884
This commit is causing the build to fail.
=> Revert "fix(jp): set the v7 document version to v7"

docs/react/navigation.md
`useIonRouter` is a public API for Ionic React but it is not documented.  This adds the TypeScript interface for the feature as well as a) what the feature does and b) how to use it.
I excluded deprecated parts of `UseIonRouterResult`
=> docs(react): add example for useIonRouter

static/usage/v6/modal/controller/angular/modal-example_component_html.md, static/usage/v6/modal/controller/demo.html, static/usage/v6/modal/controller/javascript.md, static/usage/v6/modal/controller/react.md, static/usage/v6/modal/controller/vue/modal_vue.md, static/usage/v7/modal/controller/angular/modal-example_component_html.md, static/usage/v7/modal/controller/demo.html, static/usage/v7/modal/controller/javascript.md, static/usage/v7/modal/controller/react.md, static/usage/v7/modal/controller/vue/modal_vue.md
Updates the component playground example for using the modal controller to include a bolded primary action, since the example renders two actions. 
This aligns the example with the inline modal playground.
Applies to both the v6 and v7 playground examples.
=> docs(modal): controller playground uses bolded action

docs/theming/css-shadow-parts.md
The [Vendor Prefixes](https://ionicframework.com/docs/theming/css-shadow-parts#vendor-prefixed-pseudo-elements) section in the docs has incorrect line height, apparently because it starts with `<a>` tag:
Added the markup for the paragraph using `<p>` elements, hopefully this helps to fix it.
=> docs(theming): update vendor prefixed line height

docs/layout/structure.md
- Removes inline code examples & live examples sections
- Adds playground examples from the individual API pages (header, footer, tabs, menu, split pane)
- Updates descriptions to reference components by name instead of tag
- Removes cards to open header/footer api docs
- Removes section on header & footer, instead mentioning that they can be used together under the footer section
resolves #594
Production: https://ionicframework.com/docs/layout/structure
Branch changes: https://ionic-docs-git-fw-2587-ionic1.vercel.app/docs/layout/structure
=> docs(layout): update structure docs to use new playground examples

docs/theming/css-shadow-parts.md
The whitespace is causing the build to fail. This PR removes it.
https://vercel.com/ionic/ionic-docs/2r5wqBig2H6xXJmB4GhWEKPvrgL5
=> docs(theming): remove stray whitespace

static/usage/v7/modal/controller/angular/modal-example_component_html.md, static/usage/v7/modal/controller/demo.html, static/usage/v7/modal/controller/javascript.md, static/usage/v7/modal/controller/react.md, static/usage/v7/modal/controller/vue/modal_vue.md
Updates the v7 controller playground examples to use the modern syntax. Also updates the inconsistencies with the form label across the different frameworks.
=> fix(modal): controller playground uses v7 label syntax

src/styles/components/_doc-sidebar.scss
Updates the indentation for nested categories in the sidebar and the margin spacing between sections. 
You can see an example of a nested sidebar 3 levels deep with these same changes in this PR: https://github.com/ionic-team/ionic-docs/pull/2861 (React > Testing > Unit Testing)
Our goal is to maintain the spacing and indentation for the first-level categories, but allow the nested categories to be indented.
=> fix(styles): add sidebar indentation for nested sections

docs/api/router-link.md, versioned_docs/version-v6/api/router-link.md
The `router-link` is still using the phone demo. This concept was replaced for playgrounds in v6 and v7.
For v6 and v7:
- `router-link` doesn't have a phone demo
- `router-link` follows the established layout structure (sidebar, content, and contents)
- `router-link` links back to `router` for more information
N/A
=> docs(router-link): removal of phone demo on v6 and v7

scripts/native.js
The native script is deleting all plugin files which causes only the last generated plugin to show up: https://ionicframework.com/docs/native
Preview: https://ionic-docs-git-liamdebeasi-patch-1-ionic1.vercel.app/docs/native
=> docs(native): correctly show all the native plugins

src/components/page/theming/ColorGenerator/index.tsx
In the color generator at https://ionicframework.com/docs/theming/color-generator, if you enter a color without a `#`, the generated shade and tint will be properly updated, but the color dot to the left of the main color won't update. This PR ensures there's always a `#` at the start of the input values.
Resolves https://github.com/ionic-team/ionic-docs/issues/1507
=> fix(ColorGenerator): always prepend entered colors with pound sign

docs/api/searchbar.md, static/usage/v7/searchbar/debounce/angular/example_component_html.md, static/usage/v7/searchbar/debounce/angular/example_component_ts.md, static/usage/v7/searchbar/debounce/demo.html, static/usage/v7/searchbar/debounce/javascript.md, static/usage/v7/searchbar/debounce/react.md, static/usage/v7/searchbar/debounce/vue.md
The debounce demo for v7 uses `ionChange` when it should use `ionInput`: https://github.com/ionic-team/ionic-docs/pull/2913
> The debounce property has been updated to control the timing in milliseconds to delay the event emission of the ionInput event after each keystroke. Previously it would delay the event emission of ionChange.
More info: https://github.com/ionic-team/ionic-framework/issues/27192#issuecomment-1506908563
```
Co-authored-by: guillaumesmo <guillaumesmo@users.noreply.github.com>
```
=> docs(searchbar): debounce uses ionInput

docs/intro/next.md, src/components/page/intro/next/DeveloperExperts/index.module.scss, src/components/page/intro/next/DeveloperExperts/index.tsx, versioned_docs/version-v5/intro/next.md, versioned_docs/version-v6/intro/next.md
This PR adds a developer experts section with links.
Requested by Michael and designed by Julia.
=> styles(): Add developer experts cta section to intro/next page

docs/react/your-first-app/2-taking-photos.md
As providing index as keys is a bad practice, this commit modifies the key value to be `photo.filepath` which will be unique and consistent while adding new photos.
[Keys - react docs](https://reactjs.org/docs/lists-and-keys.html#keys) 
[An example for why it is not recommended](https://robinpokorny.com/blog/index-as-a-key-is-an-anti-pattern/)
=> docs(react): provide unique key instead of index

docs/api/toast.md
Docs to accompany https://github.com/ionic-team/ionic-framework/pull/27198.
=> docs(toast): clarify aria-live usage

docs/techniques/security.md
There was some confusion around how to use `IonicSafeString` with the new `innerHTMLTemplatesEnabled` default in Ionic 7: https://github.com/ionic-team/ionic-framework/issues/27118
This PR clarifies that developers using `IonicSafeString` must also set `innerHTMLTemplatesEnabled` to `true`.
=> docs(security): clarify IonicSafeString usage with innerHTMLTemplatesEnabled

scripts/data/cli.json
Update docs for v7 of ionic cli based on breaking changes/changelog:
* **appflow:** The `package` commands and the `deploy build` command have been removed.
The remaining `deploy` commands have been renamed to `live-update`.
| deploy command | live-update command |
| - | - |
| `ionic deploy add` | `ionic live-update add` |
| `ionic deploy configure` | `ionic live-update configure` |
| `ionic deploy manifest` | `ionic live-update manifest` |
See https://ionic.io/docs/appflow/cli/overview for more information on the Ionic Cloud CLI.
* **docs:** The `ionic docs` command has been removed. 
* **doctor:** The `ionic doctor` command has been removed.
* **lab:** The `--lab` option has been removed from `ionic serve`.
=> docs(cli): update Ionic CLI docs for version 7

docs/angular/pwa.md, docs/react/pwa.md, docs/vue/pwa.md
Updates the instructions for using Firebase to deploy a PWA.
Angular: https://ionic-docs-git-docs-update-react-pwa-ionic1.vercel.app/docs/angular/pwa#deploying
React: https://ionic-docs-git-docs-update-react-pwa-ionic1.vercel.app/docs/react/pwa#deploying
Vue: https://ionic-docs-git-docs-update-react-pwa-ionic1.vercel.app/docs/vue/pwa#deploying
Co-authored-by credit has been applied from this PR: https://github.com/ionic-team/ionic-docs/pull/2708.
Note: This is from a community PR, applied to the other similar guides.
=> docs(pwa): update firebase instructions for deploying pwa

docs/reference/support.md
This link does not exist anymore as the migration guides are available as a top-level category in the sidebar.
=> docs(support): remove migration guide link

docs/angular/slides.md, versioned_docs/version-v6/angular/slides.md
The existing styles for the `ion-slides` migration can lead to unexpected results when migrating to Swiper.js elements:
Updates the documentation example to use `flex-direction`.
=> fix: styles for ion-slides migration

src/components/global/Playground/index.tsx, src/components/global/Playground/stackblitz.utils.ts
This feature isn't used in any playgrounds. See https://github.com/ionic-team/ionic-docs/pull/2922#discussion_r1172744254 for context.
=> refactor(playground): remove unused angularModuleOptions feature

docs/api/tab-bar.md, docs/api/tab-button.md, docs/api/tab.md, versioned_docs/version-v5/api/tab-bar.md, versioned_docs/version-v5/api/tab-button.md, versioned_docs/version-v5/api/tab.md, versioned_docs/version-v6/api/tab-bar.md, versioned_docs/version-v6/api/tab-button.md, versioned_docs/version-v6/api/tab.md
Related to https://github.com/ionic-team/ionic-framework/pull/27269, let's remove references to using Stencil with the tabs and tab components. Using Stencil for mobile apps is not encouraged.
=> docs(tab): remove references to using Stencil with tab

crowdin.yml
This PR allows the API docs to be translated using CrowdIn. Note that this only applies to the manually written API docs. Autogenerated docs such as props, events, methods, will not be added to CrowdIn. We plan to enable this in the future.
=> chore(crowdin): api docs are no longer ignored

src/components/global/DocDemo/index.js, src/components/global/Playground/index.tsx
Fixes a couple console errors that you currently get when local hosting the docs, with React complaining of list elements missing unique keys.
| Viewing docs home page | Viewing any component page w/ playgrounds |
-------------------- | --------------------
| ![error](https://i.gyazo.com/8b34b55679763af41a5d0436c18b394d.png) | ![error 2](https://i.gyazo.com/50983b1886d8464fb38895251f571fe9.png) |
=> fix(docsdemo, playground): add keys to list items

src/components/global/DocDemo/index.js, src/components/page/theming/ColorAccordion/index.tsx
Fixes console errors that appear when local-hosting the docs due to JSX SVG props and CSS `style` props not being formatted correctly.
Example:
=> fix(docdemo, coloraccordion): correctly format SVG/CSS props

docs/angular/slides.md, docs/vue/slides.md, versioned_docs/version-v6/angular/slides.md, versioned_docs/version-v6/vue/slides.md
=> docs(Swiper): fix typo in slidesPerView value

docs/developing/android.md
An updated version of https://github.com/ionic-team/ionic-docs/pull/2043 that uses the locations/wording from the latest version of Android Studio.
=> docs(android): update where to find SDK/AVD managers

src/pages/developing/tips.md
To resolve permission issues on Arch Linux based distros, need to add an additional command that solves the issue.
=> docs(developing): update the commands to resolve permission issues

docs/angular/lifecycle.md, docs/react/lifecycle.md, docs/vue/lifecycle.md
On https://github.com/ionic-team/ionic-docs/pull/2178, a developer noted that the lifecycle descriptions are confusing. For example, the `ionViewDidLeave` description  discusses the lifecycle relative to the entering view, even though this lifecycle hook is fired on the leaving view.
This PR is an extension of the above PR to port the changes to all the lifecycle guides.
```
Co-authored-by: BAYiTUPAi <BAYiTUPAi@users.noreply.github.com>
```
=> docs(lifecycle): clarify method descriptions

docs/reference/support.md
This PR updates the support table to note that Angular 16 is supported for Ionic v7
=> docs(support): update angular support policy

static/usage/v7/tabs/router/index.md
Issue URL: N/A
Tabs has a playground for router that was using v6's `demo.hmtl`
Switched it to v7's `demo.hmtl`
N/A
=> fix(tabs): correct router playground src

docs/react/navigation.md
Using IonContent in this way makes the entire view scrollable via the rubber band effect on iOS. This is likely a typo as the component is not used in our Tabs starters: https://github.com/ionic-team/starters/blob/main/react/official/tabs/src/App.tsx
=> docs(react): remove IonContent from tabs example

docs/vue/navigation.md
Using IonContent in this way makes the entire view scrollable via the rubber band effect on iOS. This is likely a typo as the component is not used in our Tabs starters: https://github.com/ionic-team/starters/blob/main/vue/official/tabs/src/views/TabsPage.vue
=> docs(vue): remove IonContent from tabs example

src/components/page/theming/CodeColor/index.tsx, src/components/page/theming/LayeredColorsSelect/index.tsx
Fixes two invalid DOM nesting errors that appear in the console when local hosting the docs at http://localhost:3000/docs/theming/colors:
1. `LayeredColorsSelect`: `<tr>` can't be a direct descendant of `<table>` (rows wrapped in `<thead>` and `<tbody>` as appropriate)
2. `CodeColor`: `<div>` can't be a descendant of `<p>` (component wrapper changed to a `<span>` instead)
=> fix(CodeColor, LayeredColorsSelect): fix invalid DOM nesting

docs/reference/glossary.md, versioned_docs/version-v5/reference/glossary.md, versioned_docs/version-v6/reference/glossary.md
https://github.com/ionic-team/ionic-docs/assets/171174/d009bcad-aacf-452e-a135-f53b3e087c2f
=> fix: Ionic CLI links to latest docs page 

static/usage/v6/tabs/router/angular/example_component_html.md, static/usage/v7/tabs/router/angular/example_component_html.md
This PR is in favor of: https://github.com/ionic-team/ionic-docs/pull/2960
Co-authored-by credit has been applied to the commit.
The usage for `ion-tabs` in Angular is incorrect. Ionic Framework renders the `ion-router-outlet` inside the container for the developer, they do not need to explicitly render it.
=> docs(tabs): angular usage does not use explicit ion-router-outlet

docs/troubleshooting/cors.md
Include different options for Capacitor and Cordova (legacy). Also fixes what was a dead link to Ionic Native.
=> doc(CORS): update the native options

docs/reference/versioning.md
As per our team process change: Minor releases are now done every 4 weeks if needed.
=> chore: update minor release to happen every 4 weeks if needed

docs/api/select.md, static/usage/v7/select/label-slot/angular.md, static/usage/v7/select/label-slot/demo.html, static/usage/v7/select/label-slot/index.md, static/usage/v7/select/label-slot/javascript.md, static/usage/v7/select/label-slot/react.md, static/usage/v7/select/label-slot/vue.md, static/usage/v7/select/no-visible-label/angular.md, static/usage/v7/select/no-visible-label/demo.html, static/usage/v7/select/no-visible-label/index.md, static/usage/v7/select/no-visible-label/javascript.md, static/usage/v7/select/no-visible-label/react.md, static/usage/v7/select/no-visible-label/vue.md
Docs for feature https://github.com/ionic-team/ionic-framework/pull/27545
This creates a "Labels" section that covers 3 topics:
1. Label placement (with label prop)
2. Label slot
3. aria-label
Topic 1 already has a playground. I created new playgrounds for Topics 2 and 3 following what was done in https://github.com/ionic-team/ionic-docs/pull/2955
Preview: https://ionic-docs-git-3532-docs-ionic1.vercel.app/docs/api/select#labels
I added a dev build to the label slot playground, so the iframe should work. However, the StackBlitz playgrounds will load latest (though you could manually install the dev build in StackBlitz). Dev build: 7.0.7-dev.11684935803.1436320b
=> docs(select): add label slot and aria label playgrounds

docs/deployment/progressive-web-app.md
The PWA deployment index [here](https://ionicframework.com/docs/deployment/progressive-web-app) already has links to guides for all three frameworks, but the text only lists Angular and React.
Essentially the same as https://github.com/ionic-team/ionic-docs/pull/1776, but the link and logo asset had already been added at some point; only the text needed updating. Co-author credit has been given.
=> docs(PWAs): add Vue to list of PWA deployment guides

docs/angular/navigation.md, versioned_docs/version-v5/angular/navigation.md, versioned_docs/version-v6/angular/navigation.md
Relative routing in Angular is supported in Ionic Framework: https://github.com/ionic-team/ionic-framework/commit/d9a7c63
This PR is in favor of: https://github.com/ionic-team/ionic-docs/pull/613
=> docs(angular): relative routing is supported

docs/angular/testing.md, versioned_docs/version-v6/angular/testing.md
Based on feedback when updating the starters: https://github.com/ionic-team/starters/pull/1785#discussion_r1210758452
Updates the code snippets for Ionic v6 and v7 docs to align with our conventions (and Angular's) for component testing.
=> docs(angular): update component testing code snippets

docs/techniques/security.md
Updates the security guide to include information about content security policies and how to assign the nonce value for Ionic web component projects.
Includes additional information for Angular 16 projects.
Preview link: https://ionic-docs-git-sp-csp-nonce-ionic1.vercel.app/docs/techniques/security#content-security-policies-csp
=> docs(security): content security policies

docs/vue/lifecycle.md
Adds a new line before the table to allow the Markdown to render properly.
=> docs(vue): fix lifecycle table formatting

static/usage/v6/infinite-scroll/basic/vue.md, static/usage/v6/infinite-scroll/custom-infinite-scroll-content/vue.md, static/usage/v6/infinite-scroll/infinite-scroll-content/vue.md, static/usage/v7/infinite-scroll/basic/vue.md, static/usage/v7/infinite-scroll/custom-infinite-scroll-content/vue.md, static/usage/v7/infinite-scroll/infinite-scroll-content/vue.md
Issue URL: resolves #2978 
Infinite scroll docs are using the wrong event on Vue: `IonInfiniteCustomEvent`
Infinite scroll docs are using the wrong event on Vue: `InfiniteScrollCustomEvent`
N/A
=> docs(infinite-scroll): use the correct custom event

docs/api/select.md, static/usage/v7/select/customization/custom-toggle-icons/angular.md, static/usage/v7/select/customization/custom-toggle-icons/demo.html, static/usage/v7/select/customization/custom-toggle-icons/index.md, static/usage/v7/select/customization/custom-toggle-icons/javascript.md, static/usage/v7/select/customization/custom-toggle-icons/react.md, static/usage/v7/select/customization/custom-toggle-icons/vue.md, static/usage/v7/select/customization/icon-flip-behavior/angular/example_component_css.md, static/usage/v7/select/customization/icon-flip-behavior/angular/example_component_html.md, static/usage/v7/select/customization/icon-flip-behavior/angular/example_component_ts.md, static/usage/v7/select/customization/icon-flip-behavior/demo.html, static/usage/v7/select/customization/icon-flip-behavior/index.md, static/usage/v7/select/customization/icon-flip-behavior/javascript.md, static/usage/v7/select/customization/icon-flip-behavior/react/main_css.md, static/usage/v7/select/customization/icon-flip-behavior/react/main_tsx.md, static/usage/v7/select/customization/icon-flip-behavior/vue.md
Adds two playgrounds:
- Usage for the new `toggleIcon` and `toggleIconWhenOpen` props added in https://github.com/ionic-team/ionic-framework/pull/27648
- Example CSS for customizing icon flip behavior, in lieu of a new prop as detailed [here](https://github.com/ionic-team/ionic-framework-design-documents/blob/main/projects/ionic-framework/components/select/0003-custom-icon-on-open.md#modifying-flip-behavior)
Dev build for testing: `7.0.15-dev.11687278023.161b97d8` (note that you'll need to add this to see the custom icons in the playground iframes)
Shortcut: https://ionic-docs-git-fw-2134-ionic1.vercel.app/docs/api/select#custom-toggle-icons
=> docs(select): add playgrounds for toggle icon customization

static/usage/v7/input/mask/index.md, static/usage/v7/input/mask/react.md
Maskito official launched with v1 today 🎉 . This PR updates the dependencies for the component playground examples.
=> chore: upgrade maskito dependencies to v1

src/components/global/Playground/index.tsx, src/components/global/PlaygroundTabs/index.tsx
Issue URL: resolves #2999 
The files tab section will render a scroll to the right button when there are multiple files that go off the container. However, if the right button is displayed and the user navigates to a different framework with a short list, then the right arrow is still showing.
Angular
React
The arrow only displays when there are multiples files that go off the container.
Angular
React
N/A
=> fix(playground-tabs): show arrows on long list

static/usage/v7/input/mask/angular/example_component_ts.md, static/usage/v7/input/mask/demo.html, static/usage/v7/input/mask/javascript/index_html.md, static/usage/v7/input/mask/react.md, static/usage/v7/input/mask/vue.md
Updates the card input masking example to align with the mask provided from Maskito: https://tinkoff.github.io/maskito/recipes/card
=> docs(maskito): update credit card mask format

.github/workflows/CI.yml, versioned_docs/version-v5/api/item.md, versioned_docs/version-v5/native/background-fetch.md, versioned_docs/version-v5/native/bluetooth-serial.md, versioned_docs/version-v5/native/document-scanner.md, versioned_docs/version-v5/native/firebase-vision.md, versioned_docs/version-v5/native/google-analytics.md
Enables an additional step in CI that validates there is no diff with the current working branch. This step runs after lint is ran (which includes prettier formatting).
With this step enabled, CI should fail when prettier changes have not been committed. 
This PR has additional diffs due to some weird inconsistencies with every-other-run with prettier. To avoid these issues, I adjusted the code block formatting to get consistent output. 
Example of failing diff: https://github.com/ionic-team/ionic-docs/actions/runs/5127696576/jobs/9223618711
=> chore(ci): check for diff after running prettier

docs/api/button.md, docs/reference/glossary.md, static/usage/v7/button/text-wrapping/angular.md, static/usage/v7/button/text-wrapping/demo.html, static/usage/v7/button/text-wrapping/index.md, static/usage/v7/button/text-wrapping/javascript.md, static/usage/v7/button/text-wrapping/react.md, static/usage/v7/button/text-wrapping/vue.md
- adds accessibility section to the `button` API docs with a text wrapping demo 
- adds accessibility section to the glossary documentation for what it is
The demo will look off until PR https://github.com/ionic-team/ionic-framework/pull/27547 is merged and 7.2 is released because the `min-height` and `padding` aren't changed.
Button preview: https://ionic-docs-git-fw-1808-a11y-ionic1.vercel.app/docs/api/button#accessibility
Glossary preview: https://ionic-docs-git-fw-1808-a11y-ionic1.vercel.app/docs/reference/glossary#a11y
=> docs(button): include accessibility section with best practices for text wrapping

docs/vue/quickstart.md
`npm run build` is failing. This is because the build script is using vue-tsc.
```
6:48:09 PM: $ yarn build
6:48:09 PM: yarn run v1.22.19
6:48:09 PM: $ vue-tsc && vite build
6:48:09 PM: node:internal/modules/cjs/loader:1078
6:48:09 PM:   throw err;
6:48:09 PM:   ^
6:48:09 PM: Error: Cannot find module 'typescript/package.json'
6:48:09 PM: Require stack:
6:48:09 PM: - /opt/build/repo/node_modules/vue-tsc/bin/vue-tsc.js
6:48:09 PM:     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
6:48:09 PM:     at Module._load (node:internal/modules/cjs/loader:920:27)
6:48:09 PM:     at Module.require (node:internal/modules/cjs/loader:1141:19)
6:48:09 PM:     at require (node:internal/modules/cjs/helpers:110:18)
6:48:09 PM:     at Object.<anonymous> …
```
=> docs(vue): Improve documentation for removing Typescript in v7

renovate.json
Enables the Renovate bot for managing the dependencies used by the component playground stackblitz project templates.
This PR is in favor of: https://github.com/ionic-team/ionic-docs/pull/3017
=> chore: enable renovate for component playground deps

docs/api/modal.md
There was some confusion around swipe gestures + modals on https://github.com/ionic-team/ionic-framework/issues/27753. Developer thought the swipe gesture applied to all modals, but it only applies to card and sheet modals.
=> docs(modal): clarify swipe to close section

docs/react/navigation.md
As noted in https://github.com/ionic-team/ionic-framework/issues/27705, it turns out that IonTabs in Ionic React automatically renders IonPage for you, so adding duplicate IonPage instances can cause rendering issues. This behavior is not aligned with Vue, so we should look into making this consistent in the future. For now, I've updated the docs to make this clear.
=> docs(react): clarify IonTabs behavior with IonPage

static/usage/v7/animations/basic/angular/example_component_html.md, static/usage/v7/animations/basic/javascript.md, static/usage/v7/animations/basic/react.md, static/usage/v7/animations/basic/vue.md, static/usage/v7/animations/chain/angular/example_component_html.md, static/usage/v7/animations/chain/javascript.md, static/usage/v7/animations/chain/react.md, static/usage/v7/animations/chain/vue.md, static/usage/v7/animations/group/angular/example_component_html.md, static/usage/v7/animations/group/javascript.md, static/usage/v7/animations/group/react.md, static/usage/v7/animations/group/vue.md
While implementing https://github.com/ionic-team/ionic-docs/pull/3035 I noticed in the other examples the `id` was defined on the buttons for the Angular, Javascript, React, and Vue examples. These do not need an `id` since they call click events directly, unlike the demo file.
=> style(animations): buttons in StackBlitz demos do not need id

renovate.json
Based on: https://github.com/ionic-team/ionic-docs/issues/3029, Renovate is still detecting `package.json` files at the root and within the docusaurus plugin. 
This PR limits the `includePaths` to only the Stackblitz directories.
Additionally this PR tries to limit the allowed version bumps for the v6 folder paths to not attempt to bump to Ionic v7.
=> chore(renovate): limit include paths

docs/utilities/animations.md, static/usage/v7/animations/before-and-after-hooks/angular/example_component_html.md, static/usage/v7/animations/before-and-after-hooks/angular/example_component_ts.md, static/usage/v7/animations/before-and-after-hooks/demo.html, static/usage/v7/animations/before-and-after-hooks/index.md, static/usage/v7/animations/before-and-after-hooks/javascript.md, static/usage/v7/animations/before-and-after-hooks/react.md, static/usage/v7/animations/before-and-after-hooks/vue.md
This is an alternative implementation of https://github.com/ionic-team/ionic-docs/pull/1702. It replaces the "Before and After Hooks" samples with a playground. 
I copied the existing animation playgrounds including the "play", "pause" and "stop" button (see https://github.com/ionic-team/ionic-docs/pull/3026). I changed the styles from the existing docs to use a `filter` and `box-shadow` instead of opacity, making it easier to see the styles on dark mode. 
:warning: Give co-author credit to [dillionmegida](https://github.com/dillionmegida) :warning:
Preview: https://ionic-docs-git-fw-3378-ionic1.vercel.app/docs/utilities/animations#before-and-after-hooks
=> docs(animations): add playground for before and after hooks

docs/utilities/animations.md, static/usage/v7/animations/preference-based/angular/example_component_css.md, static/usage/v7/animations/preference-based/angular/example_component_html.md, static/usage/v7/animations/preference-based/angular/example_component_ts.md, static/usage/v7/animations/preference-based/demo.html, static/usage/v7/animations/preference-based/index.md, static/usage/v7/animations/preference-based/javascript.md, static/usage/v7/animations/preference-based/react/main_css.md, static/usage/v7/animations/preference-based/react/main_tsx.md, static/usage/v7/animations/preference-based/vue.md
This is an alternative implementation of https://github.com/ionic-team/ionic-docs/pull/1712 which replaces the "Preference-Based Animations" samples with a playground. The playground contains Vanilla JS, Angular, React, and Vue code samples, and it also links out to StackBlitz.
[Demo URL](https://ionic-docs-git-fw-3376-ionic1.vercel.app/docs/utilities/animations#preference-based-animations)
---
Change the theme through your OS's system settings to view the differences or change the theme via the site.
=> docs(animations): add playground for preference based

docs/api/item-sliding.md
There was confusion on https://github.com/ionic-team/ionic-framework/issues/27794 about which element is used as the reference for "full width". An expandable option will expand to cover the full width of the parent `ion-item` when swiped, so I made that clear in the docs.
=> docs(item-sliding): clarify expandable behavior

docs/api/menu.md, static/code/stackblitz/v7/html/index.ts, static/usage/v7/menu/multiple/angular/example_component_html.md, static/usage/v7/menu/multiple/angular/example_component_ts.md, static/usage/v7/menu/multiple/demo.html, static/usage/v7/menu/multiple/index.md, static/usage/v7/menu/multiple/javascript.md, static/usage/v7/menu/multiple/react.md, static/usage/v7/menu/multiple/vue.md, static/usage/v7/menu/sides/angular.md, static/usage/v7/menu/sides/demo.html, static/usage/v7/menu/sides/index.md, static/usage/v7/menu/sides/javascript.md, static/usage/v7/menu/sides/react.md, static/usage/v7/menu/sides/vue.md
While working on the [menu playwright migration](https://github.com/ionic-team/ionic-framework/pull/26187) I noticed there were no usage examples in the docs on how to call `open` on a menu when you have multiple menus.
This PR adds the following two playgrounds:
- Menu Sides ([Preview](https://ionic-docs-git-docs-menu-sides-and-multiple-ionic1.vercel.app/docs/api/menu#menu-sides))
- Multiple Menus ([Preview](https://ionic-docs-git-docs-menu-sides-and-multiple-ionic1.vercel.app/docs/api/menu#multiple-menus))
The first one just shows an example of how to change the side to `end` which is more of a buildup to the next one. Multiple menus has two menus on the `start` side and one on the `end` side to show how you can use `MenuController` to open a menu by `id` or `side`. 
_The multiple menus …
=> docs(menu): add playgrounds for menu sides and multiple menus

scripts/i18n.sh
The JP docs are currently on the v6 page, which is not the latest version. This PR updates our docs scripts to have the JP docs point to v7.
See: https://github.com/ionic-team/ionic-docs/issues/3050
=> chore: JP docs point to v7

scripts/i18n.sh
The latest version keyword in docusaurus is "current" not "version-v7".
See https://github.com/ionic-team/ionic-docs/issues/3050
=> chore: use correct name for JP docs

docs/api/action-sheet.md, docs/api/alert.md, docs/api/toast.md
This PR adds the following to different API documentation:
[Action Sheet](https://ionic-docs-git-fw-4240-docs-ionic1.vercel.app/docs/api/action-sheet#accessibility):
- Puts all of the `Accessibility` text under subheading `Screen Readers` to match `Toast`
- Adds a section under `Accessibility` that mentions buttons with only an icon should pass an `aria-label` property to `htmlAttributes` in order to be described by screen readers
- Adds code examples for passing to `htmlAttributes` both on the Action Sheet and its buttons
- Adds the `htmlAttributes` type to the `ActionSheetButton` interface
- Adds the `id` type to the `ActionSheetButton` interface - I noticed this missing but it was actually [added in v6](https://github.com/ionic-team/ionic-framework/commit/9e24a0b49357a3a39ca89f026ff2327 …
=> docs(api): add accessibility section for new htmlAttributes property

docs/react/lifecycle.md
resolves #1949
The dependencies argument is not documented which makes it hard to determine how to provide reactive dependencies. This PR documents how the argument works and links out to the React docs for more info.
=> docs(react): document lifecycle hook dependencies arg

docs/developing/config/global/index.md, docs/developing/config/per-component/index.md, docs/developing/config/per-platform-fallback/index.md, docs/developing/config/per-platform-overrides/index.md, docs/developing/config/per-platform/index.md, docs/native-setup.md, versioned_docs/version-v6/developing/config/global/index.md, versioned_docs/version-v6/developing/config/per-component/index.md, versioned_docs/version-v6/developing/config/per-platform-fallback/index.md, versioned_docs/version-v6/developing/config/per-platform-overrides/index.md, versioned_docs/version-v6/developing/config/per-platform/index.md, versioned_docs/version-v6/native-setup.md
I've been doing research around preserving the active framework for Playground tabs. As part of that research, I discovered that Docusaurus tabs already have this functionality [[Docusaurus docs](https://docusaurus.io/docs/markdown-features/tabs#syncing-tab-choices)] and we are already using it in the Ionic docs. Any Docusaurus tab groups with the same `groupId` will sync to the same active tab.
During my research, I also noticed a few places where we aren't consistent with using the same `groupId` for tab groups with the same options. This PR tidies those up.
All Docusaurus tab `groupId`s should now be one of the following:
* 'framework': javascript, angular, vue, react, stencil
* 'runtime': capacitor, cordova, enterprise
Example: 
If you change tabs on [this page in the current …
=> fix(): consolidate docusaurus tab groupids

docs/vue/your-first-app/2-taking-photos.md
Avoid :
Type '{ filepath: string; webviewPath?: string | undefined; }' is not assignable to type 'string | number | symbol | undefined'.ts(2322) runtime-core.d.ts(914, 5): The expected type comes from property 'key' which is declared here on type '{ readonly push?: string | undefined; readonly modelValue?: string | number | boolean | undefined; readonly offset?: string | undefined; readonly offsetLg?: string | undefined; ... 32 more ...; style?: unknown; } & Record<...>' (property) key?: string | number | symbol | undefined
=> fix(vue): fix bug with key type

sidebars.js, versioned_sidebars/version-v5-sidebars.json, versioned_sidebars/version-v6-sidebars.json
Put accordion before action sheet and icons before infinite scroll.
See https://github.com/ionic-team/ionic-docs/pull/3082 for similar change for Japanese docs.
=> fix(): alphabetize sidebar

sidebars.js, versioned_sidebars/version-v5-sidebars.json, versioned_sidebars/version-v6-sidebars.json
This is the same change as https://github.com/ionic-team/ionic-docs/pull/3081 but for the Japanese docs. This puts the components in the same order for the Japanese docs as for the English ones, for consistency sake.
(I figured that since this is outside the regular docs content, it might be nice to go ahead and update the Japanese branch to match.)
=> fix(): JP - alphabetize sidebar

sidebars.js, versioned_sidebars/version-v5-sidebars.json, versioned_sidebars/version-v6-sidebars.json
Reverts #3081 because the [Vercel build of `main`](https://vercel.com/ionic/ionic-docs/AFayMzgdWiw3CFP6t5AsqDtMAG9k) was failing for unclear reasons.
=> Revert "fix(): alphabetize sidebar (#3081)"

docs/api/picker.md
There is no description of how to set the value of a picker.
Readers can find this description in the documentation.
=> docs(picker): describe how to set the initial value of a picker column

docs/api/datetime.md
Related feature PR: https://github.com/ionic-team/ionic-framework/pull/27806
=> docs(datetime): add best practices for setting value async

.github/CODEOWNERS
I'll start with these for now and can adjust to more or less once I get a feel for how much volume this is. My sense is that on average, docs PRs take less time to review than framework PRs.
/_templates/ playground generator
/docs/api/ component docs
/src/ code for playground component & other components
/static/usage/ playgrounds
=> chore(CODEOWNERS): create codeowners file and add me

_templates/playground/new/angular.md.ejs.t, _templates/playground/new/angular_example_component_css.md.ejs.t, _templates/playground/new/angular_example_component_ts.md.ejs.t, _templates/playground/new/demo.html.ejs.t, _templates/playground/new/index.js, _templates/playground/new/index.md.ejs.t, _templates/playground/new/javascript.md.ejs.t, _templates/playground/new/react.md.ejs.t, _templates/playground/new/react_main_css.md.ejs.t, _templates/playground/new/vue.md.ejs.t
See FW-4717 and [design doc update](https://github.com/ionic-team/ionic-framework-design-documents/pull/149) for extra context.
Previously, you couldn't create a playground for animations, gestures, etc., without using some workarounds. Now the prompts ask if you're creating a playground for a component or not and adjust the other prompt questions accordingly.
⚠️ I also did a little refactoring & renaming to make the code more clear. Walking through the commits one-by-one may help for review.
I included an `ion-card` in the templates, since the animation playgrounds tend to have those.
=> feat(generation): generate playgrounds for guides

plugins/docusaurus-plugin-ionic-component-api/index.js
This is a proposed change to help reduce confusion with the type signature for the `color` attribute for certain components. Ionic Framework added a type union for `string` and `Record` to resolve intellisense not detecting the pre-defined colors when using a type union with `string`. 
This PR formats and removes that "type hack" from the generated docs, as users only care about the pre-defined colors and that they can use any valid `string`.
Output before:
```
"danger" ｜ "dark" ｜ "light" ｜ "medium" ｜ "primary" ｜ "secondary" ｜ "success" ｜ "tertiary" ｜ "warning" ｜ string & Record<never, never> ｜ undefined
```
Output after:
```
"danger" ｜ "dark" ｜ "light" ｜ "medium" ｜ "primary" ｜ "secondary" ｜ "success" ｜ "tertiary" ｜ "warning" ｜ string ｜ undefined
```
=> chore: format generated property types

static/code/stackblitz/v7/angular/package.json, static/code/stackblitz/v7/html/package.json, static/code/stackblitz/v7/react/package.json, static/code/stackblitz/v7/vue/package.json
Forgot to revert the packages after https://github.com/ionic-team/ionic-docs/pull/3097
=> chore(angular, html, react, vue): revert package versions on stackblitz

docs/api/input.md, static/usage/v7/input/counter-alignment/angular.md, static/usage/v7/input/counter-alignment/demo.html, static/usage/v7/input/counter-alignment/index.md, static/usage/v7/input/counter-alignment/javascript.md, static/usage/v7/input/counter-alignment/react.md, static/usage/v7/input/counter-alignment/vue.md
Resolves https://github.com/ionic-team/ionic-docs/issues/3073
[Vercel preview](https://ionic-docs-git-fw-4917-ionic1.vercel.app/docs/api/input#input-counter)
Updates the docs for input to indicate:
1. That `counter` and `counterFormatter` are deprecated on `ion-item` and should instead be used on `ion-input`
2. That it's not recommended to put an `ion-input` with a counter inside an `ion-item`
3. How to align a counter input with `ion-item`s
=> docs(input): notes about appropriate uses of counter

static/usage/v6/nav/nav-link/vue/example_vue.md, static/usage/v6/nav/nav-link/vue/page_one_vue.md, static/usage/v6/nav/nav-link/vue/page_two_vue.md, static/usage/v7/nav/nav-link/vue/example_vue.md, static/usage/v7/nav/nav-link/vue/page_one_vue.md, static/usage/v7/nav/nav-link/vue/page_two_vue.md
In the Vue `ion-nav-link` examples, the examples will log a warning for property bindings to the components:
> [Vue warn]: Vue received a Component which was made a reactive object. This can lead to unnecessary performance overhead, and should be avoided by marking the component with `markRaw` or using `shallowRef` instead of `ref`. 
This is a result of passing a `Component` instance to a binding like `:component="component"` or `:root="component"`. 
As a result, we have marked those bindings explicitly with [`markRaw`](https://vuejs.org/api/reactivity-advanced.html#markraw), which opts them out of vue reactivity and resolves the warning.
This PR is in favor of: https://github.com/ionic-team/ionic-docs/pull/3076, https://github.com/ionic-team/ionic-docs/pull/3077.
Co-authored-by credit …
=> fix(nav-link): opt-out of vue reactivity for component binding

docs/react/navigation.md
Unfortunately, the React training team didn't implement redirects for their old documentation (possibly due to the big change from 5-6?). Instead, all links point to the same landing page:
This PR updates the links to the **relevant** (i.e., v5) React Router documentation
Resolves #3114
=> chore(react): update react router links

static/code/stackblitz/v7/react/package-lock.json, static/code/stackblitz/v7/react/package.json, static/code/stackblitz/v7/vue/package-lock.json, static/code/stackblitz/v7/vue/package.json
React/Vue playgrounds are pulling in Ionic 7.0.10. We are up to 7.4.0 now, so these should be updated.
=> chore: update v7 playground dependencies for React and Vue

renovate.json
Renovate is currently configured incorrectly to detect required dependency updates in the Stackblitz template directories. 
This PR updates the configuration to detect dependencies in the Stackblitz directories. It also pins the `react-router` and `react-router-dom` dependencies to v5. 
Example fork with these configurations enabled: https://github.com/sean-perkins/ionic-docs/issues/1
=> chore(ci): renovate configurations for stackblitz templates

docs/angular/build-options.md, docs/angular/overview.md, sidebars.js
This PR shows how to use Ionic UI standalone components.
Preview: https://ionic-docs-git-4612-docs-ionic1.vercel.app/docs/angular/build-options
=> docs(angular): add standalone documentation

src/components/global/Playground/index.tsx, src/components/global/Playground/stackblitz.utils.ts, static/usage/v6/modal/styling/animations/javascript/index_html.md, static/usage/v7/input/mask/javascript/index_html.md, static/usage/v7/modal/styling/animations/javascript/index_html.md, static/usage/v7/theming/automatic-dark-mode/javascript.md, static/usage/v7/theming/manual-dark-mode/javascript.md
When passing a `files` object to a Javascript playground, e.g.
```jsx
<Playground
version="7"
code={{
javascript: {
files: {
'index.html': javascript_index_html,
'theme/variables.css': variables_css,
},
},
...
}}
...
>
```
you currently need to include the full HTML (e.g. the `head`) in the playground's markdown file that becomes index.html. This means that the code sample displayed also has all the extra stuff in it instead of being streamlined like it is when there's only the single file for a Javascript playground.
This PR updates the playground code so that you can simplify the file and what is displayed.
Explanation of change in Playground/index.tsx:
If we pass `codeBlock` through when there are multiple files for a framework just like we've been doing when there's a single file, …
=> fix(playground): better handle multiple files for Javascript

static/code/stackblitz/v6/react/index.html, static/code/stackblitz/v7/react/index.html
The React stackblitz examples have a misconfiguration in their template files for the `index.html`. This results in certain examples rendering incorrectly, such as the v7 button playground examples. The button will grow to the entire container height: https://stackblitz.com/edit/nia7fe?file=src%2Fmain.tsx
This PR updates the template file for both v6 and v7.
=> fix(playground): react stackbiltz template files

docs/api/item.md, src/components/global/BestPracticeFigure/index.tsx
The current naming seems to cause issues with CSpell (https://github.com/ionic-team/ionic-docs/pull/3069), so the team opted to rename the `dont*` props to `doNot*`.
=> chore: rename dont props to doNot

docs/layout/dynamic-font-scaling.md
Corrects the name of the Comic Sans font, in case people copy-paste the code directly and get confused when it doesn't work.
=> docs(dynamic-font): fix font family name

docs/angular/build-options.md
Amanda noted there is no usage info for devs with an NgModule-architecture application, just a migration guide. This PR adds usage examples.
Preview: https://ionic-docs-git-standalone-usage-modules-ionic1.vercel.app/docs/angular/build-options#usage-with-ngmodule-based-applications
=> docs: add modules architecture usage

docs/angular/platform.md, docs/angular/slides.md, docs/developing/config.md, docs/developing/config/global/index.md, docs/developing/config/per-component/index.md, docs/developing/config/per-platform-fallback/index.md, docs/developing/config/per-platform-overrides/index.md, docs/developing/config/per-platform/index.md, docs/developing/hardware-back-button.md, docs/developing/keyboard.md, docs/techniques/security.md, docs/utilities/animations.md, docs/utilities/gestures.md
In addition to https://github.com/ionic-team/ionic-docs/pull/3115, I updated all the non-Playground code blocks to add Angular standalone examples.
Preview: https://ionic-docs-git-standalone-examples-ionic1.vercel.app/docs
Example: https://ionic-docs-git-standalone-examples-ionic1.vercel.app/docs/developing/config
=> docs(angular): add angular standalone syntax to non-playground examples

docs/angular/build-options.md
Screen readers currently announce the sentence in three parts. Removing the formatting here causes a consistent announcement of the sentence.
=> fix(angular): standalone guide formatting

docs/api/select.md
- Reorders the "Multiple selection" examples to be located after "Single selection"
- Adds "Alert" interface section that re-uses the existing playground example for "Single selection"
=> docs(select): reorder examples, add alert playground

docs/angular/build-options.md
The `Standalone-based Applications` section has the added line in a diff format. This PR makes it consistent between both modes by adding it to `NgModule-based Applications`.
[Page](https://ionic-docs-git-code-format-ionic1.vercel.app/docs/angular/build-options#ngmodule-based-applications)
=> docs(angular): include add diff sign

docs/api/select.md
This PR introduces documentation on the expected keyboard interactions when interacting with the `ion-select` element. 
Preview: https://ionic-docs-git-sp-fw-5130-ionic1.vercel.app/docs/api/select#accessibility
=> docs(select): keyboard navigation

.github/CODEOWNERS
Right now Renovatebot PRs are not assigned to anyone for review. This PR makes it so the Ionic Framework team is a codeowner for any `package.json` change to our StackBlitz templates.
=> chore: team is requested for review for renovatebot prs

src/components/global/Playground/index.tsx
When the framework and/or mode are changed on any playground, the new selection is stored and persisted. This applies both to all other playgrounds currently on the page, and any future page loads.
In the design doc, it was mentioned [here](https://github.com/ionic-team/ionic-framework-design-documents/blob/main/projects/ionic-framework-docs/playground/0004-framework-preference.md#synchronization) that we should not immediately update the mode for any playgrounds that haven't been scrolled to yet, for performance reasons. I elected not to do this because it doesn't seem to confer any benefit -- the iframes are not rendered at all until the playground is scrolled to, even if the mode is changed ahead of time.
There also shouldn't be any performance issues with switching modes on …
=> feat(playground): persist framework and mode selection

src/components/global/Playground/index.tsx
We've found that switching the mode for all playgrounds on the page at once can cause performance issues for some devices. Namely, if many, many playgrounds are being toggled (such as on the [Datetime page](https://ionicframework.com/docs/api/datetime)), the browser may run out of memory and forcibly refresh the page.
Instead of updating all playgrounds at once, we now only update the ones currently on the screen, and wait for others to be scrolled on-screen before updating them as well.
Slack thread for context: https://ionicteam.slack.com/archives/C02U5GFFXED/p1696944131395219
=> fix(playground): wait until playground is in view before loading stored framework/mode

docs/api/menu.md, static/usage/v7/menu/multiple/angular/example_component_ts.md, static/usage/v7/menu/multiple/demo.html, static/usage/v7/menu/multiple/javascript.md, static/usage/v7/menu/multiple/react.md, static/usage/v7/menu/multiple/vue.md
As part of https://github.com/ionic-team/ionic-framework/pull/28269, we are fixing the menu automatic disabling behavior. This PR provides guidance on how to refer to menus when there are multiple menus on the same side present in the DOM.
=> docs(menu): clarify multiple side menu behavior

docs/angular/build-options.md
While going through migrating an NgModules app to use Ionic standalone components I got confused because the previous section mentioned adding the imports in the `@Component` and not the `@NgModule` so I have added an example to help clarify.
=> docs(angular): add more info on migrating to standalone

docs/developing/keyboard.md, static/usage/v7/keyboard/enterkeyhint/angular.md, static/usage/v7/keyboard/enterkeyhint/demo.html, static/usage/v7/keyboard/enterkeyhint/index.md, static/usage/v7/keyboard/enterkeyhint/javascript.md, static/usage/v7/keyboard/enterkeyhint/react.md, static/usage/v7/keyboard/enterkeyhint/vue.md, static/usage/v7/keyboard/inputmode/angular.md, static/usage/v7/keyboard/inputmode/demo.html, static/usage/v7/keyboard/inputmode/index.md, static/usage/v7/keyboard/inputmode/javascript.md, static/usage/v7/keyboard/inputmode/react.md, static/usage/v7/keyboard/inputmode/vue.md
https://ionicframework.com/docs/developing/keyboard The two code demos on this page had several problems:
1. The demos were shown using Codepens instead of proper playgrounds.
2. The inputs were using the legacy form control syntax.
3. The code shown didn't match the Codepens.
This PR resolves all three.
Shortcut: https://ionic-docs-git-keyboard-playgrounds-ionic1.vercel.app/docs/developing/keyboard
=> feat(keyboard): replace Codepens with playgrounds using modern syntax

docs/techniques/security.md
I've seen some confusion in threads such as https://github.com/ionic-team/ionic-framework/issues/28365 as to when to use IonicSafeString, so I wanted to clarify this on the docs.
=> docs: clarify IonicSafeString usage

.github/CODEOWNERS
The Framework team should be automatically assigned to new PRs.
=> chore: add framework team as code owners

static/usage/v6/textarea/autogrow/demo.html, static/usage/v7/textarea/autogrow/demo.html
The `.container` wrapper that we render around the autogrow playground example, caused the contents to be clipped and not scrollable when large amounts of text were rendered. 
This PR changes the display style of the `.container` element for these specific examples to be `display: block`. This allows the contents to be scrolled to when working with large amounts of text. 
As a result of this, the textarea container is not optically centered to the playground frame, but for autogrow I do not believe this matters for the example.
=> fix(textarea): autogrow playground can scroll to the top of contents

docs/angular/your-first-app.md, docs/react/your-first-app.md, docs/vue/your-first-app.md
After talking with Liam, looks like defineCustomElements should be called before and not after the app was created/rendered/bootstrapped.
I've tested on angular (ngModules and standalone), vue and react and pwa-elements is working fine.
=> docs: change comments for pwa-elements defineCustomElements

docs/angular/build-options.md
In https://github.com/ionic-team/ionic-framework/issues/28445 it was noted that having to call `addIcons` in every Angular component that uses icons is tedious. I think it's worth informing developers that they can register all icons up front in `app.component.ts`. For icons that use the same handful of icons this can be a big time saver with minimal performance overhead.
=> docs(angular): clarify addIcons usage

docs/angular/build-options.md
This PR publicizes our experimental migration utility for migration to Ionic Angular standalone components.
=> docs(angular): add note on migration utility

docs/react/testing/introduction.md
Adds a mention and link to the Vitest docs for unit testing with React.
=> docs(react): link to vitest docs

renovate.json
Configures renovate to use `chore:` for commit messages.
https://docs.renovatebot.com/semantic-commits/#changing-the-semantic-commit-type
=> chore(renovate): use chore subject line for prs

renovate.json
I couldn't find a way to test this but I looked through the docs and issues and this seems like the right config. Let me know if I am missing something!
=> chore(renovate): update config to ignore typescript updates in react v6

static/usage/v7/toggle/label-placement/index.md
While testing out a PR I noticed that [Toggle's Label Placement demo](https://ionicframework.com/docs/api/toggle#label-placement) is too short to display all of the toggles on `ios`. I increased the height of the container to fit all of them.
Preview: https://ionic-docs-git-docs-fix-toggle-playgrounds-ionic1.vercel.app/docs/api/toggle#label-placement
| Before | After |
| ---| ---|
| ![before](https://github.com/ionic-team/ionic-docs/assets/6577830/427badc7-3f4a-4082-8358-054497d0bbe8) | ![after](https://github.com/ionic-team/ionic-docs/assets/6577830/a751f5e2-73ff-448b-80c8-913a8aec06d3) |
=> docs(toggle): update playground to have larger height

docs/api/radio.md, docs/api/select.md, static/usage/v7/radio/using-comparewith/angular/example_component_html.md, static/usage/v7/radio/using-comparewith/angular/example_component_ts.md, static/usage/v7/radio/using-comparewith/demo.html, static/usage/v7/radio/using-comparewith/index.md, static/usage/v7/radio/using-comparewith/javascript.md, static/usage/v7/radio/using-comparewith/react.md, static/usage/v7/radio/using-comparewith/vue.md, static/usage/v7/select/objects-as-values/using-comparewith/javascript.md
This accompanies https://github.com/ionic-team/ionic-framework/pull/28452
Ionic Framework dev build for testing: `7.5.4-dev.11699037031.16f5cbc8`
Vercel link: https://ionic-docs-git-fw-728-ionic1.vercel.app/docs/api/radio#object-value-references
=> docs(radio): playground for compareWith

docs/api/reorder.md, static/usage/v7/reorder/updating-data/angular/example_component_html.md, static/usage/v7/reorder/updating-data/angular/example_component_ts.md, static/usage/v7/reorder/updating-data/react.md, static/usage/v7/reorder/updating-data/vue.md
When using reorder without a stable identity and having Ionic reorder DOM nodes, the result can be confusing where the state of the list seemingly resets to before the gesture started.
Regardless of the update approach taken, developers should be assigning a stable identity to their loop items. This will prevent the list state from being reset even if Ionic reorders the DOM nodes.
Related: https://github.com/ionic-team/ionic-framework/issues/28496
=> docs(reorder): assign stable identity to loop items

docs/angular/build-options.md
Updates the build options doc for Angular to recommend VSCode settings to avoid invalid import recommendations.
=> docs(angular): vscode settings for standalone usages

static/usage/v7/alert/presenting/controller/angular/example_component_ts.md, static/usage/v7/alert/presenting/controller/demo.html, static/usage/v7/alert/presenting/controller/javascript.md, static/usage/v7/alert/presenting/controller/react.md, static/usage/v7/alert/presenting/controller/vue.md, static/usage/v7/alert/presenting/isOpen/angular/example_component_html.md, static/usage/v7/alert/presenting/isOpen/angular/example_component_ts.md, static/usage/v7/alert/presenting/isOpen/demo.html, static/usage/v7/alert/presenting/isOpen/javascript.md, static/usage/v7/alert/presenting/isOpen/react.md, static/usage/v7/alert/presenting/isOpen/vue.md, static/usage/v7/alert/presenting/trigger/angular/example_component_html.md, static/usage/v7/alert/presenting/trigger/angular/example_component_ts.md, static/usage/v7/alert/presenting/trigger/demo.html, static/usage/v7/alert/presenting/trigger/javascript.md, static/usage/v7/alert/presenting/trigger/react.md, static/usage/v7/alert/presenting/trigger/vue.md
While reviewing the [Apple Design Resources for iOS 17](https://www.figma.com/community/file/1248375255495415511) I found that some of their component examples have valuable placeholder text that informs the developer/designer how to use the component.
I've updated the alert playground examples for `trigger`, `isOpen` and controller to use some of these content recommendations. 
Note: Sub header does not exist in the Apple Design Resources, so that text is improvised based on the surrounding text.
=> docs(alert): update content in playground examples

src/components/global/Playground/stackblitz.utils.ts, static/code/stackblitz/v6/angular/package.json, static/code/stackblitz/v7/angular/package.json
Fixes the generated playground examples to work with the new Angular 17 templates from Stackblitz.
=> fix(playground): support angular 17 template

renovate.json
Reverts ionic-team/ionic-docs#3231
As of https://github.com/ionic-team/ionic-docs/pull/3246, the Ionic React v6 playgrounds now use Vite, so we can safely use TypeScript 5.
=> chore(renovate): revert typescript ignore rule

docs/reference/support.md
This PR notes when Angular 17 is officially supported in Ionic 7.
=> docs(support): note angular 17 support

renovate.json
This PR updates renovate to match explicitly for the package names vs. matching based on a pattern.
Currently `@ionic/react-router` is not being upgraded for v7 since it matches "react-router" and that is set to a maximum version range of `^5.0.0`.
=> chore(renovate): match explicitly the react-router and react-router-dom

.github/workflows/CI.yml
Upgrades the CI workflow to run against Node v20. Additionally updates the checkout and setup-node actions to use the latest available versions.
=> chore(ci): run workflow against node v20

docs/api/toast.md, static/usage/v7/toast/swipe-gesture/angular.md, static/usage/v7/toast/swipe-gesture/demo.html, static/usage/v7/toast/swipe-gesture/index.md, static/usage/v7/toast/swipe-gesture/javascript.md, static/usage/v7/toast/swipe-gesture/react.md, static/usage/v7/toast/swipe-gesture/vue.md
This adds a playground for the new `swipeGesture` feature in IonToast. I opted to use `positionAnchor` and `position` so devs can see how `swipeGesture` is impacted by both of these APIs.
Ionic v7.6 dev build: `7.5.4-dev.11699895923.130c21aa`
Preview: https://ionic-docs-git-toast-swipe-ionic1.vercel.app/docs/api/toast#swipe-to-dismiss (You'll need to install the above dev build on the stackblitz demos for the feature to work since it has not been released yet)
=> docs(toast): add swipeGesture playground

renovate.json
The installed version of React on the docs is outdated. This can cause issues with other dependencies when the `package-lock.json` file is removed.
Example: https://github.com/ionic-team/ionic-docs/pull/3272#issuecomment-1831988786
A dependency we used dropped support for React 17 in a minor release. The package-lock ensured that an older version of the dep was installed (which did support React 17), but re-generating the package-lock results in the newer dep (which does not support React 18) getting installed.
Note: This won't actually do anything for now because we are using the latest version of React 17. Once we update to React 18 our installed version of react and react-dom will be kept up to date (up until v19 of react) by renovatebot.
=> chore(renovate): update react and react-dom

src/components/page/theming/_utils/color.ts
This PR fixes a miscalculation in the color generator resulting in an incorrect contrast color. 
For example, with a color of `#EF3442` the expected contrast is `#000000`. However the color generator is incorrectly recommending `#ffffff`. 
This PR updates the logic for how the contrast color is determined by calculating the contrast ratio for the current color against a white and black background. The variant with the highest contrast ratio will be used as the contrast. 
The calculation for the contrast ratio was sourced from: https://stackoverflow.com/a/9733420. The code was refactored to match the existing code style for representing the `rgb` color and using the available types. 
Quick preview: https://ionic-docs-git-sp-color-generator-ionic1.vercel.app/docs/theming/color-generator
=> fix(color-generator): contrast color calculation

docusaurus.config.js, package-lock.json, package.json
Issue URL: N/A
Google Tag Manager is being added through an internal package. This is no longer necessary as Docusaurus provides a plugin for this.
- Added Google Tag Manager through Docusaurus.
- Uninstalled the internal package.
N/A
=> chore(google-tag-manager): switch to Docusaurus preset

src/components/page/theming/ColorGenerator/index.tsx, src/components/page/theming/_utils/index.tsx
There are situations when pasting a value into the input for a color, that the generated value will not include the `#`. This PR accounts for that and consistently formats the value as a hex color. 
I also resolved a few places in local development where React was erroring out due to a missing `key` attribute.
=> fix(color-generator): consistently format value as hex color

src/components/page/theming/ColorGenerator/index.tsx
The secondary and tertiary colors are the same. The secondary color should be #3dc2ff to align with the starter apps: https://github.com/ionic-team/starters/blob/7273d04c7ba2eca71d7b96bdfa0240087fb1e49d/angular/base/src/theme/variables.scss#L15
Preview: https://ionic-docs-git-liamdebeasi-patch-2-ionic1.vercel.app/docs/theming/color-generator
=> fix(color-generator): generate correct secondary color

src/components/global/Playground/index.tsx, static/usage/v6/tabs/router/angular/app_module_ts.md, static/usage/v7/tabs/router/angular/app_module_ts.md
Resolves #3260
Playground examples with many files would result in an issue with Safari where the `outerText` of the parsed code block would only include whitespace, not the actual contents of the code. 
This PR updates that logic to clone the DOM node to a detached node that results in the `outerText` consistently being parsed with the actual text content & whitespace/line breaks.
While working on the tabs example I noticed that the mode replacement logic would not apply because the regular expression matches on `IonicModule.forRoot({})` not `IonicModule.forRoot()`. I've updated the v7 & v6 examples to use the correct content. 
To test this change, open the [Tabs docs](https://ionic-docs-git-sp-fw-5649-ionic1.vercel.app/docs/api/tabs) on Safari and attempt to open it in Stackblitz. You …
=> fix(playground): tabs stackblitz example loads in Safari

static/usage/v7/select/start-end-slots/demo.html
This code was added to get around a bug in `feature-7.6` which has since been fixed, so it isn't needed anymore.
=> chore(select): remove unneeded patch from start/end slots demo

docs/angular/build-options.md
Developers have noted that Ionic's standalone components do not work with Jest by default: https://github.com/ionic-team/ionic-framework/issues/28667
This is happening because Ionic's components are ES Modules which Jest does not support. Developers need to use `transformIgnorePatterns` to ensure the ES Modules are transpired to a format Jest can use.
=> docs(angular): note jest transformIgnorePatterns for es modules

docs/api/item.md, static/usage/v7/item/basic/angular.md, static/usage/v7/item/basic/demo.html, static/usage/v7/item/basic/javascript.md, static/usage/v7/item/basic/react.md, static/usage/v7/item/basic/vue.md, static/usage/v8/item/basic/angular.md, static/usage/v8/item/basic/demo.html, static/usage/v8/item/basic/javascript.md, static/usage/v8/item/basic/react.md, static/usage/v8/item/basic/vue.md, versioned_docs/version-v7/api/item.md
This is the same as https://github.com/ionic-team/ionic-docs/pull/3314, but it ports the changes to the v8 branch.
=> docs(item): clarify usage for text wrapping

docs/deployment/app-store.md
Updates App Store release build steps to include a tab for Capacitor.
`Co-authored-by: Matthew Harris <rtpharry@hotmail.com>`
=> docs(app-store): update release build to include capacitor steps

docs/troubleshooting/runtime.md, versioned_docs/version-v7/troubleshooting/native.md, versioned_docs/version-v7/troubleshooting/runtime.md
This is the same as https://github.com/ionic-team/ionic-docs/pull/3333, but targets the Ionic 8 docs.
=> docs: show how to account for this

versioned_docs/version-v5/api/popover.md
[There is some developer confusion](https://github.com/ionic-team/ionic-framework/issues/28741) about Ionic's popover not displaying in newer version of Chrome due to the new `popover` attribute. This PR documents the limitation in Ionic v5. I'll do this for v4 as well, but that's in a separate branch
Ionic v6 and v7 apps are not impacted.
=> docs(popover): warn about popover attribute on v5

src/demos/api/popover/index.html
[There is some developer confusion](https://github.com/ionic-team/ionic-framework/issues/28741) about Ionic's popover not displaying in newer version of Chrome due to the new `popover` attribute. This PR documents the limitation in Ionic v4.
Ionic v6 and v7 apps are not impacted.
Note that the main body of the documentation is generated via files from Ionic Framework. In order to update this, I'd need to publish a new version of Ionic v4. As a result, I decided to document this limitation inside of the popover demo as the demo is defined in this repo.
=> docs(popover): warn about popover attribute on v4

docs/api/refresher.md, static/usage/v7/refresher/custom-scroll-target/angular/example_component_css.md, static/usage/v7/refresher/custom-scroll-target/demo.html, static/usage/v7/refresher/custom-scroll-target/javascript.md, static/usage/v7/refresher/custom-scroll-target/react/main_css.md, static/usage/v7/refresher/custom-scroll-target/vue.md
There was some confusion over how to get the native iOS refresher to work in a virtual scroll container. Ionic adds special CSS to allow for the rubber band effect even the container does not need to scroll. Developers need to add this to their apps too.
=> docs(refresher): add rubber band effect for virtual scroll

docs/reference/browser-support.md, docs/reference/support.md
This PR adds the JS Framework and Browser/Platform support for Ionic 8 according to https://github.com/ionic-team/ionic-framework/blob/2c20a6bdb4449ee9a3ac7766e6673b8797c53bda/BREAKING.md
=> docs(support): add support for Ionic 8

docs/api/input.md, docs/components.md, docs/core-concepts/cross-platform.md, docs/react.md, docs/react/quickstart.md, docs/reference/browser-support.md, docs/vue/quickstart.md, docusaurus.config.js, scripts/data/meta-override.json
This is a companion PR to #3365. 
I didn't necessarily try to eliminate every single mention of desktop. My objective was to eliminate any impression that we support desktop apps and formats. These are all just proposals – some of these changes may require further discussion about whether we want to change them or what the text should be.
It would be nice to remove the reference to the [desktop apps course](https://github.com/ionic-team/ionic-docs/blob/desktop-misc/docs/developer-resources/courses.md#building-desktop-apps-with-ionic-and-electron) (developer-resources/courses.md), but I don't know how the courses get selected or if that would be ok to remove.
=> docs(many): remove implications that we support desktop apps

static/usage/v7/img/basic/angular.md, static/usage/v7/img/basic/demo.html, static/usage/v7/img/basic/javascript.md, static/usage/v7/img/basic/react.md, static/usage/v7/img/basic/vue.md, versioned_docs/version-v7/index.md
Issue URL: internal
v7 docs demo was using the latest URL.
v7 docs demo is using the version 7 URL.
N/A
=> chore(demoURL): update docs demo url for v7

src/components/global/Playground/index.tsx
This PR fixes a bug: When the options for a playground's usage target or mode are limited, one of the unavailable options could show as selected. For mode, the playground would even show in the mode that wasn't supposed to be available.
**Reproduction (mode):**
1. set any playground to "md" mode
2. load this page https://ionicframework.com/docs/api/buttons#collapsible-buttons
3. see that it has md mode selected and is also displaying in md mode even though md mode is not available in the switcher
**Reproduction (framework):**
1. set any playground to a framework other than JavaScript
2. load https://ionicframework.com/docs/api/router
3. see that it has the other framework selected, when it should have JavaScript selected
=> fix(playground): use correct usage target or mode, when limited

docs/developing/keyboard.md, docs/developing/managing-focus.md, docs/layout/dynamic-font-scaling.md, docs/layout/structure.md, docs/theming/dark-mode.md, docs/utilities/animations.md, docs/utilities/gestures.md
The playgrounds in the docs guide on the v8 branch are pointing to the v7 directory instead of v8. This PR updates them to point to the correct directory.
=> chore(docs): update playgrounds to use v8

static/usage/v7/label/item/angular.md, static/usage/v7/label/item/demo.html, static/usage/v7/label/item/javascript.md, static/usage/v7/label/item/react.md, static/usage/v7/label/item/vue.md
As reported in https://github.com/ionic-team/ionic-framework/issues/28825, we previously updated the docs for Item to reflect the new line wrapping behavior but missed updating the docs for Label.
[Vercel preview](https://ionic-docs-git-st-label-truncation-ionic1.vercel.app/docs/api/label#item-labels)
=> docs(label): clarify usage for text wrapping

docs/angular/your-first-app.md
There was a [confusion](https://github.com/ionic-team/ionic-docs/pull/3320) regarding to what to select when it came to Angular `NgModules` or `Standalone` when it came to the [Angular Build Your App](https://ionicframework.com/docs/angular/your-first-app#create-an-app).
This PR aims to let devs know that the tutorial is using `NgModules`.
[Preview link](https://github.com/ionic-team/ionic-docs/pull/3320)
=> docs(angular): use ngmodules for the first app

docs/theming/advanced.md
Documents new `--ion-placeholder-opacity` CSS variable.
=> docs(theming): document new placeholder opacity global css variable

docs/react/quickstart.md, docs/vue/quickstart.md
Resolves #3327
Shortcuts:
- https://ionic-docs-git-fw-5781-ionic1.vercel.app/docs/react/quickstart#a-component-with-style
- https://ionic-docs-git-fw-5781-ionic1.vercel.app/docs/vue/quickstart#a-component-with-style
These pages are currently using legacy form control syntax for the checkbox examples. Some of the surrounding content also needed updating to keep things cohesive.
=> docs(react, vue): update Quickstart page to use modern checkbox syntax

scripts/release-notes.mjs
Fixes the generation of the release notes page: https://ionic-docs-git-sp-release-notes-ionic1.vercel.app/docs/reference/release-notes
=> fix: release notes generation from changelog

docs/api/toast.md
See associated bug fix https://github.com/ionic-team/ionic-framework/pull/28950
=> docs(toast): clarify toasts from overlays

docs/api/infinite-scroll.md
We received feedback from the community in Discord that the `virtual-scroll-element` was not clear that it referred to the component/scroll container from the virtual scroll library. 
This PR updates the content to describe that in greater detail.
=> docs(infinite-scroll): clarify virtual scroll element

docs/api/datetime-button.md, docs/api/datetime.md, static/usage/v7/datetime-button/format-options/angular.md, static/usage/v7/datetime-button/format-options/demo.html, static/usage/v7/datetime-button/format-options/index.md, static/usage/v7/datetime-button/format-options/javascript.md, static/usage/v7/datetime-button/format-options/react.md, static/usage/v7/datetime-button/format-options/vue.md, static/usage/v7/datetime/format-options/angular.md, static/usage/v7/datetime/format-options/demo.html, static/usage/v7/datetime/format-options/index.md, static/usage/v7/datetime/format-options/javascript.md, static/usage/v7/datetime/format-options/react.md, static/usage/v7/datetime/format-options/vue.md
Framework dev build: `7.7.2-dev.11707941206.120570b8`
Dependent upon https://github.com/ionic-team/ionic-framework/pull/29009 and https://github.com/ionic-team/ionic-framework/pull/29059
[Design doc](https://github.com/ionic-team/ionic-framework-design-documents/blob/7df5993be0b1cc331e70bf72d1d3a6fbae9f39da/projects/ionic-framework/components/datetime/0006-format-options.md#documentation)
=> docs(datetime, datetime-button): document formatOptions property

docs/core-concepts/cross-platform.md, docs/layout/css-utilities.md, docs/layout/global-stylesheets.md, docs/layout/structure.md, docs/techniques/security.md, docs/theming/advanced.md, docs/theming/colors.md, docs/theming/dark-mode.md, docs/troubleshooting/build.md, versioned_docs/version-v5/core-concepts/cross-platform.md, versioned_docs/version-v5/layout/css-utilities.md, versioned_docs/version-v5/layout/global-stylesheets.md, versioned_docs/version-v5/layout/grid.md, versioned_docs/version-v5/layout/structure.md, versioned_docs/version-v5/techniques/security.md, versioned_docs/version-v5/theming/advanced.md, versioned_docs/version-v5/theming/colors.md, versioned_docs/version-v5/theming/dark-mode.md, versioned_docs/version-v5/theming/platform-styles.md, versioned_docs/version-v5/theming/themes.md, versioned_docs/version-v5/troubleshooting/build.md, versioned_docs/version-v6/core-concepts/cross-platform.md, versioned_docs/version-v6/layout/css-utilities.md, versioned_docs/version-v6/layout/global-stylesheets.md, versioned_docs/version-v6/layout/structure.md, versioned_docs/version-v6/techniques/security.md, versioned_docs/version-v6/theming/advanced.md, versioned_docs/version-v6/theming/colors.md, versioned_docs/version-v6/theming/dark-mode.md, versioned_docs/version-v6/troubleshooting/build.md
The docs repo has a list of [options](https://docusaurus.io/docs/3.0.1/api/plugins/@docusaurus/plugin-content-docs#markdown-front-matter) to pass to Docusaurus. Those options are both official and custom.
`initialTab`, `inlineHtmlPreviews`, and `disableHtmlPreviews` are no longer being used. I removed all the instances.
=> refactor(md): remove unused Docusaurus properties

docs/api/input.md
Resolves #3463
More than one issue has been reported about the input color playground not changing the color of the text, even though this is intended behavior. This PR adds a note that hopefully clarifies things.
Note that the text color *did* change in Ionic v6, so only the v7 docs have been updated.
Shortcut: https://ionic-docs-git-input-color-clarify-ionic1.vercel.app/docs/api/input#colors
=> docs(input): clarify color property description

docs/theming/themes.md, src/components/page/theming/SteppedColorGenerator/index.tsx
We forgot to update the stepped colors docs to note the separate text and background stepped colors in Ionic.
=> docs(theming): note new stepped colors in ionic 8

package.json
Node is running out of memory while building the docs site on production. This is because we are building Ionic 4-8 docs sites as well as the JP docs site. This was not happening during development because we did not hit the memory limit (since JP is only built during production).
In an effort to get the Ionic 8 docs released this PR bumps the memory limit temporarily. Long term we need to investigate a way to lower the overall memory footprint of this build process.
=> chore: increase memory limit temporarily

docs/updating/8-0.md
The v8 breaking changes are available on the `feature-8.0` branch, so we need to link there until v8 is merged into `main`.
=> docs: add correct breaking changes url

docusaurus.config.js, versionsArchived.json
Jared told me that to avoid the flash of the 404 page when going to the v5 docs you need to link to it without the trailing slash.
=> chore: remove trailing slash to avoid flash of 404 page

static/usage/v8/theming/always-dark-mode/demo.html, static/usage/v8/theming/class-dark-mode/demo.html, static/usage/v8/theming/system-dark-mode/demo.html
The dark mode demos for v8 used the new theme import API but did not use the new stepped color tokens. As a result, certain variables were undefined in the demos.
Preview: https://ionic-docs-git-darkmode-fix-ionic1.vercel.app/docs/v8/theming/dark-mode
=> fix(dark-mode): demos use correct stepped color tokens

docs/updating/8-0.md
Our documentation shows how to import the new theme file for dark mode, but it does not show how to migrate the old step color tokens to the new format if devs have some manually defined.
Preview: https://ionic-docs-git-color-step-migration-ionic1.vercel.app/docs/v8/updating/8-0#step-color-tokens
=> docs(updating): show how to migrate custom step color usages

static/usage/v7/theming/automatic-dark-mode/angular/example_component_ts.md
Without type on the parameter, the following error is displayed error TS7006: Parameter 'shouldAdd' implicitly has an 'any' type.
=> docs(theming): add type to prevent compilation error in dark mode playground

static/usage/v7/input/start-end-slots/demo.html, versioned_docs/version-v7/api/input.md
This section was originally added to the v7 docs as part of https://github.com/ionic-team/ionic-docs/pull/3271. For whatever reason, it didn't make it into the versioned docs when the v8 beta docs were created, so now it's missing from v7 but present in v8. This PR restores the section to the v7 docs.
Shortcut: https://ionic-docs-git-input-slot-sync-ionic1.vercel.app/docs/api/input#start-and-end-slots-experimental
=> docs(input): add start/end slot section back into v7 docs

plugins/docusaurus-plugin-ionic-component-api/index.js
The API generation script is using an outdated version of the Ionic 8 beta that existed before the beta was publicly released on the `next` tag. Unfortunately, this was also before the `ionInputModeChange` event was marked as internal for the new picker component. As a result, this event is showing up [as part of the public API](https://ionicframework.com/docs/v8/api/picker#events):
This PR updates the config to use the `next` tag so that the latest version of the Ionic 8 beta is always used.
Preview: https://ionic-docs-git-picker-api-docs-ionic1.vercel.app/docs/v8/api/picker#events
=> docs(config): use correct v8 tag for API generation

docs/api/accordion.md, plugins/docusaurus-plugin-ionic-component-api/index.js, versioned_docs/version-v7/api/accordion.md
I've [seen](https://github.com/ionic-team/ionic-framework/issues/27724) [a](https://github.com/ionic-team/ionic-framework/issues/27986) [few](https://github.com/ionic-team/ionic-framework/issues/28794) instances of developers getting confused about the `ionChange` handler on accordion groups firing when a descendant component such as an input/checkbox has their value changed. This is happening because `ionChange` events bubble, so when Input emits `ionChange` that event bubbles up to the accordion group and causes the `ionChange` callback there to fire.
I think it's worth calling this behavior out on the docs. I made the following changes:
1. Updated the API generation script to note which events bubble.
2. Updated the accordion docs for v7 and v8 to specifically call out this behavior. …
=> docs: note event bubbling

docs/updating/8-0.md
This PR makes the following changes:
1. Adds the latest Ionic 8 beta 2 breaking changes to the migration guide
2. Adds a recommended migration step for Angular apps to avoid confusing when customizing the new dark theme imports. See https://github.com/ionic-team/starters/pull/1834#issue-2162290173 for more information.
=> docs(v8): update with latest migration recommendations

static/usage/v8/modal/controller/react.md
Update the controller example for Ionic React & Modals to clarify the naming of the props.
=> docs(modal): update controller example for react

renovate.json
This is a continuation of https://github.com/ionic-team/ionic-docs/pull/3536. In that PR I only updated `minimumReleaseAge` for the v6 dependencies. I did not do it for the remaining deps.
=> chore(renovate): account for v7 deps with minimumReleaseAge

docs/updating/8-0.md, static/code/stackblitz/v8/angular/styles.css, static/code/stackblitz/v8/html/index.ts, static/code/stackblitz/v8/react/app.tsx, static/code/stackblitz/v8/react/app.withContent.tsx, static/code/stackblitz/v8/vue/main.ts, static/usage/v8/common.js
The stackblitz v8 playgrounds are broken right now: https://ionicframework.com/docs/v8/api/button
I also updated the guide for migrating to v8 to use the new paths.
=> fix: rename themes to palettes in playground imports

docs/api/input-password-toggle.md, plugins/docusaurus-plugin-ionic-component-api/index.js, sidebars.js, static/usage/v8/input-password-toggle/basic/angular.md, static/usage/v8/input-password-toggle/basic/demo.html, static/usage/v8/input-password-toggle/basic/index.md, static/usage/v8/input-password-toggle/basic/javascript.md, static/usage/v8/input-password-toggle/basic/react.md, static/usage/v8/input-password-toggle/basic/vue.md
Adds documentation for https://github.com/ionic-team/ionic-framework/pull/29175
⚠️ Do not merge until https://github.com/ionic-team/ionic-framework/pull/29175 is shipped.
⚠️ Resolve TODOs before merging
Preview: https://ionic-docs-git-ld-password-toggle-ionic1.vercel.app/docs/v8/api/input-password-toggle
Note: Use `8.0.0-dev.11711035263.183d2423` as the build if testing the StackBlitz demos
=> docs(password-toggle): add password toggle docs

static/usage/v7/toast/theming/react/main_tsx.md, static/usage/v8/toast/theming/react/main_tsx.md
Resolves #3550
Updates the React playground examples to use `className` instead of `class`.
=> fix(toast): use className for react examples

docs/react/your-first-app/5-adding-mobile.md, docs/vue/your-first-app/5-adding-mobile.md, versioned_docs/version-v7/react/your-first-app/5-adding-mobile.md, versioned_docs/version-v7/vue/your-first-app/5-adding-mobile.md
Editing the Typing to Fix a TypeScript Error
=> docs(your-first-app): use correct type on "Adding Mobile" page

docs/theming/high-contrast-mode.md
1. Fixes the dark palette import to use the right file name (previously the light and dark palette imports were the same)
2. Changes the code block to `scss` so the comment renders properly
=> docs(high-contrast): fix typo in Angular dark palette import

docs/updating/8-0.md
While going through the migration guide, I noticed that we don't call out having to remove the old light palette colors in order for the updated colors to appear.
=> docs(migration): add info about removing old light palette colors

docs/api/checkbox.md, static/usage/v7/checkbox/label-link/angular.md, static/usage/v7/checkbox/label-link/demo.html, static/usage/v7/checkbox/label-link/index.md, static/usage/v7/checkbox/label-link/javascript.md, static/usage/v7/checkbox/label-link/react.md, static/usage/v7/checkbox/label-link/vue.md, static/usage/v8/checkbox/label-link/angular.md, static/usage/v8/checkbox/label-link/demo.html, static/usage/v8/checkbox/label-link/index.md, static/usage/v8/checkbox/label-link/javascript.md, static/usage/v8/checkbox/label-link/react.md, static/usage/v8/checkbox/label-link/vue.md, versioned_docs/version-v7/api/checkbox.md
See https://github.com/ionic-team/ionic-framework/issues/29304
Developers wanted to know how to add a link to the checkbox label (such as a link that opens a terms and conditions dialog). However, they do not want the checkbox to toggle when the link is clicked. We've had multiple devs ask about this, so I think it's worth making a demo.
=> docs(checkbox): show how to prevent toggling checkbox with link

docs/api/title.md, versioned_docs/version-v7/api/title.md
As part of this ticket the team wanted to provide some information on how to indicate the heading level of an IonTitle to assistive technology. This is part of https://github.com/ionic-team/ionic-framework/issues/23746. We originally tried to have IonTitle automatically determine this, but doing so lead to brittle code with a lot of edge cases to consider. As a result, we felt it would be best to let developers handle this until we can collect more data/feedback on how IonTitle is being used.
Preview: https://ionic-docs-git-fw-119-ionic1.vercel.app/docs/api/title#headings
=> docs(title): add information on setting headings

static/usage/v8/button/icons/angular.md, static/usage/v8/button/icons/demo.html, static/usage/v8/button/icons/javascript.md, static/usage/v8/button/icons/react.md, static/usage/v8/button/icons/vue.md, static/usage/v8/button/shape/angular.md, static/usage/v8/button/shape/demo.html, static/usage/v8/button/shape/javascript.md, static/usage/v8/button/shape/react.md, static/usage/v8/button/shape/vue.md
Preview: https://ionic-docs-git-fw-5965-ionic1.vercel.app/docs/v8/api/button
I didn't think it made sense to add an entirely new playground for this since the circular button can now be achieved by setting `shape="round"` on a button with only an icon. Instead, I updated the `Shape` playground to include buttons containing icons, and the `Icons` playground to include buttons containing icons at different sizes. I wasn't sure how much overlap we wanted in the playgrounds since a `Size` playground also exists. Happy to follow a different approach if anyone has other ideas.
=> docs(button): update shape and icons playgrounds to showcase circular icon buttons

docs/api/modal.md, versioned_docs/version-v7/api/modal.md
We've seen some confusion in https://github.com/ionic-team/ionic-framework/issues/24583 where developers are trying to adjust the height of the sheet modal by changing the max breakpoint. This causes issues because it means some of the modal (while visually shorter) is inaccessible outside of the viewport.
I noticed we had a playground that showed how to do this properly, but it did not show up in the sidemenu because of it being a level 4 heading. As a result, I made the following changes:
1. Removed the "Types of Modals" heading and made Card/Sheet Modal headings go from level 3 to level 2 headings
2. Moved the subheadings in Sheet Modal from level 4 to level 3 headings so they show up in the sidebar
3. Modified the "Auto Sheet Height" title to make it more related to changing the …
=> docs(modal): clarify changing height of sheet modal

renovate.json
Renovate bot is trying to bump the v7 playground deps to v8. This change prevents it from doing that: https://github.com/ionic-team/ionic-docs/pull/3603
=> chore(renovate): do not bump v7 deps to v8

renovate.json
- v6 docs are archived, so they will not be deployed anymore. As a result, we don't need to keep bumping the Renovatebot deps for v6 playgrounds
- Adds v8 dependency so they only get updated to v8.x. Without this, they would start getting updated to v9 once Ionic 9 comes out.
=> chore(renovate): remove v6, add v8

docs/api/datetime.md, docs/api/picker.md
⚠️ Do not merge until https://github.com/ionic-team/ionic-framework/pull/29371 merges. This documentation accompanies that fix.
=> docs(picker): add accessibility docs

renovate.json
Disables Renovate from suggesting dependency updates on v6 playgrounds. 
You can preview the effect of these changes here: https://github.com/sean-perkins/ionic-docs/issues. You will observe no PRs target v6 playgrounds.
=> chore: disable renovate on v6 playgrounds

docs/updating/8-0.md
The upgrade guide still referenced the `next` tag for upgrades.
=> docs(updating): add correct npm tag for v8

docs/vue/testing.md, sidebars.js, versioned_docs/version-v7/vue/testing.md, versioned_sidebars/version-v7-sidebars.json
There are no plans to update this page. It's been decided to remove it entirely.
=> docs(vue): remove the coming soon page

docs/angular/navigation.md
The experimental APIs for standalone routing have not existed for some time. This PR updates the content to match the latest implementation standard with Ionic v8.
=> docs(angular): standalone components are not experimental

vercel.json
This PR will redirect pages formerly hosted under v8 to the main site (since v8 is now the latest)
**It will need to be reverted once v8 is archived**
=> fix(redirects): add redirects for v8 links

scripts/cli.mjs
The local cli script uses deprecated functionality that will cause an exception when using in Node v21.2+: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules
=> fix: use module with syntax for json files

docs/theming/css-variables.md
The `getPropertyValue ` method incorrectly takes `--charcoal` as the input, it should be `--background`
=> docs(theming): replace charcoal variable with background since the property name is background

docs/techniques/security.md
React no longer has a section regarding JSX preventing injection attacks. The link has been removed since it points to the legacy site and the current site doesn't mention it.
=> docs(react): remove React protections link

docusaurus.config.js
Removes beamer. The current experience has a number of accessibility anti-patterns, such as force opening a modal when visiting the site. 
Our users deserve better.
=> chore: remove beamer

static/usage/v6/datetime/highlightedDates/array/index.md, static/usage/v6/datetime/highlightedDates/callback/index.md, static/usage/v6/icon/basic/index.md, static/usage/v6/tabs/router/index.md, static/usage/v7/datetime/highlightedDates/array/index.md, static/usage/v7/datetime/highlightedDates/callback/index.md, static/usage/v7/icon/basic/index.md, static/usage/v7/tabs/router/index.md, static/usage/v8/datetime/highlightedDates/array/index.md, static/usage/v8/datetime/highlightedDates/callback/index.md, static/usage/v8/icon/basic/index.md, static/usage/v8/tabs/router/index.md
This does two things:
1) Update the v8 playgrounds that were still using v7 to use the proper version
2) Update the syntax to use `""` instead of `{}` on the versions because these were skipped in a find & replace for that reason
=> docs(demos): update v8 playgrounds to use correct version

docs/updating/8-0.md
With the advent of react 18 this documentation ages badly, forcing a major version number ensures this continues to work as specifies by the text above it
=> docs(updating): set versions to force major number

docs/angular/navigation.md
Added mention of the need for`IonRouterLink` or  `IonRouterLinkWithHref` directives based on the info in step 9 of https://ionicframework.com/docs/angular/build-options#standalone-based-applications.
=> docs(angular): add tip for usage of IonRouterLink within navigation

docs/api/radio.md, docs/api/toast.md, static/usage/v8/radio/using-comparewith/angular/example_component_html.md, static/usage/v8/radio/using-comparewith/angular/example_component_ts.md, static/usage/v8/radio/using-comparewith/demo.html, static/usage/v8/radio/using-comparewith/index.md, static/usage/v8/radio/using-comparewith/javascript.md, static/usage/v8/radio/using-comparewith/react.md, static/usage/v8/radio/using-comparewith/vue.md, static/usage/v8/toast/swipe-gesture/angular.md, static/usage/v8/toast/swipe-gesture/demo.html, static/usage/v8/toast/swipe-gesture/index.md, static/usage/v8/toast/swipe-gesture/javascript.md, static/usage/v8/toast/swipe-gesture/react.md, static/usage/v8/toast/swipe-gesture/vue.md
A few playgrounds in the API components were using v7 demos instead of v8. This can be reproduced in the following two components:
[Toast](https://ionicframework.com/docs/api/toast#swipe-to-dismiss)
[Radio](https://ionicframework.com/docs/api/radio#object-value-references)
Steps to reproduce:
1. Click the Open in StackBlitz button
1. See that the dependencies for `@ionic/*` are using v7
I copied the v7 demos into the v8 demos directory and updated the versions from 7 to 8. I then changed the paths for the api documentation to point to the v8 demos.
[Toast](https://ionic-docs-git-docs-add-missing-v8-demos-ionic1.vercel.app/docs/api/toast#swipe-to-dismiss)
[Radio](https://ionic-docs-git-docs-add-missing-v8-demos-ionic1.vercel.app/docs/api/radio#object-value-references)
You can search the …
=> docs(api): use v8 demos instead of v7 demos for latest playgrounds

static/usage/v8/input/mask/javascript/index_ts.md, static/usage/v8/modal/styling/animations/javascript/index_ts.md
When passing a custom `index.ts` file to the JavaScript StackBlitz demos, the dark palette files have to be included, otherwise the UI does not change to dark mode based on the system settings. This is apparent when opening a different framework alongside the JavaScript example while the system is set to "Dark". The following demos are broken:
[Input](https://ionicframework.com/docs/api/input#input-masking)
[Modal](https://ionicframework.com/docs/api/modal#animations)
I updated the `index.ts` files for the above demos to include the dark palettes and other missing boilerplate code. 
[Input](https://ionic-docs-git-docs-javascript-index-files-ionic1.vercel.app/docs/api/input#input-masking)
[Modal](https://ionic-docs-git-docs-javascript-index-files-ionic1.vercel.app/docs/api/modal#animations) …
=> docs(api): add missing code to javascript demo index files

docs/updating/8-0.md
The start of the upgrade instructions for Vue referenced Ionic version 7 when it should be 8
=> Update 8-0.md - typo for the version number

static/usage/v7/input/helper-error/javascript.md, static/usage/v7/textarea/helper-error/javascript.md, static/usage/v8/input/helper-error/javascript.md, static/usage/v8/textarea/helper-error/javascript.md
Issue URL: N/A
When viewing the StackBlitz demo for helper and error text for `ion-input` and `ion-textarea` on JavaScript, it does not fire the events needed for the helper and error text to update.
- Used the correct element for the `querySelector`
1. Navigate to [Helper and Error text](https://ionicframework.com/docs/api/input#helper--error-text) on `ion-input`
2. Open StackBlitz - JavaScript
3. Verify that the text is updated when the input value is valid or not
4. Navigate to [Helper and Error text](https://ionicframework.com/docs/api/textarea#helper--error-text) on `ion-textarea`
5. Open StackBlitz - JavaScript
6. Verify that the text is updated when the textarea value is valid or not
=> docs(input, textarea): use a valid element for querySelector

static/usage/v7/input/counter/vue.md, static/usage/v8/input/counter/vue.md
Resolves: #3796
Updates the Vue examples for the `ion-input` counter example to bind the `maxlength property as a number instead of a string.
=> fix(input): vue counter example uses maxlength as a number

docs/api/app.md, static/usage/v8/app/set-focus/angular/example_component_html.md, static/usage/v8/app/set-focus/angular/example_component_ts.md, static/usage/v8/app/set-focus/demo.html, static/usage/v8/app/set-focus/index.md, static/usage/v8/app/set-focus/javascript.md, static/usage/v8/app/set-focus/react.md, static/usage/v8/app/set-focus/vue.md
Adds documentation and a demo for how to use the `setFocus` method with `ion-app` to programmatically focus Ionic components. 
Related issue: https://github.com/ionic-team/ionic-framework/issues/29830
Preview: https://ionic-docs-git-rou-11157-ionic1.vercel.app/docs/api/app#programmatic-focus
=> docs(app): add demo for the setFocus method

docs/react/slides.md, docs/vue/slides.md, versioned_docs/version-v7/react/slides.md, versioned_docs/version-v7/vue/slides.md
Fix import of modules, according to the documentation [Swiper Modules](https://swiperjs.com/swiper-api#using-js-modules)
=> docs(slides): update imports for modules 

docs/api/select.md, static/usage/v8/select/customization/interface-options/angular/example_component_html.md, static/usage/v8/select/customization/interface-options/angular/example_component_ts.md, static/usage/v8/select/customization/interface-options/demo.html, static/usage/v8/select/customization/interface-options/javascript.md, static/usage/v8/select/customization/interface-options/react.md, static/usage/v8/select/customization/interface-options/vue.md, static/usage/v8/select/interfaces/modal/angular.md, static/usage/v8/select/interfaces/modal/demo.html, static/usage/v8/select/interfaces/modal/index.md, static/usage/v8/select/interfaces/modal/javascript.md, static/usage/v8/select/interfaces/modal/react.md, static/usage/v8/select/interfaces/modal/vue.md
**NOTE:** These docs are for an unreleased feature, to test, please update the version used by the playground to the following dev build:
`8.3.4-dev.11730315987.18af6259`
**What's Changed:**
- Adds documentation on new `modal` interface where appropriate
- Adds `modal` interface playground
- Updates interface options playground to add new `modal` type
Associated feature PR: https://github.com/ionic-team/ionic-framework/pull/29972
=> docs(select): add `modal` interface to `ion-select` docs

docs/api/datetime.md, versioned_docs/version-v7/api/datetime.md
Issue URL: N/A
The `presentation` section in `ion-datetime` mentions that `year-month` can be used as a value. That's not an actual option.
- Removed any instances of `year-month`.
[Preview](https://ionic-docs-git-minor-fixes-ionic1.vercel.app/docs/api/datetime#month-and-year-selection)
=> docs(datetime): remove non-existent value from presentation

static/usage/v7/alert/buttons/angular/example_component_ts.md, static/usage/v7/alert/customization/angular/example_component_ts.md, static/usage/v7/alert/inputs/radios/angular/example_component_ts.md, static/usage/v7/alert/inputs/text-inputs/angular/example_component_ts.md, static/usage/v7/alert/presenting/controller/angular/example_component_ts.md, static/usage/v7/alert/presenting/isOpen/angular/example_component_ts.md, static/usage/v7/alert/presenting/trigger/angular/example_component_ts.md, static/usage/v8/alert/buttons/angular/example_component_ts.md, static/usage/v8/alert/customization/angular/example_component_ts.md, static/usage/v8/alert/inputs/radios/angular/example_component_ts.md, static/usage/v8/alert/inputs/text-inputs/angular/example_component_ts.md, static/usage/v8/alert/presenting/controller/angular/example_component_ts.md, static/usage/v8/alert/presenting/isOpen/angular/example_component_ts.md, static/usage/v8/alert/presenting/trigger/angular/example_component_ts.md
[Preview](https://ionic-docs-git-rou-11416-alert-ionic1.vercel.app/docs/api/alert)
=> docs(alert): update angular to standalone

static/usage/v8/app/set-focus/angular/example_component_ts.md
Migrates v8 Angular playgrounds to standalone (playground did not exist on v7)
[Preview](https://ionic-docs-git-rou-11416-app-ionic1.vercel.app/docs/api/app)
=> docs(app): update angular to standalone

static/usage/v7/item-sliding/basic/angular/example_component_html.md, static/usage/v7/item-sliding/basic/angular/example_component_ts.md, static/usage/v7/item-sliding/basic/index.md, static/usage/v7/item-sliding/expandable/angular/example_component_html.md, static/usage/v7/item-sliding/expandable/angular/example_component_ts.md, static/usage/v7/item-sliding/expandable/index.md, static/usage/v7/item-sliding/icons/angular/example_component_ts.md, static/usage/v8/item-sliding/basic/angular/example_component_html.md, static/usage/v8/item-sliding/basic/angular/example_component_ts.md, static/usage/v8/item-sliding/basic/index.md, static/usage/v8/item-sliding/expandable/angular/example_component_html.md, static/usage/v8/item-sliding/expandable/angular/example_component_ts.md, static/usage/v8/item-sliding/expandable/index.md, static/usage/v8/item-sliding/icons/angular/example_component_ts.md
[Preview](https://ionic-docs-git-rou-11416-item-sliding-ionic1.vercel.app/docs/api/item-sliding)
=> docs(item-sliding): update angular to standalone

static/usage/v7/skeleton-text/basic/angular/example_component_html.md, static/usage/v7/skeleton-text/basic/angular/example_component_ts.md, static/usage/v7/skeleton-text/theming/css-properties/angular/example_component_ts.md, static/usage/v7/skeleton-text/theming/css-properties/index.md, static/usage/v8/skeleton-text/basic/angular/example_component_html.md, static/usage/v8/skeleton-text/basic/angular/example_component_ts.md, static/usage/v8/skeleton-text/theming/css-properties/angular/example_component_ts.md, static/usage/v8/skeleton-text/theming/css-properties/index.md
[Preview](https://ionic-docs-git-rou-11416-skeleton-text-ionic1.vercel.app/docs/api/skeleton-text)
=> docs(skeleton-text): update angular to standalone

static/usage/v7/text/basic/angular/example_component_ts.md, static/usage/v8/text/basic/angular/example_component_ts.md
[Preview](https://ionic-docs-git-rou-11416-text-ionic1.vercel.app/docs/api/text)
=> docs(text): update angular to standalone

static/usage/v7/theming/automatic-dark-mode/angular/example_component_ts.md, static/usage/v7/theming/manual-dark-mode/angular/example_component_ts.md, static/usage/v8/theming/always-dark-mode/angular/example_component_ts.md, static/usage/v8/theming/always-high-contrast-mode/angular/example_component_ts.md, static/usage/v8/theming/class-dark-mode/angular/example_component_ts.md, static/usage/v8/theming/class-high-contrast-mode/angular/example_component_ts.md, static/usage/v8/theming/system-dark-mode/angular/example_component_ts.md, static/usage/v8/theming/system-high-contrast-mode/angular/example_component_ts.md
[Dark Mode Preview](https://ionic-docs-git-rou-11416-theming-ionic1.vercel.app/docs/theming/dark-mode)
[High Contrast Mode Preview](https://ionic-docs-git-rou-11416-theming-ionic1.vercel.app/docs/theming/high-contrast-mode) (v8 only)
=> docs(theming): update angular to standalone

docs/developing/tips.md, versioned_docs/version-v7/developing/tips.md
Since Atom is deprecated, I have removed it from the recommendation list.
=> docs(developing): remove Atom from list of recommended editors

static/usage/v7/icon/basic/angular/example_component_ts.md, static/usage/v8/icon/basic/angular.md, static/usage/v8/icon/basic/angular/example_component_ts.md, static/usage/v8/icon/basic/index.md
[Preview](https://ionic-docs-git-rou-11416-icon-ionic1.vercel.app/docs/api/icon)
=> docs(icon): update angular to standalone

static/usage/v7/refresher/advanced/angular/example_component_html.md, static/usage/v7/refresher/advanced/angular/example_component_ts.md, static/usage/v7/refresher/basic/angular/example_component_ts.md, static/usage/v7/refresher/custom-content/angular/example_component_ts.md, static/usage/v7/refresher/custom-scroll-target/angular/example_component_ts.md, static/usage/v7/refresher/pull-properties/angular/example_component_ts.md, static/usage/v8/refresher/advanced/angular/example_component_html.md, static/usage/v8/refresher/advanced/angular/example_component_ts.md, static/usage/v8/refresher/basic/angular/example_component_ts.md, static/usage/v8/refresher/custom-content/angular/example_component_ts.md, static/usage/v8/refresher/custom-scroll-target/angular/example_component_ts.md, static/usage/v8/refresher/pull-properties/angular/example_component_ts.md
[Preview](https://ionic-docs-git-rou-11416-refresher-ionic1.vercel.app/docs/api/refresher)
=> docs(refresher): update angular to standalone

docs/api/reorder.md, static/usage/v7/reorder/basic/angular/example_component_ts.md, static/usage/v7/reorder/custom-icon/angular/example_component_ts.md, static/usage/v7/reorder/custom-scroll-target/angular/example_component_ts.md, static/usage/v7/reorder/toggling-disabled/angular/example_component_ts.md, static/usage/v7/reorder/updating-data/angular/example_component_html.md, static/usage/v7/reorder/updating-data/angular/example_component_ts.md, static/usage/v7/reorder/wrapper/angular/example_component_ts.md, static/usage/v8/reorder/basic/angular/example_component_ts.md, static/usage/v8/reorder/custom-icon/angular/example_component_ts.md, static/usage/v8/reorder/custom-scroll-target/angular/example_component_ts.md, static/usage/v8/reorder/toggling-disabled/angular/example_component_ts.md, static/usage/v8/reorder/updating-data/angular/example_component_html.md, static/usage/v8/reorder/updating-data/angular/example_component_ts.md, static/usage/v8/reorder/wrapper/angular/example_component_ts.md, versioned_docs/version-v7/api/reorder.md
[Preview](https://ionic-docs-git-rou-11416-reorder-ionic1.vercel.app/docs/api/reorder)
=> docs(reorder): update angular to standalone

static/usage/v7/ripple-effect/basic/angular/example_component_ts.md, static/usage/v7/ripple-effect/basic/index.md, static/usage/v7/ripple-effect/customizing/angular/example_component_ts.md, static/usage/v7/ripple-effect/customizing/index.md, static/usage/v7/ripple-effect/type/angular/example_component_ts.md, static/usage/v7/ripple-effect/type/index.md, static/usage/v8/ripple-effect/basic/angular/example_component_ts.md, static/usage/v8/ripple-effect/basic/index.md, static/usage/v8/ripple-effect/customizing/angular/example_component_ts.md, static/usage/v8/ripple-effect/customizing/index.md, static/usage/v8/ripple-effect/type/angular/example_component_ts.md, static/usage/v8/ripple-effect/type/index.md
[Preview](https://ionic-docs-git-rou-11416-ripple-effect-ionic1.vercel.app/docs/api/ripple-effect)
=> docs(ripple-effect): update angular to standalone

static/usage/v7/layout/dynamic-font-scaling/angular/example_component_ts.md, static/usage/v8/layout/dynamic-font-scaling/angular/example_component_ts.md
[Preview](https://ionic-docs-git-rou-11416-layout-ionic1.vercel.app/docs/layout/dynamic-font-scaling)
=> docs(layout): update angular to standalone

docs/api/infinite-scroll.md, static/usage/v7/infinite-scroll/basic/angular/example_component_html.md, static/usage/v7/infinite-scroll/basic/angular/example_component_ts.md, static/usage/v7/infinite-scroll/custom-infinite-scroll-content/angular/example_component_html.md, static/usage/v7/infinite-scroll/custom-infinite-scroll-content/angular/example_component_ts.md, static/usage/v7/infinite-scroll/infinite-scroll-content/angular/example_component_html.md, static/usage/v7/infinite-scroll/infinite-scroll-content/angular/example_component_ts.md, static/usage/v8/infinite-scroll/basic/angular/example_component_html.md, static/usage/v8/infinite-scroll/basic/angular/example_component_ts.md, static/usage/v8/infinite-scroll/custom-infinite-scroll-content/angular/example_component_html.md, static/usage/v8/infinite-scroll/custom-infinite-scroll-content/angular/example_component_ts.md, static/usage/v8/infinite-scroll/infinite-scroll-content/angular/example_component_html.md, static/usage/v8/infinite-scroll/infinite-scroll-content/angular/example_component_ts.md, versioned_docs/version-v7/api/infinite-scroll.md
[Preview](https://ionic-docs-git-rou-11416-infinite-scroll-ionic1.vercel.app/docs/api/infinite-scroll)
=> docs(infinite-scroll): update angular to standalone

static/usage/v7/gestures/basic/angular/example_component_ts.md, static/usage/v7/gestures/double-click/angular/example_component_ts.md, static/usage/v8/gestures/basic/angular/example_component_ts.md, static/usage/v8/gestures/double-click/angular/example_component_ts.md
[Preview](https://ionic-docs-git-rou-11416-gestures-ionic1.vercel.app/docs/utilities/gestures)
=> docs(gestures): update angular to standalone

static/usage/v7/fab/basic/angular/example_component_ts.md, static/usage/v7/fab/button-sizing/angular/example_component_ts.md, static/usage/v7/fab/list-side/angular/example_component_ts.md, static/usage/v7/fab/positioning/angular/example_component_ts.md, static/usage/v7/fab/safe-area/angular/example_component_ts.md, static/usage/v7/fab/theming/colors/angular/example_component_ts.md, static/usage/v7/fab/theming/css-custom-properties/angular/example_component_ts.md, static/usage/v7/fab/theming/css-shadow-parts/angular/example_component_ts.md, static/usage/v8/fab/basic/angular/example_component_ts.md, static/usage/v8/fab/before-content/angular/example_component_html.md, static/usage/v8/fab/before-content/angular/example_component_ts.md, static/usage/v8/fab/button-sizing/angular/example_component_ts.md, static/usage/v8/fab/list-side/angular/example_component_ts.md, static/usage/v8/fab/positioning/angular/example_component_ts.md, static/usage/v8/fab/safe-area/angular/example_component_ts.md, static/usage/v8/fab/theming/colors/angular/example_component_ts.md, static/usage/v8/fab/theming/css-custom-properties/angular/example_component_ts.md, static/usage/v8/fab/theming/css-shadow-parts/angular/example_component_ts.md
[Preview](https://ionic-docs-git-rou-11416-fab-ionic1.vercel.app/docs/api/fab)
=> docs(fab): update angular to standalone

static/usage/v7/backdrop/basic/angular/example_component_ts.md, static/usage/v7/backdrop/basic/index.md, static/usage/v7/backdrop/styling/angular/example_component_ts.md, static/usage/v7/backdrop/styling/index.md, static/usage/v8/backdrop/basic/angular/example_component_ts.md, static/usage/v8/backdrop/basic/index.md, static/usage/v8/backdrop/styling/angular/example_component_ts.md, static/usage/v8/backdrop/styling/index.md
[Preview](https://ionic-docs-git-rou-11416-backdrop-ionic1.vercel.app/docs/api/backdrop)
=> docs(backdrop): update angular to standalone

static/usage/v7/action-sheet/controller/angular/example_component_ts.md, static/usage/v7/action-sheet/inline/isOpen/angular/example_component_ts.md, static/usage/v7/action-sheet/inline/trigger/angular/example_component_ts.md, static/usage/v7/action-sheet/role-info-on-dismiss/angular/example_component_ts.md, static/usage/v7/action-sheet/theming/css-properties/angular/example_component_ts.md, static/usage/v7/action-sheet/theming/styling/angular/example_component_ts.md, static/usage/v8/action-sheet/controller/angular/example_component_ts.md, static/usage/v8/action-sheet/inline/isOpen/angular/example_component_ts.md, static/usage/v8/action-sheet/inline/trigger/angular/example_component_ts.md, static/usage/v8/action-sheet/role-info-on-dismiss/angular/example_component_ts.md, static/usage/v8/action-sheet/theming/css-properties/angular/example_component_ts.md, static/usage/v8/action-sheet/theming/styling/angular/example_component_ts.md
[Preview](https://ionic-docs-git-rou-11416-action-sheet-ionic1.vercel.app/docs/api/action-sheet)
=> docs(action-sheet): update angular to standalone

src/components/global/Playground/stackblitz.utils.ts, static/usage/v7/input/mask/react.md, static/usage/v8/input/mask/react.md
The input mask demo is not working in StackBlitz for React. Additionally, it incorrectly passes dependencies as files.
1. Navigate to [Input Masking](https://ionicframework.com/docs/api/input#input-masking).
2. Select `React` and then `Open in StackBlitz`.
3. Observe that a folder named `@maskito` is present, containing two files (`core` and `react`) which only contain dependency versions.
4. Note that the demo does not display correctly, resulting in a white screen where the demo should appear.
The dependencies are no longer passed as files, and the missing imports are added, allowing the React demo to function correctly.
1. Navigate to [Input Masking](https://ionic-docs-git-docs-react-stackblitz-input-mask-ionic1.vercel.app/docs/api/input#input-masking).
2. Select `React` and then `Open …
=> docs(input): add missing imports for maskito in React

docs/api/input-password-toggle.md
The title is incorrectly displayed as [`ion-password-toggle`](https://ionicframework.com/docs/api/input-password-toggle). It should be [`ion-input-password-toggle`](https://ionic-docs-git-docs-input-password-toggle-title-ionic1.vercel.app/docs/api/input-password-toggle) to match the component name.
This component does not exist on v7 and therefore does not need to be updated in the versioned docs.
=> docs(input-password-toggle): update title to correct component name

.prettierignore, docs/reference/glossary.md
Links in the [Glossary](https://ionicframework.com/docs/reference/glossary) contain unnecessary line breaks.
Exclude the glossary file from Prettier formatting to prevent the addition of line breaks and `{' '}` around links and fixes the formatting. [Preview](https://ionic-docs-git-docs-glossary-link-line-breaks-ionic1.vercel.app/docs/reference/glossary)
=> docs(glossary): update formatting to remove line breaks around links

docs/reference/support.md
resolves #3904
[Preview](https://ionic-docs-git-rou-11506-ionic1.vercel.app/docs/reference/support#ionic-angular)
=> docs(support): add Angular 19 support to table

docs/developing/android.md, docs/developing/ios.md, versioned_docs/version-v7/developing/android.md, versioned_docs/version-v7/developing/ios.md
Issue URL: resolves https://github.com/ionic-team/ionic-docs/issues/3838
Links that are pointing to v6 in the following structure are no longer redirecting correctly: `/docs/v6`. This is due to that version being archived, which causes the domain to change.
Updated the links to the correct domain. I checked for other locations but this is only happening within two pages.
I considered making a global variable through the Docusaurus config but decided against it since it would only be used for 4 pages. We might also end up removing the reference in the next version.
[Preview - iOS v8](https://ionic-docs-git-rou-11505-ionic1.vercel.app/docs/developing/ios)
[Preview - Android v8](https://ionic-docs-git-rou-11505-ionic1.vercel.app/docs/developing/android)
[Preview - iOS …
=> docs(ios, android): update v6 links

docs/angular/your-first-app/8-distribute.md, docs/react/your-first-app/8-distribute.md, docs/vue/your-first-app/8-distribute.md, versioned_docs/version-v7/angular/your-first-app/8-distribute.md, versioned_docs/version-v7/react/your-first-app/8-distribute.md, versioned_docs/version-v7/vue/your-first-app/8-distribute.md
Maintain consistency and enhance clarity without altering existing content.
=> docs(your-first-app): remove duplicate word and correct grammar

docs/angular/build-options.md, versioned_docs/version-v7/angular/build-options.md
It's discouraged now: https://angular.dev/api/core/enableProdMode
"Using this method is discouraged as the Angular CLI will set production mode when using the optimization option."
=> docs(build-options): remove enableProdMode() reference

docs/utilities/gestures.md, versioned_docs/version-v7/utilities/gestures.md
Are we talking about gestures or animations?
=> docs(gestures): update Animation references to Gesture

docs/api/badge.md, docs/api/tab-bar.md, static/usage/v8/badge/inside-tab-bar/angular/example_component_html.md, static/usage/v8/badge/inside-tab-bar/angular/example_component_ts.md, static/usage/v8/badge/inside-tab-bar/demo.html, static/usage/v8/badge/inside-tab-bar/index.md, static/usage/v8/badge/inside-tab-bar/javascript.md, static/usage/v8/badge/inside-tab-bar/react.md, static/usage/v8/badge/inside-tab-bar/vue.md
Issue URL: resolves #4039 
There are no docs that show how badges can be used within a tab bar.
Added playgrounds to show this use case.
[Badge preview](https://ionic-docs-git-fw-6378-ionic1.vercel.app/docs/api/badge#badges-in-tab-buttons)
[Tab bar preview](https://ionic-docs-git-fw-6378-ionic1.vercel.app/docs/api/tab-bar#badges-in-tab-buttons)
=> docs(badge, tab-bar): add playground to show usage of badges in tab-bar

docs/react/navigation.md, docs/vue/navigation.md, docs/vue/utility-functions.md, versioned_docs/version-v7/react/navigation.md, versioned_docs/version-v7/vue/navigation.md, versioned_docs/version-v7/vue/utility-functions.md
RouterDirection does not contain `none`: https://github.com/ionic-team/ionic-framework/blob/8dd566b5c1241022e26cc91c0f415de20c0d0f34/core/src/components/router/utils/interface.ts#L66
When using with Vue it gives this error:
```
Type '"none"' is not assignable to type 'RouterDirection | undefined'
```
While it might work for React, I think this is incorrect: https://github.com/ionic-team/ionic-framework/blob/8dd566b5c1241022e26cc91c0f415de20c0d0f34/packages/react/src/models/RouterDirection.ts#L1
=> docs(navigation): correct routerDirection values

docs/reference/support.md, versioned_docs/version-v7/reference/support.md
Issue URL: N/A
The support pages do not display the true statuses for v7 and v8.
Updated statuses and dates for v7 and v8.
- [v7 Support page](https://ionic-docs-git-support-page-ionic1.vercel.app/docs/v7/reference/support#framework-maintenance-and-support-status)
- [v8 Support page](https://ionic-docs-git-support-page-ionic1.vercel.app/docs/reference/support#framework-maintenance-and-support-status)
=> docs(support): update framework statuses

docs/reference/support.md, versioned_docs/version-v7/reference/support.md
Issue URL: N/A
As of April 17, v7 is no longer supported at any level. This makes the support page out of date.
Update the support page to reflect the correct status for v7,
- [v8 Preview](https://ionic-docs-git-support-page-ionic1.vercel.app/docs/reference/support#framework-maintenance-and-support-status)
- [v7 Preview](https://ionic-docs-git-support-page-ionic1.vercel.app/docs/v7/reference/support#framework-maintenance-and-support-status)
=> docs(support-page): update v7 status

scripts/native.mjs
Issue URL: N/A
Pages under the `/native` are [auto-generated](https://github.com/ionic-team/ionic-docs/blob/f180f5102800dccad329e56f1f7ecfa72c360563/package.json#L17) based on the packages' latest README. The docs site has no way to override the contents as any changes would be immediately removed upon `start` or `build`.
Docusaurus will throw parse errors when using `{@link URL|Text}` or `{@link URL}`.
There's been a recent [README update](https://github.com/ionic-team/capacitor-google-maps/commit/4fb47b5aae8fc820607a2cddfbea54284aec66c6#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) to the `@capacitor/google-maps` that used JSDoc links. This caused Docusaurus to throw a parse error, leading to the docs site to not build or start.
Updated the native script to …
=> chore(script-native): convert JSDoc links to Markdown links

static/code/stackblitz/v8/html/index.withContent.html, static/usage/v8/common.js, static/usage/v8/fab/before-content/demo.html
There are a few paths targeting `core@next` which should be `core@8`. See the differences here:
[static/code/stackblitz/v8/html/index.withContent.html](https://github.com/ionic-team/ionic-docs/blob/fee8fa0c3a0a39f984b62f3775672bfdeb16d56c/static/code/stackblitz/v8/html/index.withContent.html#L4-L5)
[static/code/stackblitz/v8/html/index.html](https://github.com/ionic-team/ionic-docs/blob/fee8fa0c3a0a39f984b62f3775672bfdeb16d56c/static/code/stackblitz/v8/html/index.html#L4-L5)
The files above are both used by the JavaScript StackBlitz examples but target different npm tags for `core`.
=> docs(playgrounds): fix cdn imports to target v8

plugins/docusaurus-plugin-ionic-component-api/index.js
Resolves #634 
Created renderParameters function in docusaurus script to include optional row for method parameter definitions if present. Called in renderMethods function.
=> docs(docusaurus): Ionic method parameters are missing descriptions (#634)

static/usage/v7/infinite-scroll/basic/vue.md, static/usage/v7/infinite-scroll/custom-infinite-scroll-content/vue.md, static/usage/v7/infinite-scroll/infinite-scroll-content/vue.md, static/usage/v8/infinite-scroll/basic/vue.md, static/usage/v8/infinite-scroll/custom-infinite-scroll-content/vue.md, static/usage/v8/infinite-scroll/infinite-scroll-content/vue.md
Resolves #4095
**Changelog**
- Removed duplicate IonContent imports in Vue displays
- Removed import and export of unused IonImg components in Vue displays
- Demoed changes of modified components, all remain functional
- Compiled and previewed modified docs site with changes, all remain functional
=> docs(infinite-scroll): remove duplicate and unused imports

static/usage/v7/accordion/accessibility/animations/demo.html, static/usage/v7/accordion/basic/demo.html, static/usage/v7/accordion/customization/advanced-expansion-styles/demo.html, static/usage/v7/accordion/customization/expansion-styles/demo.html, static/usage/v7/accordion/customization/icons/demo.html, static/usage/v7/accordion/customization/theming/demo.html, static/usage/v7/accordion/disable/group/demo.html, static/usage/v7/accordion/disable/individual/demo.html, static/usage/v7/accordion/listen-changes/demo.html, static/usage/v7/accordion/multiple/demo.html, static/usage/v7/accordion/readonly/group/demo.html, static/usage/v7/accordion/readonly/individual/demo.html, static/usage/v7/accordion/toggle/demo.html, static/usage/v8/accordion/accessibility/animations/demo.html, static/usage/v8/accordion/basic/demo.html, static/usage/v8/accordion/customization/advanced-expansion-styles/demo.html, static/usage/v8/accordion/customization/expansion-styles/demo.html, static/usage/v8/accordion/customization/icons/demo.html, static/usage/v8/accordion/customization/theming/demo.html, static/usage/v8/accordion/disable/group/demo.html, static/usage/v8/accordion/disable/individual/demo.html, static/usage/v8/accordion/listen-changes/demo.html, static/usage/v8/accordion/multiple/demo.html, static/usage/v8/accordion/readonly/group/demo.html, static/usage/v8/accordion/readonly/individual/demo.html, static/usage/v8/accordion/toggle/demo.html
I noticed that the [Accordion: Expansion Styles](https://ionicframework.com/docs/api/accordion#advanced-expansion-styles) demo is the only one that shows the accordion a bit wider. This looks better in my opinion, so I updated all of the demos to add this style.
| Before | After |
| ---| ---|
| ![before](https://github.com/user-attachments/assets/75b3cefa-c7ae-473a-ba7c-33814c3e9bde) | ![after](https://github.com/user-attachments/assets/b0db0922-1190-45c8-880a-64ca8f7cd450) |
[Preview](https://ionic-docs-git-docs-accordion-demos-ionic1.vercel.app/docs/api/accordion)
=> docs(accordion): update demos to always set accordion to 300px wide

docs/reference/support.md
Issue URL: internal
The support page displays that Angular 19 is the maximum version.
Updated the support page to display Angular 20 to be the maximum version.
[Preview](https://ionic-docs-b74ljiu5s-ionic1.vercel.app/docs/reference/support#ionic-angular)
=> docs(support): add Angular 20 support

renovate.json
Issue URL: N/A
`@angular-devkit` does not upgrade with `@angular` packages.
`@angular-devkit` has been grouped under `angular`. This will allow `@angular-devkit` and `@angular` packages to be upgraded in the same PR.
N/A
=> chore(renovate): bundle @angular-devkit with @angular

docusaurus.config.js, src/styles/components/_code.scss
resolves #4156
- Add 'diff' to list of additionalLanguages in docusaurus.config.js
- Move `.token.inserted` selector to greenish #42b983 block after verifying `.token.inserted` and `.token.deleted` will only select lines in diff blocks
Screenshot from docs/angular/build-options
=> fix(docusaurus): support diff code blocks #4156

docs/theming/high-contrast-mode.md
=> docs(theming): fix broken link in high contrast mode guide

static/usage/v7/refresher/advanced/angular/example_component_ts.md, static/usage/v7/refresher/advanced/react/main_tsx.md, static/usage/v7/refresher/advanced/vue.md, static/usage/v7/refresher/basic/angular/example_component_ts.md, static/usage/v7/refresher/basic/react.md, static/usage/v7/refresher/basic/vue.md, static/usage/v7/refresher/custom-content/angular/example_component_ts.md, static/usage/v7/refresher/custom-content/react.md, static/usage/v7/refresher/custom-content/vue.md, static/usage/v7/refresher/custom-scroll-target/angular/example_component_ts.md, static/usage/v7/refresher/custom-scroll-target/react/main_tsx.md, static/usage/v7/refresher/custom-scroll-target/vue.md, static/usage/v7/refresher/pull-properties/angular/example_component_ts.md, static/usage/v7/refresher/pull-properties/react.md, static/usage/v7/refresher/pull-properties/vue.md, static/usage/v8/refresher/advanced/angular/example_component_ts.md, static/usage/v8/refresher/advanced/react/main_tsx.md, static/usage/v8/refresher/advanced/vue.md, static/usage/v8/refresher/basic/angular/example_component_ts.md, static/usage/v8/refresher/basic/react.md, static/usage/v8/refresher/basic/vue.md, static/usage/v8/refresher/custom-content/angular/example_component_ts.md, static/usage/v8/refresher/custom-content/react.md, static/usage/v8/refresher/custom-content/vue.md, static/usage/v8/refresher/custom-scroll-target/angular/example_component_ts.md, static/usage/v8/refresher/custom-scroll-target/react/main_tsx.md, static/usage/v8/refresher/custom-scroll-target/vue.md, static/usage/v8/refresher/pull-properties/angular/example_component_ts.md, static/usage/v8/refresher/pull-properties/react.md, static/usage/v8/refresher/pull-properties/vue.md
Hey, I noticed that in the framework examples for the refresher docs, the convenient `RefresherCustomEvent` type isn't used at all, even though it is provided by the respective packages and [documented on the site](https://ionicframework.com/docs/api/refresher#refreshercustomevent).
Only in the React examples, it is kind-of used as `CustomEvent<RefresherEventDetails>`.
This occured to me when I was reading the [`ion-infinite-scroll`](https://ionicframework.com/docs/api/infinite-scroll) docs for Vue, where the `InfiniteScrollCustomEvent` is being used and provides proper TypeScript support.
I streamlined the Angular, Vue and React examples to use the same Event type instead of having varying approaches for every implementation.
Hope to hear your feedback on this!
=> docs(refresher): use `RefresherCustomEvent` type in playground examples

renovate.json, src/components/global/Playground/stackblitz.utils.ts, static/code/stackblitz/v7/html/index.html, static/code/stackblitz/v7/html/index.withContent.html, static/code/stackblitz/v7/html/package.json, static/code/stackblitz/v7/html/tsconfig.json, static/code/stackblitz/v7/html/vite.config.ts, static/code/stackblitz/v8/html/index.html, static/code/stackblitz/v8/html/index.withContent.html, static/code/stackblitz/v8/html/package.json, static/code/stackblitz/v8/html/tsconfig.json, static/code/stackblitz/v8/html/vite.config.ts
This PR migrates the JavaScript playgrounds to use Node and Vite.
Playgrounds I suggest testing:
- [Alert: Controller](https://ionic-docs-git-fw-6238-ionic1.vercel.app/docs/api/alert#controller-alerts) - example of overlay
- [Badge: Custom CSS Properties](https://ionic-docs-git-fw-6238-ionic1.vercel.app/docs/api/badge#css-properties) - example of custom styles
- [Buttons: Icons](https://ionic-docs-git-fw-6238-ionic1.vercel.app/docs/api/button#icons) - example of using Ionicons
- [Input: Mask](https://ionic-docs-git-fw-6238-ionic1.vercel.app/docs/api/input#input-masking) - example of using a custom dependency
- [Ripple Effect: Basic](https://ionic-docs-git-fw-6238-ionic1.vercel.app/docs/api/ripple-effect#basic-usage) - example of ripple effect
- [Modal: …
=> refactor(stackblitz): move html playgrounds to node and vite

docs/components.md, sidebars.js
I noticed after merging https://github.com/ionic-team/ionic-docs/commit/6f5a148f6d17f9ca1546570582aaec77da05f145 that we forgot to add Range to the components page.
This PR:
- Adds range, replacing input OTP in the design
- I decided to remove input OTP because I think we should match the side bar section headings for cards
- Updates the sidebar to be in proper alphabetical order and match the components order
- Updates some section headings in the sidebar to match the card headers
[Preview](https://ionic-docs-git-fw-6391-ionic1.vercel.app/docs/components)
=> docs(components): update main components page to match sidebar sections

src/theme/DocSidebar/index.tsx
**Problem:**
When navigating the docs site, the sidebar does not update to reflect the active item.
**Solution:**
This PR updates the sidebar to scroll the active item into view when a new page is selected.
**Test steps:**
1. Visit https://ionicframework.com/docs/components
2. Scroll down and select "Popover"
3. Notice that the sidebar remains at the top (starting at "Accordion") and "Popover" is not visible
4. Visit https://ionic-docs-git-fix-sidebar-scroll-ionic1.vercel.app/docs/components
5. Repeat step 2
6. Confirm that the sidebar now scrolls to and highlights "Popover"
**Repeat the test steps above for a "Guide" page:**
1. Go to https://ionicframework.com/docs/
2. Click on the "Theming" card
3. Notice the sidebar remains at the top
4. Repeat for …
=> fix(sidebar): scroll to the active item after navigating

docs/angular/storage.md, docs/react/storage.md, docs/vue/storage.md, versioned_docs/version-v7/angular/storage.md, versioned_docs/version-v7/react/storage.md, versioned_docs/version-v7/vue/storage.md
This closes internal ticket https://outsystemsrd.atlassian.net/browse/RMET-3245.
Main changes:
- Remove references to outdated packages.
- Specify storage mechanisms based on the needs of the application.
- Added a disclaimer about third party plugins/products neither being endorsed nor supported. We constantly get "but it was on your official documentation" and I want to make it clear that does not imply endorsement or support obligations.
[Preview](https://ionic-docs-git-docs-storage-ionic1.vercel.app/docs/angular/storage)
=> docs(storage): replace outdated or sunset products with active projects

docs/api/radio.md, static/usage/v7/radio/label-wrap/angular/example_component_css.md, static/usage/v7/radio/label-wrap/angular/example_component_html.md, static/usage/v7/radio/label-wrap/angular/example_component_ts.md, static/usage/v7/radio/label-wrap/demo.html, static/usage/v7/radio/label-wrap/index.md, static/usage/v7/radio/label-wrap/javascript.md, static/usage/v7/radio/label-wrap/react/main_css.md, static/usage/v7/radio/label-wrap/react/main_tsx.md, static/usage/v7/radio/label-wrap/vue.md, static/usage/v8/radio/label-wrap/angular/example_component_css.md, static/usage/v8/radio/label-wrap/angular/example_component_html.md, static/usage/v8/radio/label-wrap/angular/example_component_ts.md, static/usage/v8/radio/label-wrap/demo.html, static/usage/v8/radio/label-wrap/index.md, static/usage/v8/radio/label-wrap/javascript.md, static/usage/v8/radio/label-wrap/react/main_css.md, static/usage/v8/radio/label-wrap/react/main_tsx.md, static/usage/v8/radio/label-wrap/vue.md, versioned_docs/version-v7/api/radio.md
resolves #3373
- Create new section in `ion-radio` docs called "Label Wrapping".
- Create new demo and examples for JavaScript, React, Angular and Vue.
The new section is placed beneath "Label Placement" because that section includes information about truncating text with an ellipsis.
=> docs(radio): add example for wrapping label text

static/usage/v7/radio/using-comparewith/angular/example_component_ts.md, versioned_docs/version-v7/api/radio.md
The v7 version of the [Radio API docs](https://ionic-docs-git-docs-radio-v7-usage-ionic1.vercel.app/docs/v7/api/radio#object-value-references) was pointing to the v8 playground example for comparewith.
=> docs(radio): point to correct v7 usage for comparewith

docs/core-concepts/fundamentals.md, plugins/docusaurus-plugin-ionic-component-api/index.js, versioned_docs/version-v5/core-concepts/fundamentals.md, versioned_docs/version-v6/core-concepts/fundamentals.md, versioned_docs/version-v7/core-concepts/fundamentals.md
Resolves #3814 
Changelog:
- Adds documentation to fundamentals about reactive & virtual properties
- Updates properties table for API pages to include a note for virtual properties linking to fundamentals
[Fundamentals Preview](https://ionic-docs-git-fork-kkindrai-3814virtual-properti-5628fa-ionic1.vercel.app/docs/core-concepts/fundamentals#properties)
[Properties API Preview](https://ionic-docs-git-fork-kkindrai-3814virtual-properti-5628fa-ionic1.vercel.app/docs/api/accordion#properties)
=> docs(guide): add properties section to fundamentals and virtual property description to API
