src/content/installation/android.md
to make it possible to just "next" through the whole docs
=> Next link for Android Setup

src/content/building/storage.md
=> Storage: Add prev/next links

src/content/building/storage.md
=> Storage: Link with text instead of just URL

src/content/theming/platform-styles.md
Remove strange backticks for iOS devices and uppercase Android
=> Platform Styles: Fix description of platform-mode

src/content/publishing/progressive-web-app.md
• Fixed a typo
• Clarified the firebase.json example
=> Publishing PWA update

src/content/installation/ios.md
Currently XCode 10 does not work with Cordova.
See: https://github.com/apache/cordova-ios/issues/407
=> docs(installation-ios): warn about Xcode 10

src/content/pro/builds/intro.md
Adds docs describing what builds concurrency is.
=> Added docs for concurrency limits

package-lock.json, src/content/pro/builds/intro.md
Documentation for concurrency builds limit
=> Concurrency docs

src/content/building/testing.md
Swapped two words and changed a tense.  No big whoop.
-
-
-
**Fixes**: #
=> Two small typos

package-lock.json, src/content/developer-resources/guides.md, src/content/developer-resources/guides/first-app-v4/creating-photo-gallery-device-storage.md, src/content/developer-resources/guides/first-app-v4/intro.md, src/content/developer-resources/guides/first-app-v4/ios-android-camera.md, src/content/developer-resources/guides/first-app-v4/theming.md
Add a new tutorial, used in our email nurtures for new Ionic account signups.
Add new article under Guides section.
-
-
-
**Fixes**: #
=> Photo tutorial - framework v4

src/content/publishing/app-store.md
(title)
- just fixed a typo
**Fixes**: corrects a typo
=> Fix typo in ‘Publishing to app store’

src/content/installation/android.md
fix close `<p>` tag.
-
-
-
**Fixes**: #
=> fix(installation/android): close <p> tag.

package-lock.json, src/content/building/migration.md
updating migration guide with v1 to v4 info
=> adding section to migration guide on v1 to v4

src/pages/developer-resources/guides/first-app-v4/ios-android-camera.md
=> add section to manually add cordova script tag

src/components/search/search.css
Hide search until it's fully functional.
=> chore: hide search temporarily

src/pages/theming/advanced.md
=> fix(theming): remove HTML blockquotes in favor of Markdown

scripts/build-menus/index.ts
closes ionic-team/ionic-native#2658
=> fix(native): add external repo links to menu

package-lock.json, package.json
=> chore(deps): update @ionic/docs -> 4.0.1

src/components/page/page.css
=> fix(demo): prevent demo expansion in grid

src/components/reference/reference.css, src/styles/base.css
=> style: adjust code and reference type styles

src/components.d.ts, src/components/contributor-list/contributor-list.css, src/components/contributor-list/contributor-list.tsx, src/components/page/templates/default.tsx
=> feat(contributor-list): add contributor list to default template

package-lock.json, package.json, src/components/page/templates/api.tsx
=> feat(api): add slots table

src/pages/publishing/progressive-web-app.md
https://github.com/ionic-team/ionic-docs/issues/447#issue-409047766
=> fixed grammar issue in 'Publishing a Progressive Web App' page

src/pages/theming/advanced.md
- adds a section on Variables in Media Queries
- adds a section on Modifying CSS Color Variables
closes #167
=> docs(theming): add more sections on the limitations for CSS variables

src/components.d.ts, src/demos/api/progress-bar/index.html
=> docs(progressBar): add example for ion-progress-bar)

package-lock.json, package.json, src/demos/api/skeleton-text/index.html
- removes the temporary hacks to style skeleton by updating to the dev build of ionic
- not sure if we want the docs on a dev build so I will leave this here for review
=> docs(demos): update skeleton text to latest usage

src/pages/layout/css-utilities.md, src/pages/layout/grid.md, src/pages/layout/structure.md, src/pages/theming/advanced.md, src/pages/theming/basics.md, src/pages/theming/color-generator.md, src/pages/theming/css-variables.md, src/pages/theming/platform-styles.md, src/pages/utilities/config.md, src/pages/utilities/platform.md
this PR adds some missing contributors to a few places, I was going to add more in other places but unfortunately we lost the git history of who originally added the files when we refactored the docs and I don't remember who originally added them.
=> docs(all): add missing contributors

src/components/page/templates/api.tsx
=> feat(api): show property defaults

scripts/build-menus/index.ts, scripts/build-pages/page-types/native.ts, scripts/data/native.json
=> chore(build): update native data

src/components/page/templates/cli.tsx
Fixes https://github.com/ionic-team/ionic-docs/issues/558
=> fix display of boolean flags with default true

src/demos/api/action-sheet/index.html, src/demos/api/alert/index.html, src/demos/api/anchor/index.html, src/demos/api/back-button/index.html, src/demos/api/fab/index.html, src/demos/api/icon/index.html, src/demos/api/infinite-scroll/data.js, src/demos/api/infinite-scroll/index.html, src/demos/api/input/index.html, src/demos/api/item/index.html, src/demos/api/loading/index.html, src/demos/api/modal/index.html, src/demos/api/nav/index.html, src/demos/api/picker/index.html, src/demos/api/popover/index.html, src/demos/api/tabs/index.html, src/demos/api/text/index.html, src/demos/api/toast/index.html
- Updates input demo to include textarea example and improved UI
- Adds infinite scroll demo with fake data including avatars
This will close out issue #463.
Input before & after
| `master` | `branch` |
| ---| ---|
| ![](https://user-images.githubusercontent.com/6577830/55179513-f5410c00-515d-11e9-9022-151b24a65193.png) | ![](https://user-images.githubusercontent.com/6577830/55179512-f5410c00-515d-11e9-8e1d-d401450fd7fa.png) |
Infinite scroll demo
=> docs(demos): adds infinite scroll demo and updates input demo

src/pages/navigation/angular.md
"kick things off" sounds more natural :)
=> Fix typos in angular.md

src/pages/appflow/quickstart/environment.md
* Adds some additional text clarifying when to create the Environment & related environment variable prior to the example
=> fix(appflow): Minor addition to Environment setup

src/components/menu/templates/appflow.tsx, src/components/nav/nav.css, src/components/nav/nav.tsx
Updates the menu design per Ben
=> fix(menu): update menu design

src/components/menu/templates/main.tsx, src/pages/developer-resources/guides/first-app-v4/creating-photo-gallery-device-storage.md, src/pages/developer-resources/guides/first-app-v4/intro.md, src/pages/developer-resources/guides/first-app-v4/ios-android-camera.md, src/pages/intro/concepts.md
Flow modifications to lead people to get started building their first app quickly.
=> Build Your First App Flow Modifications

src/pages/publishing/app-store.md
=> Fixed typos in app-store.md

src/pages/appflow/deploy/api.md
-added missing await in example
-removed reference to monitoring
=> sync method code example correction

src/pages/building/migration.md
The statement "see Starting an app" had a starting parenthesis, but no closing. This PR closes the statement.
=> Add a missing close parenthesis

scripts/build-pages/page-types/api.ts, src/components/demo/demo.css, src/components/demo/demo.tsx, src/components/page/page.tsx
=> add view source link to API page demos

src/pages/faq/glossary.md
Update karma link to the latest version
=> Update karma link

src/pages/angular/your-first-app.md, src/pages/angular/your-first-app/creating-photo-gallery-device-storage.md, src/pages/angular/your-first-app/ios-android-camera.md
Update YFP Angular guide to reflect new Ionic CLI 5 changes.
=> Your First App - CLI 5 updates

src/pages/building/migration.md
=> Update angular navigation link

src/components/color-gen/demo/index.html
color-generator demo is fixed 4.0.0. But some components may changed in current version.
=> update(demo): unpkg version change 4.0.0 to latest

src/components.d.ts, src/components/color-gen/css-text/color-gen-css-text.tsx, src/components/color-gen/demo/index.html, src/components/color-gen/variable-selector/color-gen-variable-selector.css, src/components/color-gen/variable-selector/color-gen-variable-selector.tsx, src/components/new-color-generator/new-color-generator.css, src/components/new-color-generator/new-color-generator.tsx, src/pages/theming/colors.md
This adds a new color creator on the color documentation that generates the CSS variables to set on the root & the Ionic class to use the color on Ionic components. It also updates the documentation to be more clear on how to add a new color manually.
=> feat(theming): add new color creator & update the color docs

scripts/data/native.json
Correct the github group name in the repository url.
=> Use correct repository

src/pages/appflow/deploy/api.md
=> Updating documentation example api.md

src/components/menu/templates/enterprise.tsx, src/pages/enterprise/contacts.md
Add Contacts plugin to enterprise offering
=> Add contacts plugin

src/pages/react/your-first-app.md
I just tried to create an Ionic App with Codesandbox with some copy/paste and the IonApp was not imported.
=> docs(react/your-first-app): Import missing

src/pages/enterprise/auth-connect.md
including:  
* updates to workflow
* updates to options (e.g. android toolbar color)
* additional details about IdentityVault integration
* details about supporting Azure password reset with custom user flow/policy
=> updates for recent changes to the auth connect plugin

src/components/menu/templates/enterprise.tsx, src/pages/enterprise.md, src/pages/enterprise/couchbase-lite.md
Also added Contacts on src/pages/enterprise.md
=> docs(native): add enterprise couchbase lite page

src/pages/appflow/automation/environments.md
People keep trying to use this on Ionic v4 and keep failing...
=> doc(environments): clarify acceptable version for feature

src/pages/enterprise.md
Users more certain and active verbiage since some things we were "suggesting" before really are things ppl have to do in order to get this to work.
Also clarified what needs to be done, by who, etc.
=> doc(enterprise): clarify the IEE setup process

src/assets/locales/en/messages.json, src/components/menu/templates/enterprise.tsx, src/components/page/templates/enterprise-plugin.tsx, src/pages/enterprise.md, src/pages/enterprise/quickstart.md, src/pages/enterprise/setup.md, src/pages/native.md
Migrate some Install instructions into new Setup page
=> (native): Add Setup and Quickstart pages

src/pages/enterprise/geolocation.md
This PR fixes a code formatting issue in markdown page for Geolocation.
Page that's been affected is:
https://ionicframework.com/docs/enterprise/geolocation#classes
Path to the source file: src/pages/enterprise/geolocation.md
I haven't touched the other languages (FR, ES etc.) to keep this PR simple. Let me know if those needed to be updated as well.
=> Fix markdown code formatting

src/pages/appflow/deploy/api.md
MAX_VERSIONS variable has no effect, the variable in the config.xml is MAX_STORE
Also, the value assigned in the documentation was 'production'. The value has to be an integer
=> update max versions

src/pages/enterprise/auth-connect.md
* Fixing incorrect plugin-id for Ionic Auth Connect
=> fix(native): Fix plugin-id for Auth Connect

src/components/native-ent-install/native-ent-install.tsx, src/pages/enterprise/auth-connect.md, src/pages/enterprise/setup.md
- Remove cordova variables from Capacitor instructions
- Setup: clarify Capacitor details including new notes on manual native project configuration
- Update Auth connect cap install details.
=> Ionic Native: Update capacitor install details

src/pages/react/lifecycle.md
Added closing braces for the HomeApp React component before exporting the component
=> Close the HomeApp Component

src/assets/locales/en/messages.json, src/components/menu/templates/main.tsx, src/pages/intro/browser-support.md, src/pages/intro/first-app.md, src/pages/intro/what-are-progressive-web-apps.md, src/pages/publishing/progressive-web-app.md
Porting the old page over from 
https://ionicframework.com/docs/v3/developer-resources/progressive-web-apps/
=> What are PWAs

src/pages/developer-resources/courses.md
- Added the new Electron Course.
- Removed old Electron Course.
- Updated the verbiage to match what's on Pluralsight's pages.
=> Updated Mike's Pluralsight Courses

src/pages/enterprise/camera.md
=> docs(enterprise): Update camera docs adding preferences

src/pages/enterprise/splashscreen.md
=> docs(enterprise): Update Splashscreen docs adding preferences

src/pages/angular/pwa.md
One sentence was repeated twice
=> Duplicated line to delete

src/pages/enterprise/couchbase-lite.md
Update the generated file for couchbase-lite plugin. Any required changes should be done in the  plugin repository.
Removed the "## Reference Apps" sections since they use offline-storage plugin, they should probably be updated and they we can link them back.
=> docs(enterprise): Update couchbase-lite file

src/pages/appflow/quickstart/ionic-remote.md
- Adding a note about the `ionic git remote` command to the Appflow docs
=> docs(appflow): Adding note about ionic git remote command

scripts/data/native.json
- Remove the @ionic-native/pro wrapper from docs
=> docs(native): Remove @ionic-native/pro wrapper page

src/pages/enterprise/offline-storage.md, src/pages/enterprise/offline-storage/1.0.X/offline-storage.md
Add the new offline-storage file and moves the old one to 1.0.X folder
=> docs(enterprise): update offline-storage file with 2.x version

src/pages/angular/your-first-app/3-saving-photos.md
=> Add missing step for savePicture usage

CONTRIBUTING.md, scripts/data/cli.json, src/components/menu/templates/cli.tsx, src/pages/angular/your-first-app.md, src/pages/building/android.md, src/pages/building/ios.md, src/pages/building/running.md, src/pages/building/scaffolding.md, src/pages/building/starting.md, src/pages/building/webview.md, src/pages/cli.md, src/pages/cli/livereload.md, src/pages/developer-resources/guides/first-app-v3/intro.md, src/pages/developer-resources/guides/first-app-v4/intro.md, src/pages/enterprise/setup.md, src/pages/faq/glossary.md, src/pages/faq/tips.md, src/pages/installation/android.md, src/pages/installation/cli.md, src/pages/installation/environment.md, src/pages/installation/ios.md, src/pages/intro/concepts.md, src/pages/native/community.md, src/pages/pt/angular/your-first-app.md, src/pages/react.md, src/pages/react/overview.md, src/pages/react/quickstart.md, src/pages/react/your-first-app.md
=> Ionic CLI 6 Documentation Changes

src/pages/enterprise/auth-connect.md
This note is to work around an issue found here: https://ionic-cloud.atlassian.net/browse/SE-128?atlOrigin=eyJpIjoiNDUwMGI4NWI0MmVkNDdmNGIzYjM1M2E4YTNhYWRkNTMiLCJwIjoiaiJ9
=> doc(auth-connect): add a note about Edge support

src/pages/intro/browser-support.md
- Updated supported browser version tables for mobile and desktop
=> fix(browser-support): Updated supported browser version tables

src/pages/enterprise/auth-connect.md
Update the file to include 1.5.0 release notes and new general type information
=> docs(enterprise): update auth-connect plugin file

src/pages/publishing/play-store.md
Path is now android/app/build/outputs/apk
=> android apk location modified

src/components/menu/templates/components.tsx
Missing changes related to the move from Ionic v4 to v5
=> fix(components): Remove anchor & nav stuff, add nav-link

src/pages/contributing/how-to-contribute.md
blocked by https://github.com/ionic-team/ionic/pull/21117
=> docs(contributing): add guide on how to create a good code reproduction

src/pages/appflow/cookbook/phonegap-build-migration.md
This step is for allowing live reload on localhost url, not for accessing external APIs
=> chore(appflow-pgb): remove unnecessary step

src/pages/utilities/gestures.md
blocked by https://github.com/ionic-team/ionic/pull/20638
=> docs(gesture): add blurOnStart feature

src/pages/utilities/animations.md
blocked by https://github.com/ionic-team/ionic/pull/20940
=> docs(animation): update destroy and progressStart method docs

src/pages/utilities/gestures.md
blocked by https://github.com/ionic-team/ionic/pull/20685
=> docs(gesture): note that gestures do not run in NgZone by default

src/pages/react/your-first-app/4-loading-photos.md
In the loadSaved() method we can use the PHOTO_STORAGE constant already declared, instead of the 'photos' string.
=> Use PHOTO_STORAGE constant

src/pages/developer-resources/books.md
Added Learning Ionic and Learning Ionic second edition
=> Added Learning Ionic

src/pages/cli/configuration.md
[Change log Ionic CLI release 6.9.0](https://github.com/ionic-team/ionic-cli/blob/develop/packages/%40ionic/cli/CHANGELOG.md#690-2020-05-11)
=> Update in relation to Ionic CLI release 6.9.0

src/assets/locales/en/messages.json, src/pages/appflow/destinations/cli.md
I also cleaned up the formatting of the document a bit to make it more
pretty, debatably.
=> doc(dtas): add some extra configuration options

src/components/menu/templates/enterprise.tsx, src/pages/enterprise/auth-connect.md, src/pages/enterprise/auth-connect/okta.md
Adds documentation for Okta provider that was added in version 2.2.0 version of Auth Connect
=> doc(auth-connect): Add docs for configuring Okta provider

scripts/data/native.json
Resulting file generated from [this PR](https://github.com/ionic-team/ionic-native/pull/3453).
=> Update community native plugin list

src/pages/developer-resources/posts.md
Added and updated some IonicThemes tutorials.
=> docs(posts): add community posts

src/pages/appflow/package/adding-credentials.md
First time appflow user, and I got stuck here for a while. This addition
would have got me through this quickly, I think.
=> Add iOS details for adding a profile

src/pages/theming/dark-mode.md
blocked by https://github.com/ionic-team/ionic-framework/pull/21756
merge after framework 5.3 ships
=> docs(theming): add card css variable for dark mode

src/pages/cli/configuration.md
Docs for https://github.com/ionic-team/ionic-cli/pull/4496
=> update docs for new capacitor sync hook

src/pages/enterprise/contacts.md, src/pages/enterprise/contacts/1.0.X/contacts.md
This branch updates the documentation for the enterprise-contacts plugin. It uses the new custom theme for generation and includes the 1.0.x -> 1.1.x transition that was never published.
=> Updating the enterprise-contacts plugin docs.

src/pages/reference/support.md
MIgration guide is available here : 
https://ionicframework.com/docs/reference/migration
=> Fixed a broken link

src/pages/angular/your-first-app/3-saving-photos.md
classes have methods, functions are standalone blocks of code that are specifically not associated with objects (classes)
we should strive to use appropriate naming conventions where possible, especially where confusion may ensue when using the wrong term, e.g. if we're being told to create a function, this would be created _outside_ of the class
=> clarify code block type

src/pages/react/your-first-app/4-loading-photos.md
I think there was a typo on the docs. I think it should be "our" instead of "are".
=> Grammar error 

src/pages/angular/your-first-app/2-taking-photos.md, src/pages/angular/your-first-app/3-saving-photos.md, src/pages/angular/your-first-app/4-loading-photos.md
remove unnecessary base64 code and other cleanups
=> Photo gallery angular: clean up code

src/pages/angular/your-first-app/2-taking-photos.md
There is no any variable `photos` in relevant component. So it must be referred from `photoService`.
=> Add call to photos variable from photoService

scripts/data/cli.json
see https://github.com/ionic-team/ionic-cli/pull/4574
=> Ionic CLI documentation changes

src/pages/appflow/build-stacks.md
* the UI for eol build stacks is still in progress, an image of what that looks like will be added when that feature is complete
=> CT-186 update build stack docs with more info

src/pages/vue/lifecycle.md
In support of https://github.com/ionic-team/ionic-framework/pull/22241
=> docs(vue): update lifecycle usage

src/pages/react/navigation.md
Router outlets can be nested in Ionic React.
=> docs(react): remove inaccurate router outlet info

src/pages/react/navigation.md
See https://github.com/ionic-team/ionic-framework/pull/23009
=> docs(react): remove incorrect IonPage information

src/pages/vue/lifecycle.md
Blocked by https://github.com/ionic-team/ionic-framework/pull/22970
=> docs(vue): add composition api lifecycle hook examples

src/pages/intro/cdn.md
=> removed version number from ionicons cdn

package-lock.json, package.json
Bump Ionic Framework to v5.6.4
=> chore(): bump framework version

src/assets/locales/en/messages.json, src/components/menu/templates/main.tsx, src/pages/angular/performance.md, src/pages/react/performance.md, src/pages/vue/performance.md
Inspired by this issue in Framework: https://github.com/ionic-team/ionic-framework/issues/22775#issuecomment-849028954
=> docs(): add performance docs for angular, react, and vue on using loops with ionic components

scripts/build-pages/markdown-renderer/code.ts, src/assets/locales/en/messages.json, src/components/code/prismjs-theme.css, src/components/menu/templates/main.tsx, src/pages/angular/virtual-scroll.md
Add initial virtual scroll docs for angular.
=> docs(): add virtual scroll docs

src/pages/reference/browser-support.md, src/pages/reference/support.md
Related: https://github.com/ionic-team/ionic-framework/pull/23443
=> docs(support): update support docs with v6

src/pages/vue/navigation.md
Do not merge until Framework v5.6.10 (this week)
=> docs(vue): update usage on router outlet with tabs

docs/utilities/animations.md
https://github.com/ionic-team/ionic-docs/issues/1930
=> docs(animation): fix usage examples and interface

docs/utilities/animations.md
https://github.com/ionic-team/ionic-docs/issues/1930
=> docs(animation): add correct progressStart interface

docs/react/pwa.md
I noticed that there are other PRs for other typos/mistakes back from Feb. It worries me that noone is accepting PRs for documentation fixes. I hesitated to create this one. Should I even bother with any more PRs?
=> Fix Typos and Other Mistakes

versioned_docs/version-v5/api/toggle.md
It appears there was a copy/paste error, or I misunderstand the code.
=> Use different toppings in Toggle doc

src/pages/deployment/play-store.md
the url is wrong, should be deployment instead of publishing
also, should start with `/`
=> fix deploy to app store link

docs/angular/config.md, docs/angular/platform.md, docs/react/config.md, docs/react/platform.md, docs/vue/config.md, docs/vue/platform.md
Adding docs for this PR in Framework: https://github.com/ionic-team/ionic-framework/pull/23915
=> docs(config, platform): add custom platform detection docs

src/pages/react/quickstart.md
Resolves https://github.com/ionic-team/ionic-docs/issues/1384 for the legacy branch. Content update is the same as https://github.com/ionic-team/ionic-docs/pull/2073/files.
=> docs(react): add icons usage to legacy quickstart

static/demos/api/accordion/index.html, static/demos/api/breadcrumbs/index.html, static/demos/api/datetime/index.html, static/demos/api/modal/index.html
Also see https://github.com/ionic-team/ionic-framework/pull/24104
=> docs(): add new Ionic 6 examples that match usage

docs/angular/slides.md, docs/react/slides.md, docs/vue/slides.md
Do not merge until Ionic 6 RC 3 ships.
=> docs(slides): add Swiper 7 migration guide

docs/react/config.md, docs/react/platform.md
See https://github.com/ionic-team/ionic-framework/pull/24254
Do not merge until Ionic 6 RC 4 is released
=> docs(react): update correct config usage for Ionic 6

docs/intro/upgrading-to-ionic-6.md, docs/reference/browser-support.md, docs/reference/migration.md, sidebars.js
Do not merge until RC 4 is out.
=> docs(): add ionic 6 migration guide

docs/angular/your-first-app/7-live-reload.md, docs/react/your-first-app/2-taking-photos.md, docs/react/your-first-app/3-saving-photos.md, docs/vue/your-first-app/2-taking-photos.md, docs/vue/your-first-app/3-saving-photos.md, docs/vue/your-first-app/7-live-reload.md, versioned_docs/version-v5/angular/your-first-app/7-live-reload.md, versioned_docs/version-v5/react/your-first-app/2-taking-photos.md, versioned_docs/version-v5/react/your-first-app/3-saving-photos.md, versioned_docs/version-v5/vue/your-first-app/2-taking-photos.md, versioned_docs/version-v5/vue/your-first-app/3-saving-photos.md, versioned_docs/version-v5/vue/your-first-app/7-live-reload.md
Photo was replaced with UserPhoto, but it was missed in a few places.
I think this covers all missing places.
=> fix: Change remaining usages of Photo with UserPhoto

src/components/global/Playground/index.tsx, src/components/global/Playground/playground.css
Introduces the ability to toggle the visibility of the code block.
<video src="https://user-images.githubusercontent.com/13732623/153088863-fd67519e-9347-4563-ae58-691ad34592c7.mp4"></video>
Split from #2185 continuation of #2189
=> feat(playground): toggle source code visibility

docs/reference/support.md
=> docs(support): fix typo for support status

src/components/global/Playground/index.tsx
This PR changes the behavior of the code snippet area to automatically expand when a user changes the selected language.
=> fix(playground): changing language now show code

docs/core-concepts/what-are-progressive-web-apps.md, docs/react/performance.md, scripts/data/meta-override.json
fix a few past implementations and complete docs updates through April 14
=> chore(titan updates): updates through 0414

docs/vue/your-first-app/8-distribute.md
\cc @liamdebeasi and @amandaejohnston
=> docs(vue): Fix small misspell for distribute page

versioned_docs/version-v5/native/image-picker.md
Fix wrong unwanted escape characters
=> docs(v5): fix native image picker usage example

docs/api/select.md, static/usage/select/interfaces/action-sheet/angular.md, static/usage/select/interfaces/action-sheet/demo.html, static/usage/select/interfaces/action-sheet/index.md, static/usage/select/interfaces/action-sheet/javascript.md, static/usage/select/interfaces/action-sheet/react.md, static/usage/select/interfaces/action-sheet/vue.md, static/usage/select/interfaces/popover/angular.md, static/usage/select/interfaces/popover/demo.html, static/usage/select/interfaces/popover/index.md, static/usage/select/interfaces/popover/javascript.md, static/usage/select/interfaces/popover/react.md, static/usage/select/interfaces/popover/vue.md
Adds Action Sheet and Popover interface playgrounds.
=> docs(select): add interface playgrounds

docs/utilities/animations.md
Fixes a few small issues with the code snippets on this page: https://ionicframework.com/docs/utilities/animations#modals
=> docs(animations): update code snippets for modal animations

docs/api/select.md, static/usage/select/customization/button-text/angular.md, static/usage/select/customization/button-text/demo.html, static/usage/select/customization/button-text/index.md, static/usage/select/customization/button-text/javascript.md, static/usage/select/customization/button-text/react.md, static/usage/select/customization/button-text/vue.md, static/usage/select/customization/interface-options/angular/app.component_html.md, static/usage/select/customization/interface-options/angular/app.component_ts.md, static/usage/select/customization/interface-options/demo.html, static/usage/select/customization/interface-options/index.md, static/usage/select/customization/interface-options/javascript.md, static/usage/select/customization/interface-options/react.md, static/usage/select/customization/interface-options/vue.md, static/usage/select/customization/styling-select/angular/angular-css.md, static/usage/select/customization/styling-select/angular/angular-html.md, static/usage/select/customization/styling-select/angular/angular-ts.md, static/usage/select/customization/styling-select/demo.html, static/usage/select/customization/styling-select/index.md, static/usage/select/customization/styling-select/javascript.md, static/usage/select/customization/styling-select/react/react-css.md, static/usage/select/customization/styling-select/react/react-ts.md, static/usage/select/customization/styling-select/vue.md
Adds the following playgrounds:
- Button Text
- Interface Options
- Styling the Select
Also removes some usage code that is no longer needed.
=> docs(select): add customization playgrounds

static/demos/api/alert/index.html
I was reading the [docs](https://ionicframework.com/docs/api/alert) and checking the source code, then my eyes started hurting...
=> docs(alert): fix demo source code

docs/api/select.md, static/usage/select/objects-as-values/multiple-selection/angular/app.component_html.md, static/usage/select/objects-as-values/multiple-selection/angular/app.component_ts.md, static/usage/select/objects-as-values/multiple-selection/demo.html, static/usage/select/objects-as-values/multiple-selection/index.md, static/usage/select/objects-as-values/multiple-selection/javascript.md, static/usage/select/objects-as-values/multiple-selection/react.md, static/usage/select/objects-as-values/multiple-selection/vue.md, static/usage/select/objects-as-values/using-comparewith/angular/app.component_html.md, static/usage/select/objects-as-values/using-comparewith/angular/app.component_ts.md, static/usage/select/objects-as-values/using-comparewith/demo.html, static/usage/select/objects-as-values/using-comparewith/index.md, static/usage/select/objects-as-values/using-comparewith/javascript.md, static/usage/select/objects-as-values/using-comparewith/react.md, static/usage/select/objects-as-values/using-comparewith/vue.md
Adds two playgrounds for demonstrating objects as values, with single or multiple selection.
=> docs(select): add objects as values playgrounds

docs/api/modal.md, src/components/page/reference/ReleaseNotes/release-notes.json, static/usage/modal/controller/angular/app_component_html.md, static/usage/modal/controller/angular/app_component_ts.md, static/usage/modal/controller/angular/app_module_ts.md, static/usage/modal/controller/angular/modal-example_component_html.md, static/usage/modal/controller/angular/modal-example_component_ts.md, static/usage/modal/controller/demo.html, static/usage/modal/controller/index.md, static/usage/modal/controller/javascript.md, static/usage/modal/controller/react.md, static/usage/modal/controller/vue/example_vue.md, static/usage/modal/controller/vue/modal_vue.md
Re-approach to the controller modal component playground example.
This PR is in favor of: #2315 and #2319.
=> docs(modal): controller playground

docs/angular/slides.md
i just want to edit slide 3 double to slide 2
=> Update double slide 3

docs/api/accordion.md, static/usage/accordion/disable-group/angular.md, static/usage/accordion/disable-group/demo.html, static/usage/accordion/disable-group/index.md, static/usage/accordion/disable-group/javascript.md, static/usage/accordion/disable-group/react.md, static/usage/accordion/disable-group/vue.md, static/usage/accordion/disable-individual/angular.md, static/usage/accordion/disable-individual/demo.html, static/usage/accordion/disable-individual/index.md, static/usage/accordion/disable-individual/javascript.md, static/usage/accordion/disable-individual/react.md, static/usage/accordion/disable-individual/vue.md
Adds playgrounds for disabling individual accordions and entire accordion groups.
=> docs(accordion): add disabled playgrounds

docs/api/breadcrumbs.md, static/usage/breadcrumbs/styling/color/angular.md, static/usage/breadcrumbs/styling/color/demo.html, static/usage/breadcrumbs/styling/color/index.md, static/usage/breadcrumbs/styling/color/javascript.md, static/usage/breadcrumbs/styling/color/react.md, static/usage/breadcrumbs/styling/color/vue.md, static/usage/breadcrumbs/styling/css-props/angular/angular_css.md, static/usage/breadcrumbs/styling/css-props/angular/angular_html.md, static/usage/breadcrumbs/styling/css-props/demo.html, static/usage/breadcrumbs/styling/css-props/index.md, static/usage/breadcrumbs/styling/css-props/javascript.md, static/usage/breadcrumbs/styling/css-props/react/react_css.md, static/usage/breadcrumbs/styling/css-props/react/react_ts.md, static/usage/breadcrumbs/styling/css-props/vue.md
Adds the Color Property and CSS Properties playgrounds.
=> docs(breadcrumbs): add styling playgrounds

docs/api/accordion.md, static/usage/accordion/listen-changes/angular-html.md, static/usage/accordion/listen-changes/angular-ts.md, static/usage/accordion/listen-changes/demo.html, static/usage/accordion/listen-changes/index.md, static/usage/accordion/listen-changes/javascript.md, static/usage/accordion/listen-changes/react.md, static/usage/accordion/listen-changes/vue.md, static/usage/accordion/multiple/angular.md, static/usage/accordion/multiple/demo.html, static/usage/accordion/multiple/index.md, static/usage/accordion/multiple/javascript.md, static/usage/accordion/multiple/react.md, static/usage/accordion/multiple/vue.md, static/usage/accordion/toggle/angular-html.md, static/usage/accordion/toggle/angular-ts.md, static/usage/accordion/toggle/demo.html, static/usage/accordion/toggle/index.md, static/usage/accordion/toggle/javascript.md, static/usage/accordion/toggle/react.md, static/usage/accordion/toggle/vue.md
Adds the following playgrounds:
- Programmatically toggling accordions
- Listening for ionChange
- Showing multiple accordions at a time
=> docs(playground): add remaining basic usage

docs/react/your-first-app.md, docs/vue/your-first-app.md, versioned_docs/version-v5/react/your-first-app.md, versioned_docs/version-v5/vue/your-first-app.md
replace Tabs.vue with TabsPage.vue as that's the current name of the file
add missing step on vue tutorials replacing ellipse with image on setup method
add some clarifications about deleting/replacing ellipse with image
=> docs: Add some improvements to your first app tutorials

docs/index.md
=> fix(docs): Add correct file extensions linking from Intro

src/components/global/Playground/index.tsx
Got some feedback (https://forum.ionicframework.com/t/problem-loading-example-docs/224503/6) that our soft launch of the playgrounds is causing a bit of slow downs. We have previously discussed lazily loading the playground content, so I made a PR to do that to alleviate some of the performance issues.
=> fix(playground): lazy load playgrounds

docs/api/loading.md, static/code/stackblitz/html/index.ts, static/usage/loading/spinners/angular/html.md, static/usage/loading/spinners/angular/ts.md, static/usage/loading/spinners/demo.html, static/usage/loading/spinners/index.md, static/usage/loading/spinners/javascript.md, static/usage/loading/spinners/react.md, static/usage/loading/spinners/vue.md, static/usage/loading/theming/angular/css.md, static/usage/loading/theming/angular/html.md, static/usage/loading/theming/angular/ts.md, static/usage/loading/theming/demo.html, static/usage/loading/theming/index.md, static/usage/loading/theming/javascript.md, static/usage/loading/theming/react.md, static/usage/loading/theming/react/css.md, static/usage/loading/theming/react/tsx.md, static/usage/loading/theming/vue.md
- Add playground for how to set custom spinners
- Add playground for how to theme loading
=> docs(loading): add spinners and theming playground

docs/layout/structure.md
Changed 'for React' to 'in React'.
=> chore(layout): fix react typo

docs/api/alert.md, static/usage/alert/customization/angular/angular_css.md, static/usage/alert/customization/angular/angular_html.md, static/usage/alert/customization/angular/angular_ts.md, static/usage/alert/customization/demo.html, static/usage/alert/customization/index.md, static/usage/alert/customization/javascript.md, static/usage/alert/customization/react/react_css.md, static/usage/alert/customization/react/react_ts.md, static/usage/alert/customization/vue.md
Adds the Customization playground and removes a couple of dead anchor links from the docs.
=> docs(alert): add customization playground

docs/api/alert.md, static/usage/alert/customization/angular/angular_css.md, static/usage/alert/customization/angular/angular_html.md, static/usage/alert/customization/angular/angular_ts.md, static/usage/alert/customization/demo.html, static/usage/alert/customization/index.md, static/usage/alert/customization/javascript.md, static/usage/alert/customization/react/react_css.md, static/usage/alert/customization/react/react_ts.md, static/usage/alert/customization/vue.md, static/usage/alert/inputs/radios/angular/angular_html.md, static/usage/alert/inputs/radios/angular/angular_ts.md, static/usage/alert/inputs/radios/demo.html, static/usage/alert/inputs/radios/index.md, static/usage/alert/inputs/radios/javascript.md, static/usage/alert/inputs/radios/react.md, static/usage/alert/inputs/radios/vue.md, static/usage/alert/inputs/text-inputs/angular/angular_html.md, static/usage/alert/inputs/text-inputs/angular/angular_ts.md, static/usage/alert/inputs/text-inputs/demo.html, static/usage/alert/inputs/text-inputs/index.md, static/usage/alert/inputs/text-inputs/javascript.md, static/usage/alert/inputs/text-inputs/react.md, static/usage/alert/inputs/text-inputs/vue.md
Adds the Text Inputs and Radios playgrounds.
=> docs(alert): add inputs playgrounds

static/code/stackblitz/react/package-lock.json, static/code/stackblitz/vue/package-lock.json
Updates the dependency lock for all playground examples (React & Vue).
=> fix(playground): update react & vue dependencies

static/usage/range/css-shadow-parts/angular/app_component_css.md, static/usage/range/css-shadow-parts/demo.html, static/usage/range/css-shadow-parts/javascript.md, static/usage/range/css-shadow-parts/react/main_css.md, static/usage/range/css-shadow-parts/vue.md
=> docs(range): incomplete css pseudo-element text

docs/angular/your-first-app.md, docs/angular/your-first-app/2-taking-photos.md, docs/angular/your-first-app/4-loading-photos.md, docs/angular/your-first-app/5-adding-mobile.md, docs/angular/your-first-app/7-live-reload.md, docs/react/your-first-app.md, docs/react/your-first-app/2-taking-photos.md, docs/react/your-first-app/4-loading-photos.md, docs/react/your-first-app/5-adding-mobile.md, docs/react/your-first-app/7-live-reload.md, docs/vue/your-first-app.md, docs/vue/your-first-app/2-taking-photos.md, docs/vue/your-first-app/4-loading-photos.md, docs/vue/your-first-app/5-adding-mobile.md, docs/vue/your-first-app/7-live-reload.md, versioned_docs/version-v5/angular/your-first-app.md, versioned_docs/version-v5/angular/your-first-app/2-taking-photos.md, versioned_docs/version-v5/angular/your-first-app/4-loading-photos.md, versioned_docs/version-v5/angular/your-first-app/5-adding-mobile.md, versioned_docs/version-v5/angular/your-first-app/7-live-reload.md, versioned_docs/version-v5/react/your-first-app.md, versioned_docs/version-v5/react/your-first-app/2-taking-photos.md, versioned_docs/version-v5/react/your-first-app/4-loading-photos.md, versioned_docs/version-v5/react/your-first-app/5-adding-mobile.md, versioned_docs/version-v5/react/your-first-app/7-live-reload.md, versioned_docs/version-v5/vue/your-first-app.md, versioned_docs/version-v5/vue/your-first-app/2-taking-photos.md, versioned_docs/version-v5/vue/your-first-app/4-loading-photos.md, versioned_docs/version-v5/vue/your-first-app/5-adding-mobile.md, versioned_docs/version-v5/vue/your-first-app/7-live-reload.md
closes https://github.com/ionic-team/ionic-docs/issues/2491
=> docs(your-first-app): Replace Storage plugin with Preferences

docs/angular/navigation.md
Documents the usage of standalone components with routing in Angular.
Preview link: https://ionic-docs-git-docs-angular-standalone-routing-ionic1.vercel.app/docs/angular/navigation#standalone-components
=> docs(angular): standalone component api

docs/vue/your-first-app/6-deploying-mobile.md
**URL:**
[https://ionicframework.com/docs/vue/your-first-app/deploying-mobile#capacitor-setup](https://ionicframework.com/docs/vue/your-first-app/deploying-mobile#capacitor-setup)
**Example:** 
```
$ ionic cap add ios
$ ionic cap add android
```
=> Remove $ from shell snippet code

static/usage/alert/buttons/vue.md, static/usage/alert/customization/vue.md, static/usage/alert/inputs/radios/vue.md, static/usage/alert/inputs/text-inputs/vue.md, static/usage/alert/presenting/controller/vue.md
Update the `ion-alert` vue playground examples to use the CompositionAPI.
=> docs(alert): use composition api for vue examples

docs/vue/navigation.md, docs/vue/utility-functions.md
- Updates the structure and documentation surrounding Vue Routing and `useIonRouter`. 
- Organizes the usage examples within the "Utility Functions" page
Related issue: https://github.com/ionic-team/ionic-framework/issues/26062
Quick links:
- https://ionic-docs-git-docs-vue-routing-ionic1.vercel.app/docs/vue/navigation#functions
- https://ionic-docs-git-docs-vue-routing-ionic1.vercel.app/docs/vue/utility-functions#functions
=> docs(vue): useIonRouter description and usage

docs/api/split-pane.md
- Removes inline TOC
- Shows sidebar TOC
- Removes code usage
- Adds playground headings
=> docs(split-pane): add setup

docs/reference/browser-support.md
As part of https://github.com/ionic-team/ionic-framework/pull/26461, we will be bumping the minimum Firefox version from v63 to v70 for Ionic v7.
=> docs(browser-support): update min firefox version to 70

static/code/stackblitz/v7/angular/package.json, static/code/stackblitz/v7/html/package.json, static/code/stackblitz/v7/react/package.json, static/code/stackblitz/v7/vue/package.json, static/usage/v7/input/basic/demo.html, static/usage/v7/input/clear/demo.html, static/usage/v7/input/counter/demo.html, static/usage/v7/input/fill/demo.html, static/usage/v7/input/helper-error/demo.html, static/usage/v7/input/labels/demo.html, static/usage/v7/input/theming/colors/demo.html, static/usage/v7/input/theming/css-properties/demo.html, static/usage/v7/input/types/demo.html, static/usage/v7/toast/buttons/demo.html, static/usage/v7/toast/icon/demo.html, static/usage/v7/toast/inline/basic/demo.html, static/usage/v7/toast/inline/is-open/demo.html, static/usage/v7/toast/theming/demo.html, static/usage/v7/toggle/basic/demo.html, static/usage/v7/toggle/justify/demo.html, static/usage/v7/toggle/label-placement/demo.html, static/usage/v7/toggle/list/demo.html, static/usage/v7/toggle/on-off/demo.html, static/usage/v7/toggle/theming/colors/demo.html, static/usage/v7/toggle/theming/css-properties/demo.html, static/usage/v7/toggle/theming/css-shadow-parts/demo.html
Updates the v7 demos to the latest v7 pre-release
=> docs(deps): update to latest v7 beta

versioned_docs/version-v6/reference/support.md
This data got lost when we versioned the docs.
=> docs(support): update version support

static/usage/v6/toast/layout/index.md
Forgot to add a version to this playground.
=> docs(toast): add version to layout

static/usage/v6/toast/layout/demo.html
I did not update the modalController module import to be the latest version of v6.
=> docs(toast): update cdn version

static/usage/v6/select/typeahead/angular/modal-example_component_ts.md, static/usage/v6/select/typeahead/demo.html, static/usage/v6/select/typeahead/javascript.md, static/usage/v6/select/typeahead/react/typeahead_component_tsx.md, static/usage/v6/select/typeahead/vue/typeahead_component_vue.md, static/usage/v7/select/typeahead/angular/modal-example_component_ts.md, static/usage/v7/select/typeahead/demo.html, static/usage/v7/select/typeahead/javascript.md, static/usage/v7/select/typeahead/react/typeahead_component_tsx.md, static/usage/v7/select/typeahead/vue/typeahead_component_vue.md
See https://github.com/ionic-team/ionic-docs/pull/2832
Co-author-credit:
```
Co-authored-by: BlackHakwDC <BlackHakwDC@users.noreply.github.com>
```
=> docs(select): fix typeahead search

docs/react/your-first-app.md
While following your instructions, my app did not produce an `index.tsx` file. You may want it to be `main.tsx` instead.
=> docs(react): update pwa-elements import

src/components/page/theming/ColorAccordion/index.tsx, src/components/page/theming/LayeredColorsSelect/index.tsx
Same as https://github.com/ionic-team/ionic-docs/pull/2940, just a couple more spots I missed.
=> fix(ColorAccordion, LayeredColorsSelect): add keys to list items

docs/developing/tips.md, versioned_docs/version-v5/developing/tips.md, versioned_docs/version-v6/developing/tips.md
This PR is in favor of: https://github.com/ionic-team/ionic-docs/pull/2116
Ported the same changes to the v6 and v5 docs as well.
=> docs(developing): tip for changing node_modules permissions

static/code/stackblitz/v7/react/package-lock.json, static/code/stackblitz/v7/react/package.json, static/code/stackblitz/v7/vue/package-lock.json, static/code/stackblitz/v7/vue/package.json
Updates the component playground dependencies for React and Vue.
=> chore(deps): update react and vue playground dependencies

docs/angular/your-first-app/5-adding-mobile.md
Resolves [#2986](https://github.com/ionic-team/ionic-docs/issues/2986)
- Added fileName in readAsBase64
=> docs(angular):updated component photo service (#2986)

docs/native-faq.md
=> docs(native): improve grammar

renovate.json
Resolves #3024
Removes invalid extends configuration.
=> chore(renovate): remove extending docs config

docs/react/quickstart.md, docs/vue/quickstart.md
added 'to get started' instead of 'to begin'
=> docs(quickstart): change wording for installing CLI

docs/api/action-sheet.md, docs/api/alert.md, docs/api/toast.md
Blocked on the Ionic 7.3 release
=> chore: merge feature-7.3 documentation

docs/reference/support.md, versioned_docs/version-v5/reference/support.md, versioned_docs/version-v6/reference/support.md
I went and updated the support tables for the versioned docs too. If you have a better approach than just updating the tables, I'm open to ideas.
=> chore(support): update support table

static/usage/v6/fab/basic/vue.md, static/usage/v7/fab/basic/vue.md
No ticket, I just found this while testing renovate PRs
=> fix(fab): remove unused component from playground

docs/react/your-first-app/7-live-reload.md
Set return order of usePhotoGallery the same as expected in Tab2
=> docs(react): update live reload steps to fix order in return

static/usage/v7/radio/using-comparewith/demo.html
I happened to notice that this demo wasn't working correctly.
=> docs(radio): fix radio demo

docs/reference/support.md
There was some confusion internally about what "Extended Support" entails. Damian proposed adding the term "maintenance" to resolve.
See https://ionic-cloud.atlassian.net/browse/FW-5766
=> docs(support): revise wording

docs/api/refresher.md, static/usage/v7/refresher/custom-scroll-target/angular/example_component_css.md, static/usage/v7/refresher/custom-scroll-target/demo.html, static/usage/v7/refresher/custom-scroll-target/javascript.md, static/usage/v7/refresher/custom-scroll-target/react/main_css.md, static/usage/v7/refresher/custom-scroll-target/vue.md, static/usage/v8/refresher/custom-scroll-target/angular/example_component_css.md, static/usage/v8/refresher/custom-scroll-target/demo.html, static/usage/v8/refresher/custom-scroll-target/javascript.md, static/usage/v8/refresher/custom-scroll-target/react/main_css.md, static/usage/v8/refresher/custom-scroll-target/vue.md, versioned_docs/version-v7/api/refresher.md
This is the same as https://github.com/ionic-team/ionic-docs/pull/3345 but targets Ionic 8.
=> docs(refresher): add rubber band effect for virtual scroll

static/usage/v6/datetime/highlightedDates/array/demo.html, static/usage/v6/datetime/highlightedDates/callback/demo.html, static/usage/v6/modal/custom-dialogs/demo.html, static/usage/v7/layout/dynamic-font-scaling/demo.html
Some of our demos are using dev builds still, this updates them to the latest major version.
=> chore(playgrounds): update demos to use latest major version 

static/usage/v7/input/mask/angular/app_module_ts.md, static/usage/v7/input/mask/angular/example_component_ts.md, static/usage/v7/input/mask/index.md
Learn more:
* https://github.com/taiga-family/maskito/releases/tag/v2.0.0
=> docs(input): update `Maskito` documentation (according to the latest major release `2.0.0`)

package-lock.json, package.json
Upgrading to be the same as the Vercel setting.
=> chore(node): upgrade to v20

docs/theming/css-variables.md
React project also generates the `variables.css` file.
=> Update css-variables.md for adding React reference. 

docs/updating/8-0.md
Vue Upgrade steps went from 1 to 3 when it should have gone from 1 to 2.
=> chore: fix numbering

docs/theming/basics.md
=> docs(theming): update CSS properties to CSS custom properties

static/usage/v7/theming/automatic-dark-mode/react/main_tsx.md, static/usage/v7/theming/manual-dark-mode/react/main_tsx.md, static/usage/v8/theming/class-dark-mode/react/main_tsx.md, static/usage/v8/theming/class-high-contrast-mode/react/main_tsx.md
=> docs(theming): clean up event listeners in React demos

docusaurus.config.js, src/styles/custom.scss
This PR:
- Adds OS announcement bar to config
- Adds OS announcement bar styles
=> feat(): os announcement bar config and styles

static/usage/v7/radio/using-comparewith/demo.html
=> docs(radio): use correct paths for Object Value References playground

docs/react.md, docs/react/performance.md, docs/react/quickstart.md, docs/react/your-first-app/2-taking-photos.md
Update the links from https://reactjs.org to https://react.dev
=> docs(react): update documentation url

docs/api/segment-content.md, docs/api/segment-view.md, docs/api/segment.md, docs/api/select.md, sidebars.js, static/usage/v8/segment/swipeable/angular/angular_css.md, static/usage/v8/segment/swipeable/angular/angular_html.md, static/usage/v8/segment/swipeable/demo.html, static/usage/v8/segment/swipeable/index.md, static/usage/v8/segment/swipeable/javascript.md, static/usage/v8/segment/swipeable/react/react_css.md, static/usage/v8/segment/swipeable/react/react_tsx.md, static/usage/v8/segment/swipeable/vue.md, static/usage/v8/select/customization/interface-options/angular/example_component_html.md, static/usage/v8/select/customization/interface-options/angular/example_component_ts.md, static/usage/v8/select/customization/interface-options/demo.html, static/usage/v8/select/customization/interface-options/javascript.md, static/usage/v8/select/customization/interface-options/react.md, static/usage/v8/select/customization/interface-options/vue.md, static/usage/v8/select/interfaces/modal/angular.md, static/usage/v8/select/interfaces/modal/demo.html, static/usage/v8/select/interfaces/modal/index.md, static/usage/v8/select/interfaces/modal/javascript.md, static/usage/v8/select/interfaces/modal/react.md, static/usage/v8/select/interfaces/modal/vue.md
=> docs(): merge feature-8.4 docs

CONTRIBUTING.md
PR fixes the license reference in `CONTRIBUTING.md`.
=> docs: update license reference

static/usage/v7/animations/basic/angular/example_component_ts.md, static/usage/v7/animations/before-and-after-hooks/angular/example_component_ts.md, static/usage/v7/animations/chain/angular/example_component_ts.md, static/usage/v7/animations/gesture/angular/example_component_ts.md, static/usage/v7/animations/group/angular/example_component_ts.md, static/usage/v7/animations/keyframes/angular/example_component_ts.md, static/usage/v7/animations/modal-override/angular/example_component_ts.md, static/usage/v7/animations/preference-based/angular/example_component_ts.md, static/usage/v7/modal/styling/animations/angular/example_component_ts.md, static/usage/v8/animations/basic/angular/example_component_ts.md, static/usage/v8/animations/before-and-after-hooks/angular/example_component_ts.md, static/usage/v8/animations/chain/angular/example_component_ts.md, static/usage/v8/animations/gesture/angular/example_component_ts.md, static/usage/v8/animations/group/angular/example_component_ts.md, static/usage/v8/animations/keyframes/angular/example_component_ts.md, static/usage/v8/animations/modal-override/angular/example_component_ts.md, static/usage/v8/animations/preference-based/angular/example_component_ts.md, static/usage/v8/modal/styling/animations/angular/example_component_ts.md
[Preview](https://ionic-docs-git-rou-11416-animations-ionic1.vercel.app/docs/utilities/animations)
=> docs(animations): update angular to standalone

static/usage/v8/input-password-toggle/basic/vue.md
=> docs(input-password-toggle): update vue import

docs/api/toast.md
=> docs(toast): remove cssClass property from ToastButton interface
